package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator generates Dart code from parsed structs
type Generator struct {
	outputDir string
	tmpl      *template.Template
}

// NewGenerator creates a new generator
func NewGenerator(outputDir string) *Generator {
	tmpl := template.Must(template.New("dart").Funcs(template.FuncMap{
		"toDartType":       toDartType,
		"toSnakeCase":      toSnakeCase,
		"toCamelCase":      toCamelCase,
		"toClassName":      toClassName,
		"needsImport":      needsImport,
		"getImports":       getImports,
		"isNullable":       isNullable,
		"defaultValue":     defaultValue,
		"getRequiredFields": getRequiredFields,
	}).Parse(dartTemplate))

	return &Generator{
		outputDir: outputDir,
		tmpl:      tmpl,
	}
}

// Generate generates a Dart file for a struct
func (g *Generator) Generate(s Struct) error {
	// Ensure output directory exists
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate file path
	fileName := toSnakeCase(s.Name) + ".dart"
	filePath := filepath.Join(g.outputDir, fileName)

	// Create file
	file, err := os.Create(filePath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	// Execute template
	if err := g.tmpl.Execute(file, s); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

// toDartType converts a Go type to a Dart type
func toDartType(goType string, isOptional bool, isCollection bool, collectionOf string) string {
	var dartType string

	if isCollection {
		elemType := mapGoTypeToDart(collectionOf)
		dartType = fmt.Sprintf("List<%s>", elemType)
	} else {
		dartType = mapGoTypeToDart(goType)
	}

	if isOptional {
		return dartType + "?"
	}
	return dartType
}

// mapGoTypeToDart maps Go types to Dart types
func mapGoTypeToDart(goType string) string {
	// Handle qualified types (pkg.Type)
	if strings.Contains(goType, ".") {
		parts := strings.Split(goType, ".")
		pkg := parts[0]
		typeName := parts[1]

		switch pkg {
		case "uuid":
			return "String" // uuid.UUID -> String
		case "time":
			return "DateTime" // time.Time -> DateTime
		case "pq":
			if typeName == "StringArray" {
				return "List<String>"
			}
		case "datatypes":
			if typeName == "JSON" {
				return "Map<String, dynamic>"
			}
		case "gorm":
			if typeName == "DeletedAt" {
				return "DateTime" // gorm.DeletedAt -> DateTime
			}
		}

		// Default: assume it's a custom type, use the type name
		return toClassName(typeName)
	}

	// Handle simple types
	switch goType {
	case "string":
		return "String"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "double"
	case "bool":
		return "bool"
	case "interface{}", "any":
		return "dynamic"
	case "Map":
		return "Map<String, dynamic>"
	default:
		// Assume it's a custom struct type
		return toClassName(goType)
	}
}

// needsImport checks if a field needs an import
func needsImport(field Field) bool {
	typeName := field.CollectionOf
	if typeName == "" {
		typeName = field.Type
	}

	// Check if it's a custom type (not a primitive)
	dartType := mapGoTypeToDart(typeName)
	primitives := []string{"String", "int", "double", "bool", "DateTime", "dynamic", "List", "Map"}

	for _, prim := range primitives {
		if strings.HasPrefix(dartType, prim) {
			return false
		}
	}

	return true
}

// getImports returns all necessary imports for a struct
func getImports(s Struct) (imports []string) {
	for _, field := range s.Fields {
		if needsImport(field) {
			typeName := field.CollectionOf
			if typeName == "" {
				typeName = field.Type
			}

			imports = append(imports, toSnakeCase(mapGoTypeToDart(typeName)) + ".dart")
		}
	}
	return
}

// isNullable checks if a field is nullable
func isNullable(field Field) bool {
	return field.IsOptional
}

// defaultValue returns the default value for a field in constructor
func defaultValue(field Field) string {
	if field.IsOptional {
		return ""
	}
	return "required "
}

// getRequiredFields returns a list of JSON field names that are marked as required
func getRequiredFields(s Struct) []string {
	var required []string
	for _, field := range s.Fields {
		if field.IsRequired {
			required = append(required, field.JsonTag)
		}
	}
	return required
}

// Dart template
const dartTemplate = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
{{- range $import := getImports . }}
import '{{ $import }}';
{{- end }}

part '{{ toSnakeCase .Name }}.g.dart';

@JsonSerializable(explicitToJson: true)
class {{ .Name }} {
{{- $requiredFields := getRequiredFields . }}
{{- if $requiredFields }}
  // Fields marked as required in the backend model
  static const List<String> requiredFields = [
{{- range $i, $field := $requiredFields }}
{{- if $i }},{{ end }}
    '{{ $field }}'
{{- end }}
  ];
{{- end }}

{{- range .Fields }}
  @JsonKey(name: '{{ .JsonTag }}')
  final {{ toDartType .Type .IsOptional .IsCollection .CollectionOf }} {{ toCamelCase .Name }};
{{- end }}

  {{ .Name }}({
{{- range .Fields }}
    {{ defaultValue . }}this.{{ toCamelCase .Name }},
{{- end }}
  });

  factory {{ .Name }}.fromJson(Map<String, dynamic> json) => _${{ .Name }}FromJson(json);

  Map<String, dynamic> toJson() => _${{ .Name }}ToJson(this);
}
`
