-- Migration: Convert exercises rationale from array to map
-- This migration transforms the reasoning.exercises[].rationale field
-- from []string (array of tags) to map[string]string (category -> reason)
--
-- Before: {"exercises": [{"id": "push-up", "rationale": ["goal", "muscle"]}]}
-- After:  {"exercises": [{"id": "push-up", "rationale": {"goal": "builds chest strength", "muscle": "targets pectorals"}}]}
--
-- NOTE: Existing data will have empty rationale maps since the old format
-- cannot be automatically converted to meaningful descriptions.
-- New trainings will have proper rationale maps generated by the LLM.

-- Step 1: Update all trainings to convert rationale arrays to empty maps
UPDATE trainings
SET reasoning = jsonb_set(
    reasoning,
    '{exercises}',
    (
        SELECT COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'id', exercise->>'id',
                    'rationale', '{}'::jsonb
                )
            ),
            '[]'::jsonb
        )
        FROM jsonb_array_elements(reasoning->'exercises') AS exercise
    )
)
WHERE reasoning->'exercises' IS NOT NULL
  AND jsonb_array_length(reasoning->'exercises') > 0;

-- Step 2: Verify migration (optional - run to check results)
-- SELECT id, reasoning->'exercises' FROM trainings LIMIT 5;
