// Code generated by qtc from "gen_training.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/gen_training.qtpl:1
package prompt

//line llm/prompt/gen_training.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/prompt/gen_training.qtpl:4
import exercisedb "github.com/streambinder/vigor/exercisedb/model"

//line llm/prompt/gen_training.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/gen_training.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/gen_training.qtpl:6
func StreamGenTraining(qw422016 *qt422016.Writer, profile *model.Profile, exercises []exercisedb.Exercise, duration int) {
//line llm/prompt/gen_training.qtpl:7
	qw422016.N().S(` Generate a `)
//line llm/prompt/gen_training.qtpl:9
	qw422016.N().D(duration)
//line llm/prompt/gen_training.qtpl:9
	qw422016.N().S(`min training from these exercises: `)
//line llm/prompt/gen_training.qtpl:10
	for _, exercise := range exercises {
//line llm/prompt/gen_training.qtpl:10
		qw422016.N().S(` ID: `)
//line llm/prompt/gen_training.qtpl:11
		qw422016.E().S(exercise.ID)
//line llm/prompt/gen_training.qtpl:11
		qw422016.N().S(`, `)
//line llm/prompt/gen_training.qtpl:12
	}
//line llm/prompt/gen_training.qtpl:12
	qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:15
}

//line llm/prompt/gen_training.qtpl:15
func WriteGenTraining(qq422016 qtio422016.Writer, profile *model.Profile, exercises []exercisedb.Exercise, duration int) {
//line llm/prompt/gen_training.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/gen_training.qtpl:15
	StreamGenTraining(qw422016, profile, exercises, duration)
//line llm/prompt/gen_training.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/gen_training.qtpl:15
}

//line llm/prompt/gen_training.qtpl:15
func GenTraining(profile *model.Profile, exercises []exercisedb.Exercise, duration int) string {
//line llm/prompt/gen_training.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/gen_training.qtpl:15
	WriteGenTraining(qb422016, profile, exercises, duration)
//line llm/prompt/gen_training.qtpl:15
	qs422016 := string(qb422016.B)
//line llm/prompt/gen_training.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/gen_training.qtpl:15
	return qs422016
//line llm/prompt/gen_training.qtpl:15
}
