// Code generated by qtc from "gen_training.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/gen_training.qtpl:1
package prompt

//line llm/prompt/gen_training.qtpl:3
import "strings"

//line llm/prompt/gen_training.qtpl:4
import "github.com/streambinder/vigor/model"

//line llm/prompt/gen_training.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/gen_training.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/gen_training.qtpl:6
func StreamGenTraining(qw422016 *qt422016.Writer, profile model.Profile, exercises []model.Exercise, duration int, recentTrainings []model.Training) {
//line llm/prompt/gen_training.qtpl:7
	qw422016.N().S(` Generate `)
//line llm/prompt/gen_training.qtpl:9
	qw422016.N().D(duration)
//line llm/prompt/gen_training.qtpl:9
	qw422016.N().S(`min training from these exercises: `)
//line llm/prompt/gen_training.qtpl:10
	for _, exercise := range exercises {
//line llm/prompt/gen_training.qtpl:10
		qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:11
		qw422016.E().S(exercise.ID)
//line llm/prompt/gen_training.qtpl:11
		qw422016.N().S(` ( `)
//line llm/prompt/gen_training.qtpl:12
		if len(exercise.Instructions) > 0 {
//line llm/prompt/gen_training.qtpl:12
			qw422016.N().S(`Instructions: `)
//line llm/prompt/gen_training.qtpl:12
			qw422016.E().S(strings.Join(exercise.Instructions, ", "))
//line llm/prompt/gen_training.qtpl:12
		}
//line llm/prompt/gen_training.qtpl:12
		qw422016.N().S(`. `)
//line llm/prompt/gen_training.qtpl:13
		if len(exercise.Muscles) > 0 {
//line llm/prompt/gen_training.qtpl:13
			qw422016.N().S(`Target muscles: `)
//line llm/prompt/gen_training.qtpl:13
			qw422016.E().S(strings.Join(exercise.Muscles, ", "))
//line llm/prompt/gen_training.qtpl:13
		}
//line llm/prompt/gen_training.qtpl:13
		qw422016.N().S(`. `)
//line llm/prompt/gen_training.qtpl:14
		if len(exercise.SecondaryMuscles) > 0 {
//line llm/prompt/gen_training.qtpl:14
			qw422016.N().S(`Secondary muscles: `)
//line llm/prompt/gen_training.qtpl:14
			qw422016.E().S(strings.Join(exercise.SecondaryMuscles, ", "))
//line llm/prompt/gen_training.qtpl:14
		}
//line llm/prompt/gen_training.qtpl:14
		qw422016.N().S(`. `)
//line llm/prompt/gen_training.qtpl:15
		if len(exercise.BodyParts) > 0 {
//line llm/prompt/gen_training.qtpl:15
			qw422016.N().S(`Body parts: `)
//line llm/prompt/gen_training.qtpl:15
			qw422016.E().S(strings.Join(exercise.BodyParts, ", "))
//line llm/prompt/gen_training.qtpl:15
		}
//line llm/prompt/gen_training.qtpl:15
		qw422016.N().S(`. `)
//line llm/prompt/gen_training.qtpl:16
		if len(exercise.Equipment) > 0 {
//line llm/prompt/gen_training.qtpl:16
			qw422016.N().S(`Equipment: `)
//line llm/prompt/gen_training.qtpl:16
			qw422016.E().S(strings.Join(exercise.Equipment, ", "))
//line llm/prompt/gen_training.qtpl:16
		}
//line llm/prompt/gen_training.qtpl:16
		qw422016.N().S(`. ); `)
//line llm/prompt/gen_training.qtpl:18
	}
//line llm/prompt/gen_training.qtpl:18
	qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:20
	if len(recentTrainings) > 0 {
//line llm/prompt/gen_training.qtpl:20
		qw422016.N().S(` Recent training history (consider variety and progression): `)
//line llm/prompt/gen_training.qtpl:22
		for _, training := range recentTrainings {
//line llm/prompt/gen_training.qtpl:22
			qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:23
			qw422016.E().S(training.Type)
//line llm/prompt/gen_training.qtpl:23
			qw422016.N().S(` workout `)
//line llm/prompt/gen_training.qtpl:23
			qw422016.E().S(training.Name)
//line llm/prompt/gen_training.qtpl:23
			qw422016.N().S(` (`)
//line llm/prompt/gen_training.qtpl:23
			qw422016.N().D(training.DaysSince())
//line llm/prompt/gen_training.qtpl:23
			qw422016.N().S(` days ago): `)
//line llm/prompt/gen_training.qtpl:24
			qw422016.E().S(training.Description)
//line llm/prompt/gen_training.qtpl:24
			qw422016.N().S(` (exercises: `)
//line llm/prompt/gen_training.qtpl:26
			for _, routine := range training.Routines {
//line llm/prompt/gen_training.qtpl:26
				qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:27
				for _, block := range routine.Blocks {
//line llm/prompt/gen_training.qtpl:27
					qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:28
					for _, activity := range block.Activities {
//line llm/prompt/gen_training.qtpl:28
						qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:29
						if activity.Type == "exercise" {
//line llm/prompt/gen_training.qtpl:29
							qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:30
							qw422016.E().S(activity.Name)
//line llm/prompt/gen_training.qtpl:30
							qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:31
							if activity.WeightKg > 0 {
//line llm/prompt/gen_training.qtpl:31
								qw422016.N().S(` at `)
//line llm/prompt/gen_training.qtpl:32
								qw422016.N().D(activity.WeightKg)
//line llm/prompt/gen_training.qtpl:32
								qw422016.N().S(`kg `)
//line llm/prompt/gen_training.qtpl:33
							}
//line llm/prompt/gen_training.qtpl:33
							qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:34
							if activity.Reps > 0 {
//line llm/prompt/gen_training.qtpl:34
								qw422016.N().S(` for `)
//line llm/prompt/gen_training.qtpl:35
								qw422016.N().D(activity.WeightKg)
//line llm/prompt/gen_training.qtpl:35
								qw422016.N().S(` reps `)
//line llm/prompt/gen_training.qtpl:36
							}
//line llm/prompt/gen_training.qtpl:36
							qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:37
							if activity.Duration > 0 {
//line llm/prompt/gen_training.qtpl:37
								qw422016.N().S(` for `)
//line llm/prompt/gen_training.qtpl:38
								qw422016.N().D(activity.Duration)
//line llm/prompt/gen_training.qtpl:38
								qw422016.N().S(`s `)
//line llm/prompt/gen_training.qtpl:39
							}
//line llm/prompt/gen_training.qtpl:39
							qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:40
							if len(activity.Feedback) > 0 {
//line llm/prompt/gen_training.qtpl:40
								qw422016.N().S(` wth feedback "`)
//line llm/prompt/gen_training.qtpl:41
								qw422016.E().S(activity.Feedback)
//line llm/prompt/gen_training.qtpl:41
								qw422016.N().S(`" `)
//line llm/prompt/gen_training.qtpl:42
							}
//line llm/prompt/gen_training.qtpl:42
							qw422016.N().S(` ; `)
//line llm/prompt/gen_training.qtpl:44
						}
//line llm/prompt/gen_training.qtpl:44
						qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:45
					}
//line llm/prompt/gen_training.qtpl:45
					qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:46
				}
//line llm/prompt/gen_training.qtpl:46
				qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:47
			}
//line llm/prompt/gen_training.qtpl:47
			qw422016.N().S(` ); `)
//line llm/prompt/gen_training.qtpl:49
		}
//line llm/prompt/gen_training.qtpl:49
		qw422016.N().S(`. `)
//line llm/prompt/gen_training.qtpl:50
	}
//line llm/prompt/gen_training.qtpl:50
	qw422016.N().S(` `)
//line llm/prompt/gen_training.qtpl:53
}

//line llm/prompt/gen_training.qtpl:53
func WriteGenTraining(qq422016 qtio422016.Writer, profile model.Profile, exercises []model.Exercise, duration int, recentTrainings []model.Training) {
//line llm/prompt/gen_training.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/gen_training.qtpl:53
	StreamGenTraining(qw422016, profile, exercises, duration, recentTrainings)
//line llm/prompt/gen_training.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/gen_training.qtpl:53
}

//line llm/prompt/gen_training.qtpl:53
func GenTraining(profile model.Profile, exercises []model.Exercise, duration int, recentTrainings []model.Training) string {
//line llm/prompt/gen_training.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/gen_training.qtpl:53
	WriteGenTraining(qb422016, profile, exercises, duration, recentTrainings)
//line llm/prompt/gen_training.qtpl:53
	qs422016 := string(qb422016.B)
//line llm/prompt/gen_training.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/gen_training.qtpl:53
	return qs422016
//line llm/prompt/gen_training.qtpl:53
}
