// Code generated by qtc from "system.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line system.qtpl:1
package prompt

//line system.qtpl:3
import "github.com/streambinder/vigor/model"

//line system.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line system.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line system.qtpl:5
func StreamSystem(qw422016 *qt422016.Writer, profile *model.Profile, schema string) {
//line system.qtpl:6
	qw422016.N().S(` You are a personal trainer who helps people to achieve their fitness goals. `)
//line system.qtpl:10
	if len(profile.Goals()) > 0 {
//line system.qtpl:10
		qw422016.N().S(` The target goals are: `)
//line system.qtpl:12
		for _, goal := range profile.Goals() {
//line system.qtpl:12
			qw422016.N().S(` `)
//line system.qtpl:13
			qw422016.E().S(goal.Description)
//line system.qtpl:13
			qw422016.N().S(` (started: `)
//line system.qtpl:13
			qw422016.E().S(goal.StartDate.Format("2006-01-02"))
//line system.qtpl:13
			qw422016.N().S(`), `)
//line system.qtpl:14
		}
//line system.qtpl:14
		qw422016.N().S(` `)
//line system.qtpl:15
	}
//line system.qtpl:15
	qw422016.N().S(` Profile details include: `)
//line system.qtpl:18
	qw422016.E().S(profile.Language)
//line system.qtpl:18
	qw422016.N().S(` language; `)
//line system.qtpl:19
	qw422016.E().S(profile.Birthdate.Format("2006-01-02"))
//line system.qtpl:19
	qw422016.N().S(` (age `)
//line system.qtpl:19
	qw422016.N().D(profile.Age())
//line system.qtpl:19
	qw422016.N().S(`) birthdate; `)
//line system.qtpl:20
	qw422016.N().F(profile.Height)
//line system.qtpl:20
	qw422016.N().S(`cm height; `)
//line system.qtpl:21
	qw422016.N().F(profile.Weight)
//line system.qtpl:21
	qw422016.N().S(`kg weight; `)
//line system.qtpl:22
	if len(profile.Injuries()) > 0 {
//line system.qtpl:22
		qw422016.N().S(` `)
//line system.qtpl:23
		for _, injury := range profile.Injuries() {
//line system.qtpl:23
			qw422016.N().S(` `)
//line system.qtpl:24
			qw422016.E().S(injury.Description)
//line system.qtpl:24
			qw422016.N().S(` (year: `)
//line system.qtpl:24
			qw422016.N().D(injury.Year)
//line system.qtpl:24
			qw422016.N().S(`), `)
//line system.qtpl:25
		}
//line system.qtpl:25
		qw422016.N().S(` injury history; `)
//line system.qtpl:27
	}
//line system.qtpl:27
	qw422016.N().S(` `)
//line system.qtpl:28
	if len(profile.Limitations()) > 0 {
//line system.qtpl:28
		qw422016.N().S(` `)
//line system.qtpl:29
		for _, limitation := range profile.Limitations() {
//line system.qtpl:29
			qw422016.N().S(` `)
//line system.qtpl:30
			qw422016.E().S(limitation)
//line system.qtpl:30
			qw422016.N().S(`, `)
//line system.qtpl:31
		}
//line system.qtpl:31
		qw422016.N().S(` `)
//line system.qtpl:32
	}
//line system.qtpl:32
	qw422016.N().S(` You must always speak the profile language. You must always respond with a JSON with this structure: `)
//line system.qtpl:35
	qw422016.N().S(schema)
//line system.qtpl:35
	qw422016.N().S(` `)
//line system.qtpl:38
}

//line system.qtpl:38
func WriteSystem(qq422016 qtio422016.Writer, profile *model.Profile, schema string) {
//line system.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line system.qtpl:38
	StreamSystem(qw422016, profile, schema)
//line system.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line system.qtpl:38
}

//line system.qtpl:38
func System(profile *model.Profile, schema string) string {
//line system.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line system.qtpl:38
	WriteSystem(qb422016, profile, schema)
//line system.qtpl:38
	qs422016 := string(qb422016.B)
//line system.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line system.qtpl:38
	return qs422016
//line system.qtpl:38
}
