// Code generated by qtc from "system.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/system.qtpl:1
package prompt

//line llm/prompt/system.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/prompt/system.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/system.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/system.qtpl:5
func StreamSystem(qw422016 *qt422016.Writer, profile *model.Profile, schema string) {
//line llm/prompt/system.qtpl:6
	qw422016.N().S(` Personal trainer. Create workouts to achieve fitness goals. `)
//line llm/prompt/system.qtpl:10
	if len(profile.Goals()) > 0 {
//line llm/prompt/system.qtpl:10
		qw422016.N().S(`Goals: `)
//line llm/prompt/system.qtpl:10
		for i, goal := range profile.Goals() {
//line llm/prompt/system.qtpl:10
			qw422016.E().S(goal.Description)
//line llm/prompt/system.qtpl:10
			if i < len(profile.Goals())-1 {
//line llm/prompt/system.qtpl:10
				qw422016.N().S(`, `)
//line llm/prompt/system.qtpl:10
			}
//line llm/prompt/system.qtpl:10
		}
//line llm/prompt/system.qtpl:10
		qw422016.N().S(` `)
//line llm/prompt/system.qtpl:11
	}
//line llm/prompt/system.qtpl:11
	qw422016.N().S(` Profile: age `)
//line llm/prompt/system.qtpl:12
	qw422016.N().D(profile.Age())
//line llm/prompt/system.qtpl:12
	qw422016.N().S(`, `)
//line llm/prompt/system.qtpl:12
	qw422016.N().F(profile.Height)
//line llm/prompt/system.qtpl:12
	qw422016.N().S(`cm, `)
//line llm/prompt/system.qtpl:12
	qw422016.N().F(profile.Weight)
//line llm/prompt/system.qtpl:12
	qw422016.N().S(`kg`)
//line llm/prompt/system.qtpl:12
	if len(profile.Injuries()) > 0 {
//line llm/prompt/system.qtpl:12
		qw422016.N().S(` Injuries: `)
//line llm/prompt/system.qtpl:13
		for i, injury := range profile.Injuries() {
//line llm/prompt/system.qtpl:13
			qw422016.E().S(injury.Description)
//line llm/prompt/system.qtpl:13
			if i < len(profile.Injuries())-1 {
//line llm/prompt/system.qtpl:13
				qw422016.N().S(`, `)
//line llm/prompt/system.qtpl:13
			}
//line llm/prompt/system.qtpl:13
		}
//line llm/prompt/system.qtpl:13
	}
//line llm/prompt/system.qtpl:13
	if len(profile.Limitations()) > 0 {
//line llm/prompt/system.qtpl:13
		qw422016.N().S(` Limits: `)
//line llm/prompt/system.qtpl:14
		for i, limitation := range profile.Limitations() {
//line llm/prompt/system.qtpl:14
			qw422016.E().S(limitation)
//line llm/prompt/system.qtpl:14
			if i < len(profile.Limitations())-1 {
//line llm/prompt/system.qtpl:14
				qw422016.N().S(`, `)
//line llm/prompt/system.qtpl:14
			}
//line llm/prompt/system.qtpl:14
		}
//line llm/prompt/system.qtpl:14
	}
//line llm/prompt/system.qtpl:14
	qw422016.N().S(` Respond in `)
//line llm/prompt/system.qtpl:16
	qw422016.E().S(profile.Language)
//line llm/prompt/system.qtpl:16
	qw422016.N().S(` using JSON: `)
//line llm/prompt/system.qtpl:16
	qw422016.N().S(schema)
//line llm/prompt/system.qtpl:16
	qw422016.N().S(` `)
//line llm/prompt/system.qtpl:19
}

//line llm/prompt/system.qtpl:19
func WriteSystem(qq422016 qtio422016.Writer, profile *model.Profile, schema string) {
//line llm/prompt/system.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/system.qtpl:19
	StreamSystem(qw422016, profile, schema)
//line llm/prompt/system.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/system.qtpl:19
}

//line llm/prompt/system.qtpl:19
func System(profile *model.Profile, schema string) string {
//line llm/prompt/system.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/system.qtpl:19
	WriteSystem(qb422016, profile, schema)
//line llm/prompt/system.qtpl:19
	qs422016 := string(qb422016.B)
//line llm/prompt/system.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/system.qtpl:19
	return qs422016
//line llm/prompt/system.qtpl:19
}
