// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'activity.g.dart';

@JsonSerializable(explicitToJson: true)
class Activity {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'block_id', defaultValue: '')
  final String blockId;
  @JsonKey(name: 'exercise_id', defaultValue: '')
  final String exerciseId;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'reps')
  final int reps;
  @JsonKey(name: 'weight_kg')
  final int weightKg;
  @JsonKey(name: 'modifiers', defaultValue: [])
  final List<String> modifiers;
  @JsonKey(name: 'rest')
  final int rest;
  @JsonKey(name: 'detail', defaultValue: {})
  final Map<String, dynamic> detail;

  Activity({
    required this.id,
    required this.blockId,
    required this.exerciseId,
    required this.name,
    required this.duration,
    required this.reps,
    required this.weightKg,
    required this.modifiers,
    required this.rest,
    required this.detail,
  });

  factory Activity.fromJson(Map<String, dynamic> json) => _$ActivityFromJson(json);

  Map<String, dynamic> toJson() => _$ActivityToJson(this);
}
