// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'activity.g.dart';

@JsonSerializable(explicitToJson: true)
class Activity {
  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'block_id')
  final String blockId;
  @JsonKey(name: 'name')
  final String name;
  @JsonKey(name: 'rationale')
  final String rationale;
  @JsonKey(name: 'type')
  final String type;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'reps')
  final int reps;
  @JsonKey(name: 'weight_kg')
  final int weightKg;
  @JsonKey(name: 'rest')
  final int rest;
  @JsonKey(name: 'detail')
  final Map<String, dynamic> detail;
  @JsonKey(name: 'feedback')
  final String feedback;

  Activity({
    required this.id,
    required this.blockId,
    required this.name,
    required this.rationale,
    required this.type,
    required this.duration,
    required this.reps,
    required this.weightKg,
    required this.rest,
    required this.detail,
    required this.feedback,
  });

  factory Activity.fromJson(Map<String, dynamic> json) => _$ActivityFromJson(json);

  Map<String, dynamic> toJson() => _$ActivityToJson(this);
}
