// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'avatar.g.dart';

@JsonSerializable(explicitToJson: true)
class Avatar {
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;

  Avatar({
    required this.userId,
  });

  factory Avatar.fromJson(Map<String, dynamic> json) => _$AvatarFromJson(json);

  Map<String, dynamic> toJson() => _$AvatarToJson(this);
}
