// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'classic.dart';

part 'classic_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class ClassicEmbedding {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'text', defaultValue: '')
  final String text;
  @JsonKey(name: 'classic_id', defaultValue: '')
  final String classicId;
  @JsonKey(name: 'classic')
  final Classic classic;

  ClassicEmbedding({
    required this.id,
    required this.text,
    required this.classicId,
    required this.classic,
  });

  factory ClassicEmbedding.fromJson(Map<String, dynamic> json) => _$ClassicEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$ClassicEmbeddingToJson(this);
}
