// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'classic.g.dart';

@JsonSerializable(explicitToJson: true)
class Classic {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'type', defaultValue: '')
  final String type;
  @JsonKey(name: 'excerpt', defaultValue: '')
  final String excerpt;

  Classic({
    required this.id,
    required this.name,
    required this.type,
    required this.excerpt,
  });

  factory Classic.fromJson(Map<String, dynamic> json) => _$ClassicFromJson(json);

  Map<String, dynamic> toJson() => _$ClassicToJson(this);
}
