// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'exercise.dart';

part 'equipment.g.dart';

@JsonSerializable(explicitToJson: true)
class Equipment {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'aliases')
  final List<String>? aliases;
  @JsonKey(name: 'exercises')
  final List<Exercise>? exercises;

  Equipment({
    required this.id,
    this.aliases,
    this.exercises,
  });

  factory Equipment.fromJson(Map<String, dynamic> json) => _$EquipmentFromJson(json);

  Map<String, dynamic> toJson() => _$EquipmentToJson(this);
}
