// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'equipment.dart';

part 'equipment_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class EquipmentEmbedding {
  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'text', defaultValue: '')
  final String text;
  @JsonKey(name: 'equipment_id', defaultValue: '')
  final String equipmentId;
  @JsonKey(name: 'equipment')
  final Equipment equipment;

  EquipmentEmbedding({
    required this.id,
    required this.text,
    required this.equipmentId,
    required this.equipment,
  });

  factory EquipmentEmbedding.fromJson(Map<String, dynamic> json) => _$EquipmentEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$EquipmentEmbeddingToJson(this);
}
