// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'exercise.dart';

part 'equipment_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class EquipmentEmbedding {
  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'text', defaultValue: '')
  final String text;
  @JsonKey(name: 'exercises', defaultValue: const [])
  final List<Exercise> exercises;

  EquipmentEmbedding({
    required this.id,
    required this.text,
    required this.exercises,
  });

  factory EquipmentEmbedding.fromJson(Map<String, dynamic> json) => _$EquipmentEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$EquipmentEmbeddingToJson(this);
}
