// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'exercise.dart';

part 'exercise_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class ExerciseEmbedding {
  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'text', defaultValue: '')
  final String text;
  @JsonKey(name: 'exercise_id', defaultValue: '')
  final String exerciseId;
  @JsonKey(name: 'exercise')
  final Exercise exercise;

  ExerciseEmbedding({
    required this.id,
    required this.text,
    required this.exerciseId,
    required this.exercise,
  });

  factory ExerciseEmbedding.fromJson(Map<String, dynamic> json) => _$ExerciseEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$ExerciseEmbeddingToJson(this);
}
