// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'exercise_selection.g.dart';

@JsonSerializable(explicitToJson: true)
class ExerciseSelection {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'rationale', defaultValue: [])
  final List<String> rationale;

  ExerciseSelection({
    required this.id,
    required this.rationale,
  });

  factory ExerciseSelection.fromJson(Map<String, dynamic> json) => _$ExerciseSelectionFromJson(json);

  Map<String, dynamic> toJson() => _$ExerciseSelectionToJson(this);
}
