// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'exercise_density.g.dart';

@JsonSerializable(explicitToJson: true)
class ExerciseDensity {
  @JsonKey(name: 'min')
  final int min;
  @JsonKey(name: 'max')
  final int max;

  ExerciseDensity({
    required this.min,
    required this.max,
  });

  factory ExerciseDensity.fromJson(Map<String, dynamic> json) => _$ExerciseDensityFromJson(json);

  Map<String, dynamic> toJson() => _$ExerciseDensityToJson(this);
}
