// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'exercise.g.dart';

@JsonSerializable(explicitToJson: true)
class Exercise {
  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'name')
  final String name;
  @JsonKey(name: 'equipment', defaultValue: const [])
  final List<String> equipment;
  @JsonKey(name: 'muscles', defaultValue: const [])
  final List<String> muscles;
  @JsonKey(name: 'reference')
  final String reference;
  @JsonKey(name: 'instructions', defaultValue: const [])
  final List<String> instructions;

  Exercise({
    required this.id,
    required this.name,
    required this.equipment,
    required this.muscles,
    required this.reference,
    required this.instructions,
  });

  factory Exercise.fromJson(Map<String, dynamic> json) => _$ExerciseFromJson(json);

  Map<String, dynamic> toJson() => _$ExerciseToJson(this);
}
