// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'external_workout_summary.g.dart';

@JsonSerializable(explicitToJson: true)
class ExternalWorkoutSummary {
  @JsonKey(name: 'days_ago')
  final int daysAgo;
  @JsonKey(name: 'exercise_type', defaultValue: '')
  final String exerciseType;
  @JsonKey(name: 'duration_mins')
  final int durationMins;

  ExternalWorkoutSummary({
    required this.daysAgo,
    required this.exerciseType,
    required this.durationMins,
  });

  factory ExternalWorkoutSummary.fromJson(Map<String, dynamic> json) => _$ExternalWorkoutSummaryFromJson(json);

  Map<String, dynamic> toJson() => _$ExternalWorkoutSummaryToJson(this);
}
