// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'fact.dart';

part 'fact_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class FactEmbedding {
  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'text')
  final String text;
  @JsonKey(name: 'fact_id')
  final String factId;
  @JsonKey(name: 'fact')
  final Fact fact;

  FactEmbedding({
    required this.id,
    required this.text,
    required this.factId,
    required this.fact,
  });

  factory FactEmbedding.fromJson(Map<String, dynamic> json) => _$FactEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$FactEmbeddingToJson(this);
}
