// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'fact.g.dart';

@JsonSerializable(explicitToJson: true)
class Fact {
  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'reference')
  final String reference;
  @JsonKey(name: 'area')
  final String area;
  @JsonKey(name: 'tags', defaultValue: const [])
  final List<String> tags;
  @JsonKey(name: 'content')
  final String content;

  Fact({
    required this.id,
    required this.reference,
    required this.area,
    required this.tags,
    required this.content,
  });

  factory Fact.fromJson(Map<String, dynamic> json) => _$FactFromJson(json);

  Map<String, dynamic> toJson() => _$FactToJson(this);
}
