// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'family_progress.g.dart';

@JsonSerializable(explicitToJson: true)
class FamilyProgress {
  @JsonKey(name: 'capability')
  final double capability;
  @JsonKey(name: 'calibration')
  final double calibration;

  FamilyProgress({
    required this.capability,
    required this.calibration,
  });

  factory FamilyProgress.fromJson(Map<String, dynamic> json) => _$FamilyProgressFromJson(json);

  Map<String, dynamic> toJson() => _$FamilyProgressToJson(this);
}
