// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'flow_pose.g.dart';

@JsonSerializable(explicitToJson: true)
class FlowPose {
  @JsonKey(name: 'exercise_id', defaultValue: '')
  final String exerciseId;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'rest')
  final int rest;
  @JsonKey(name: 'detail', defaultValue: {})
  final Map<String, dynamic> detail;

  FlowPose({
    required this.exerciseId,
    required this.name,
    required this.duration,
    required this.rest,
    required this.detail,
  });

  factory FlowPose.fromJson(Map<String, dynamic> json) => _$FlowPoseFromJson(json);

  Map<String, dynamic> toJson() => _$FlowPoseToJson(this);
}
