// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'training_reference.dart';
import 'flow_pose.dart';
import 'llm_step.dart';
import 'training_prompt.dart';

part 'flow_session.g.dart';

@JsonSerializable(explicitToJson: true)
class FlowSession {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'description', defaultValue: '')
  final String description;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'muscles', defaultValue: [])
  final List<String> muscles;
  @JsonKey(name: 'request', defaultValue: '')
  final String request;
  @JsonKey(name: 'references', defaultValue: [])
  final List<TrainingReference> references;
  @JsonKey(name: 'fact_indices', defaultValue: [])
  final List<int> factIndices;
  @JsonKey(name: 'poses', defaultValue: [])
  final List<FlowPose> poses;
  @JsonKey(name: 'llm_steps', defaultValue: [])
  final List<LLMStep> lLMSteps;
  @JsonKey(name: 'prompt')
  final TrainingPrompt prompt;
  @JsonKey(name: 'completed_at', toJson: _nullableDateTimeToJson)
  final DateTime? completedAt;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;
  @JsonKey(name: 'updated_at', toJson: _dateTimeToJson)
  final DateTime updatedAt;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;

  FlowSession({
    required this.id,
    required this.name,
    required this.description,
    required this.duration,
    required this.muscles,
    required this.request,
    required this.references,
    required this.factIndices,
    required this.poses,
    required this.lLMSteps,
    required this.prompt,
    this.completedAt,
    required this.createdAt,
    required this.updatedAt,
    required this.userId,
  });

  factory FlowSession.fromJson(Map<String, dynamic> json) => _$FlowSessionFromJson(json);

  Map<String, dynamic> toJson() => _$FlowSessionToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();

  static String? _nullableDateTimeToJson(DateTime? dt) => dt?.toUtc().toIso8601String();
}
