// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'goal.dart';

part 'goal_embedding.g.dart';

@JsonSerializable(explicitToJson: true)
class GoalEmbedding {
  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'text', defaultValue: '')
  final String text;
  @JsonKey(name: 'goal_id', defaultValue: '')
  final String goalId;
  @JsonKey(name: 'goal')
  final Goal goal;

  GoalEmbedding({
    required this.id,
    required this.text,
    required this.goalId,
    required this.goal,
  });

  factory GoalEmbedding.fromJson(Map<String, dynamic> json) => _$GoalEmbeddingFromJson(json);

  Map<String, dynamic> toJson() => _$GoalEmbeddingToJson(this);
}
