// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'goal.g.dart';

@JsonSerializable(explicitToJson: true)
class Goal {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'description')
  final String? description;
  @JsonKey(name: 'aliases')
  final List<String>? aliases;
  @JsonKey(name: 'sessions_per_week')
  final List<int>? sessionsPerWeek;
  @JsonKey(name: 'session_duration_mins')
  final List<int>? sessionDurationMins;
  @JsonKey(name: 'methodology_weights')
  final Map<String, dynamic>? methodologyWeights;
  @JsonKey(name: 'preferred_hours')
  final List<int>? preferredHours;

  Goal({
    required this.id,
    this.description,
    this.aliases,
    this.sessionsPerWeek,
    this.sessionDurationMins,
    this.methodologyWeights,
    this.preferredHours,
  });

  factory Goal.fromJson(Map<String, dynamic> json) => _$GoalFromJson(json);

  Map<String, dynamic> toJson() => _$GoalToJson(this);
}
