// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'goal.g.dart';

@JsonSerializable(explicitToJson: true)
class Goal {
  @JsonKey(name: 'description', defaultValue: '')
  final String description;
  @JsonKey(name: 'start_date')
  final DateTime startDate;

  Goal({
    required this.description,
    required this.startDate,
  });

  factory Goal.fromJson(Map<String, dynamic> json) => _$GoalFromJson(json);

  Map<String, dynamic> toJson() => _$GoalToJson(this);
}
