// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'goal.g.dart';

@JsonSerializable(explicitToJson: true)
class Goal {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'description')
  final String? description;
  @JsonKey(name: 'aliases')
  final List<String>? aliases;

  Goal({
    required this.id,
    this.description,
    this.aliases,
  });

  factory Goal.fromJson(Map<String, dynamic> json) => _$GoalFromJson(json);

  Map<String, dynamic> toJson() => _$GoalToJson(this);
}
