// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'gym.g.dart';

@JsonSerializable(explicitToJson: true)
class Gym {
  @JsonKey(name: 'id')
  final String id;
  @JsonKey(name: 'name')
  final String name;
  @JsonKey(name: 'equipment', defaultValue: const [])
  final List<String> equipment;

  Gym({
    required this.id,
    required this.name,
    required this.equipment,
  });

  factory Gym.fromJson(Map<String, dynamic> json) => _$GymFromJson(json);

  Map<String, dynamic> toJson() => _$GymToJson(this);
}
