// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'gym.g.dart';

@JsonSerializable(explicitToJson: true)
class Gym {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'equipment', defaultValue: [])
  final List<String> equipment;
  @JsonKey(name: 'modifier_variants')
  final Map<String, dynamic>? modifierVariants;

  Gym({
    required this.id,
    required this.name,
    required this.equipment,
    this.modifierVariants,
  });

  factory Gym.fromJson(Map<String, dynamic> json) => _$GymFromJson(json);

  Map<String, dynamic> toJson() => _$GymToJson(this);
}
