// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_weight.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthWeight {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'weight')
  final double weight;
  @JsonKey(name: 'source', defaultValue: '')
  final String source;
  @JsonKey(name: 'source_app', defaultValue: '')
  final String sourceApp;
  @JsonKey(name: 'measured_at', toJson: _dateTimeToJson)
  final DateTime measuredAt;
  @JsonKey(name: 'hc_record_id')
  final String? hCRecordId;
  @JsonKey(name: 'synced_at', toJson: _dateTimeToJson)
  final DateTime syncedAt;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;
  @JsonKey(name: 'updated_at', toJson: _dateTimeToJson)
  final DateTime updatedAt;

  HealthWeight({
    required this.id,
    required this.userId,
    required this.weight,
    required this.source,
    required this.sourceApp,
    required this.measuredAt,
    this.hCRecordId,
    required this.syncedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory HealthWeight.fromJson(Map<String, dynamic> json) => _$HealthWeightFromJson(json);

  Map<String, dynamic> toJson() => _$HealthWeightToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
