// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'health_sync_metric.dart';
import 'health_sync_session.dart';
import 'health_sync_hr_sample.dart';

part 'health_sync_request.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthSyncRequest {
  @JsonKey(name: 'timezone', defaultValue: '')
  final String timezone;
  @JsonKey(name: 'metrics', defaultValue: [])
  final List<HealthSyncMetric> metrics;
  @JsonKey(name: 'sessions', defaultValue: [])
  final List<HealthSyncSession> sessions;
  @JsonKey(name: 'hr_samples', defaultValue: [])
  final List<HealthSyncHRSample> hRSamples;
  @JsonKey(name: 'deleted_record_ids', defaultValue: [])
  final List<String> deletedRecordIDs;

  HealthSyncRequest({
    required this.timezone,
    required this.metrics,
    required this.sessions,
    required this.hRSamples,
    required this.deletedRecordIDs,
  });

  factory HealthSyncRequest.fromJson(Map<String, dynamic> json) => _$HealthSyncRequestFromJson(json);

  Map<String, dynamic> toJson() => _$HealthSyncRequestToJson(this);
}
