// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_sync_metric.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthSyncMetric {
  @JsonKey(name: 'date', defaultValue: '')
  final String date;
  @JsonKey(name: 'sleep_hours')
  final double sleepHours;
  @JsonKey(name: 'sleep_deep_hours')
  final double sleepDeepHours;
  @JsonKey(name: 'sleep_light_hours')
  final double sleepLightHours;
  @JsonKey(name: 'sleep_rem_hours')
  final double sleepREMHours;
  @JsonKey(name: 'resting_hr')
  final int restingHR;
  @JsonKey(name: 'hrv_rmssd')
  final double hRVRMSSD;
  @JsonKey(name: 'steps')
  final int steps;
  @JsonKey(name: 'total_calories')
  final double totalCalories;

  HealthSyncMetric({
    required this.date,
    required this.sleepHours,
    required this.sleepDeepHours,
    required this.sleepLightHours,
    required this.sleepREMHours,
    required this.restingHR,
    required this.hRVRMSSD,
    required this.steps,
    required this.totalCalories,
  });

  factory HealthSyncMetric.fromJson(Map<String, dynamic> json) => _$HealthSyncMetricFromJson(json);

  Map<String, dynamic> toJson() => _$HealthSyncMetricToJson(this);
}
