// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_sync_hr_sample.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthSyncHRSample {
  @JsonKey(name: 'timestamp')
  final int timestamp;
  @JsonKey(name: 'bpm')
  final int bPM;

  HealthSyncHRSample({
    required this.timestamp,
    required this.bPM,
  });

  factory HealthSyncHRSample.fromJson(Map<String, dynamic> json) => _$HealthSyncHRSampleFromJson(json);

  Map<String, dynamic> toJson() => _$HealthSyncHRSampleToJson(this);
}
