// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_daily_metric.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthDailyMetric {
  @JsonKey(name: 'date', toJson: _dateTimeToJson)
  final DateTime date;
  @JsonKey(name: 'sleep_hours')
  final double sleepHours;
  @JsonKey(name: 'resting_hr')
  final int restingHR;
  @JsonKey(name: 'hrv_rmssd')
  final double hRVRMSSD;

  HealthDailyMetric({
    required this.date,
    required this.sleepHours,
    required this.restingHR,
    required this.hRVRMSSD,
  });

  factory HealthDailyMetric.fromJson(Map<String, dynamic> json) => _$HealthDailyMetricFromJson(json);

  Map<String, dynamic> toJson() => _$HealthDailyMetricToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
