// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'health_metric.dart';
import 'health_exercise_session.dart';

part 'health_daily_response.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthDailyResponse {
  @JsonKey(name: 'metrics', defaultValue: [])
  final List<HealthMetric> metrics;
  @JsonKey(name: 'sessions', defaultValue: [])
  final List<HealthExerciseSession> sessions;

  HealthDailyResponse({
    required this.metrics,
    required this.sessions,
  });

  factory HealthDailyResponse.fromJson(Map<String, dynamic> json) => _$HealthDailyResponseFromJson(json);

  Map<String, dynamic> toJson() => _$HealthDailyResponseToJson(this);
}
