// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_exercise_session.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthExerciseSession {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'training_id')
  final String? trainingId;
  @JsonKey(name: 'source_app', defaultValue: '')
  final String sourceApp;
  @JsonKey(name: 'exercise_type', defaultValue: '')
  final String exerciseType;
  @JsonKey(name: 'started_at', toJson: _dateTimeToJson)
  final DateTime startedAt;
  @JsonKey(name: 'ended_at', toJson: _dateTimeToJson)
  final DateTime endedAt;
  @JsonKey(name: 'avg_hr')
  final int? avgHR;
  @JsonKey(name: 'max_hr')
  final int? maxHR;
  @JsonKey(name: 'calories')
  final double? calories;
  @JsonKey(name: 'hr_zone_distribution_json', defaultValue: {})
  final Map<String, dynamic> hRZoneDistributionJSON;
  @JsonKey(name: 'hr_samples_json', defaultValue: {})
  final Map<String, dynamic> hRSamplesJSON;
  @JsonKey(name: 'hc_record_id', defaultValue: '')
  final String hCRecordId;
  @JsonKey(name: 'synced_at', toJson: _dateTimeToJson)
  final DateTime syncedAt;

  HealthExerciseSession({
    required this.id,
    required this.userId,
    this.trainingId,
    required this.sourceApp,
    required this.exerciseType,
    required this.startedAt,
    required this.endedAt,
    this.avgHR,
    this.maxHR,
    this.calories,
    required this.hRZoneDistributionJSON,
    required this.hRSamplesJSON,
    required this.hCRecordId,
    required this.syncedAt,
  });

  factory HealthExerciseSession.fromJson(Map<String, dynamic> json) => _$HealthExerciseSessionFromJson(json);

  Map<String, dynamic> toJson() => _$HealthExerciseSessionToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
