// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_sync_session.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthSyncSession {
  @JsonKey(name: 'hc_record_id', defaultValue: '')
  final String hCRecordId;
  @JsonKey(name: 'source_app', defaultValue: '')
  final String sourceApp;
  @JsonKey(name: 'exercise_type', defaultValue: '')
  final String exerciseType;
  @JsonKey(name: 'started_at')
  final int startedAt;
  @JsonKey(name: 'ended_at')
  final int endedAt;
  @JsonKey(name: 'calories')
  final double? calories;

  HealthSyncSession({
    required this.hCRecordId,
    required this.sourceApp,
    required this.exerciseType,
    required this.startedAt,
    required this.endedAt,
    this.calories,
  });

  factory HealthSyncSession.fromJson(Map<String, dynamic> json) => _$HealthSyncSessionFromJson(json);

  Map<String, dynamic> toJson() => _$HealthSyncSessionToJson(this);
}
