// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'health_sync_weight.g.dart';

@JsonSerializable(explicitToJson: true)
class HealthSyncWeight {
  @JsonKey(name: 'hc_record_id', defaultValue: '')
  final String hCRecordId;
  @JsonKey(name: 'source_app', defaultValue: '')
  final String sourceApp;
  @JsonKey(name: 'measured_at')
  final int measuredAt;
  @JsonKey(name: 'weight')
  final double weight;

  HealthSyncWeight({
    required this.hCRecordId,
    required this.sourceApp,
    required this.measuredAt,
    required this.weight,
  });

  factory HealthSyncWeight.fromJson(Map<String, dynamic> json) => _$HealthSyncWeightFromJson(json);

  Map<String, dynamic> toJson() => _$HealthSyncWeightToJson(this);
}
