// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'injury.g.dart';

@JsonSerializable(explicitToJson: true)
class Injury {
  @JsonKey(name: 'description')
  final String description;
  @JsonKey(name: 'year')
  final int year;

  Injury({
    required this.description,
    required this.year,
  });

  factory Injury.fromJson(Map<String, dynamic> json) => _$InjuryFromJson(json);

  Map<String, dynamic> toJson() => _$InjuryToJson(this);
}
