// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'json_schema.dart';

part 'json_schema_format.g.dart';

@JsonSerializable(explicitToJson: true)
class JSONSchemaFormat {
  @JsonKey(name: 'type')
  final String type;
  @JsonKey(name: 'json_schema')
  final JSONSchema jSONSchema;

  JSONSchemaFormat({
    required this.type,
    required this.jSONSchema,
  });

  factory JSONSchemaFormat.fromJson(Map<String, dynamic> json) => _$JSONSchemaFormatFromJson(json);

  Map<String, dynamic> toJson() => _$JSONSchemaFormatToJson(this);
}
