// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'llm_prompt.dart';

part 'llm_step.g.dart';

@JsonSerializable(explicitToJson: true)
class LLMStep {
  @JsonKey(name: 'model', defaultValue: '')
  final String model;
  @JsonKey(name: 'prompt')
  final LLMPrompt prompt;
  @JsonKey(name: 'output')
  final String? output;

  LLMStep({
    required this.model,
    required this.prompt,
    this.output,
  });

  factory LLMStep.fromJson(Map<String, dynamic> json) => _$LLMStepFromJson(json);

  Map<String, dynamic> toJson() => _$LLMStepToJson(this);
}
