// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'llm_prompt.g.dart';

@JsonSerializable(explicitToJson: true)
class LLMPrompt {
  @JsonKey(name: 'system', defaultValue: '')
  final String system;
  @JsonKey(name: 'user', defaultValue: '')
  final String user;

  LLMPrompt({
    required this.system,
    required this.user,
  });

  factory LLMPrompt.fromJson(Map<String, dynamic> json) => _$LLMPromptFromJson(json);

  Map<String, dynamic> toJson() => _$LLMPromptToJson(this);
}
