// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'methodology_work.g.dart';

@JsonSerializable(explicitToJson: true)
class MethodologyWork {
  @JsonKey(name: 'min_difficulty')
  final int minDifficulty;
  @JsonKey(name: 'max_difficulty')
  final int? maxDifficulty;
  @JsonKey(name: 'mobility_only')
  final bool? mobilityOnly;

  MethodologyWork({
    required this.minDifficulty,
    this.maxDifficulty,
    this.mobilityOnly,
  });

  factory MethodologyWork.fromJson(Map<String, dynamic> json) => _$MethodologyWorkFromJson(json);

  Map<String, dynamic> toJson() => _$MethodologyWorkToJson(this);
}
