// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'methodology_work.g.dart';

@JsonSerializable(explicitToJson: true)
class MethodologyWork {
  @JsonKey(name: 'min')
  final int min;
  @JsonKey(name: 'max')
  final int? max;

  MethodologyWork({
    required this.min,
    this.max,
  });

  factory MethodologyWork.fromJson(Map<String, dynamic> json) => _$MethodologyWorkFromJson(json);

  Map<String, dynamic> toJson() => _$MethodologyWorkToJson(this);
}
