// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'methodology.g.dart';

@JsonSerializable(explicitToJson: true)
class Methodology {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'description', defaultValue: '')
  final String description;

  Methodology({
    required this.id,
    required this.name,
    required this.description,
  });

  factory Methodology.fromJson(Map<String, dynamic> json) => _$MethodologyFromJson(json);

  Map<String, dynamic> toJson() => _$MethodologyToJson(this);
}
