// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'model_step.g.dart';

@JsonSerializable(explicitToJson: true)
class ModelStep {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'trajectory_id')
  final String? trajectoryId;
  @JsonKey(name: 'step', defaultValue: '')
  final String step;
  @JsonKey(name: 'position')
  final int position;
  @JsonKey(name: 'kind', defaultValue: '')
  final String kind;
  @JsonKey(name: 'llm')
  final Map<String, dynamic>? lLM;
  @JsonKey(name: 'dm')
  final Map<String, dynamic>? dM;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;

  ModelStep({
    required this.id,
    this.trajectoryId,
    required this.step,
    required this.position,
    required this.kind,
    this.lLM,
    this.dM,
    required this.createdAt,
  });

  factory ModelStep.fromJson(Map<String, dynamic> json) => _$ModelStepFromJson(json);

  Map<String, dynamic> toJson() => _$ModelStepToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
