// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'modifier.g.dart';

@JsonSerializable(explicitToJson: true)
class Modifier {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'patterns', defaultValue: const [])
  final List<String> patterns;
  @JsonKey(name: 'aliases')
  final List<String>? aliases;

  Modifier({
    required this.id,
    required this.patterns,
    this.aliases,
  });

  factory Modifier.fromJson(Map<String, dynamic> json) => _$ModifierFromJson(json);

  Map<String, dynamic> toJson() => _$ModifierToJson(this);
}
