// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'muscle_progress.g.dart';

@JsonSerializable(explicitToJson: true)
class MuscleProgress {
  @JsonKey(name: 'proficiency')
  final double proficiency;
  @JsonKey(name: 'calibration')
  final double calibration;

  MuscleProgress({
    required this.proficiency,
    required this.calibration,
  });

  factory MuscleProgress.fromJson(Map<String, dynamic> json) => _$MuscleProgressFromJson(json);

  Map<String, dynamic> toJson() => _$MuscleProgressToJson(this);
}
