// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'muscle_impact.g.dart';

@JsonSerializable(explicitToJson: true)
class MuscleImpact {
  @JsonKey(name: 'heat')
  final double heat;

  MuscleImpact({
    required this.heat,
  });

  factory MuscleImpact.fromJson(Map<String, dynamic> json) => _$MuscleImpactFromJson(json);

  Map<String, dynamic> toJson() => _$MuscleImpactToJson(this);
}
