// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'partner.g.dart';

@JsonSerializable(explicitToJson: true)
class Partner {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'training_id', defaultValue: '')
  final String trainingId;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;

  Partner({
    required this.id,
    required this.trainingId,
    required this.userId,
    required this.createdAt,
  });

  factory Partner.fromJson(Map<String, dynamic> json) => _$PartnerFromJson(json);

  Map<String, dynamic> toJson() => _$PartnerToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
