// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'pending_feedback_training.g.dart';

@JsonSerializable(explicitToJson: true)
class PendingFeedbackTraining {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'completedAt', toJson: _dateTimeToJson)
  final DateTime completedAt;

  PendingFeedbackTraining({
    required this.id,
    required this.name,
    required this.completedAt,
  });

  factory PendingFeedbackTraining.fromJson(Map<String, dynamic> json) => _$PendingFeedbackTrainingFromJson(json);

  Map<String, dynamic> toJson() => _$PendingFeedbackTrainingToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
