// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'preferences.g.dart';

@JsonSerializable(explicitToJson: true)
class Preferences {
  @JsonKey(name: 'exercises')
  final List<String>? exercises;
  @JsonKey(name: 'equipment')
  final List<String>? equipment;

  Preferences({
    this.exercises,
    this.equipment,
  });

  factory Preferences.fromJson(Map<String, dynamic> json) => _$PreferencesFromJson(json);

  Map<String, dynamic> toJson() => _$PreferencesToJson(this);
}
