// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'goal.dart';
import 'injury.dart';
import 'preferences.dart';

part 'profile_data.g.dart';

@JsonSerializable(explicitToJson: true)
class profileData {
  // Fields marked as required in the backend model
  static const List<String> requiredFields = [
    'goals'
  ];
  @JsonKey(name: 'goals', defaultValue: const [])
  final List<Goal> goals;
  @JsonKey(name: 'injuries', defaultValue: const [])
  final List<Injury> injuries;
  @JsonKey(name: 'limitations', defaultValue: const [])
  final List<String> limitations;
  @JsonKey(name: 'preferences')
  final Preferences? preferences;

  profileData({
    required this.goals,
    required this.injuries,
    required this.limitations,
    this.preferences,
  });

  factory profileData.fromJson(Map<String, dynamic> json) => _$profileDataFromJson(json);

  Map<String, dynamic> toJson() => _$profileDataToJson(this);
}
