// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'profile.g.dart';

@JsonSerializable(explicitToJson: true)
class Profile {
  // Fields marked as required in the backend model
  static const List<String> requiredFields = [
    'birthdate',
    'language',
    'height',
    'weight'
  ];
  @JsonKey(name: 'birthdate')
  final DateTime birthdate;
  @JsonKey(name: 'language')
  final String language;
  @JsonKey(name: 'height')
  final double height;
  @JsonKey(name: 'weight')
  final double weight;
  @JsonKey(name: 'data')
  final Map<String, dynamic> data;
  @JsonKey(name: 'user_id')
  final String userId;

  Profile({
    required this.birthdate,
    required this.language,
    required this.height,
    required this.weight,
    required this.data,
    required this.userId,
  });

  factory Profile.fromJson(Map<String, dynamic> json) => _$ProfileFromJson(json);

  Map<String, dynamic> toJson() => _$ProfileToJson(this);
}
