// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'profile.g.dart';

@JsonSerializable(explicitToJson: true)
class Profile {
  // Fields marked as required in the backend model
  static const List<String> requiredFields = [
    'first_name',
    'last_name',
    'birthdate',
    'gender',
    'language',
    'height',
    'weight'
  ];
  @JsonKey(name: 'first_name')
  final String firstName;
  @JsonKey(name: 'last_name')
  final String lastName;
  @JsonKey(name: 'birthdate', toJson: _dateTimeToJson)
  final DateTime birthdate;
  @JsonKey(name: 'gender')
  final String gender;
  @JsonKey(name: 'language')
  final String language;
  @JsonKey(name: 'height')
  final double height;
  @JsonKey(name: 'weight')
  final double weight;
  @JsonKey(name: 'health_disconnected')
  final bool healthDisconnected;
  @JsonKey(name: 'data', defaultValue: {})
  final Map<String, dynamic> data;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;

  Profile({
    required this.firstName,
    required this.lastName,
    required this.birthdate,
    required this.gender,
    required this.language,
    required this.height,
    required this.weight,
    required this.healthDisconnected,
    required this.data,
    required this.userId,
  });

  factory Profile.fromJson(Map<String, dynamic> json) => _$ProfileFromJson(json);

  Map<String, dynamic> toJson() => _$ProfileToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
