// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'proficiency.g.dart';

@JsonSerializable(explicitToJson: true)
class Proficiency {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'training_id', defaultValue: '')
  final String trainingId;
  @JsonKey(name: 'movement_family', defaultValue: '')
  final String movementFamily;
  @JsonKey(name: 'value')
  final double value;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;

  Proficiency({
    required this.id,
    required this.userId,
    required this.trainingId,
    required this.movementFamily,
    required this.value,
    required this.createdAt,
  });

  factory Proficiency.fromJson(Map<String, dynamic> json) => _$ProficiencyFromJson(json);

  Map<String, dynamic> toJson() => _$ProficiencyToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
