// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'injury.dart';
import 'preferences.dart';

part 'profile_data.g.dart';

@JsonSerializable(explicitToJson: true)
class ProfileData {
  // Fields marked as required in the backend model
  static const List<String> requiredFields = [
    'goals'
  ];
  @JsonKey(name: 'goals', defaultValue: [])
  final List<String> goals;
  @JsonKey(name: 'injuries', defaultValue: [])
  final List<Injury> injuries;
  @JsonKey(name: 'limitations', defaultValue: [])
  final List<String> limitations;
  @JsonKey(name: 'conditions', defaultValue: [])
  final List<String> conditions;
  @JsonKey(name: 'preferences')
  final Preferences? preferences;

  ProfileData({
    required this.goals,
    required this.injuries,
    required this.limitations,
    required this.conditions,
    this.preferences,
  });

  factory ProfileData.fromJson(Map<String, dynamic> json) => _$ProfileDataFromJson(json);

  Map<String, dynamic> toJson() => _$ProfileDataToJson(this);
}
