// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'progression_adjustment.g.dart';

@JsonSerializable(explicitToJson: true)
class ProgressionAdjustment {
  @JsonKey(name: 'exercise', defaultValue: '')
  final String exercise;
  @JsonKey(name: 'adjustment', defaultValue: '')
  final String adjustment;
  @JsonKey(name: 'reason', defaultValue: '')
  final String reason;

  ProgressionAdjustment({
    required this.exercise,
    required this.adjustment,
    required this.reason,
  });

  factory ProgressionAdjustment.fromJson(Map<String, dynamic> json) => _$ProgressionAdjustmentFromJson(json);

  Map<String, dynamic> toJson() => _$ProgressionAdjustmentToJson(this);
}
