// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'progression_adjustment.dart';

part 'progression_reasoning.g.dart';

@JsonSerializable(explicitToJson: true)
class ProgressionReasoning {
  @JsonKey(name: 'summary', defaultValue: '')
  final String summary;
  @JsonKey(name: 'adjustments', defaultValue: [])
  final List<ProgressionAdjustment> adjustments;

  ProgressionReasoning({
    required this.summary,
    required this.adjustments,
  });

  factory ProgressionReasoning.fromJson(Map<String, dynamic> json) => _$ProgressionReasoningFromJson(json);

  Map<String, dynamic> toJson() => _$ProgressionReasoningToJson(this);
}
