// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'progress.g.dart';

@JsonSerializable(explicitToJson: true)
class Progress {
  @JsonKey(name: 'families')
  final Map<String, dynamic> families;
  @JsonKey(name: 'muscles')
  final Map<String, dynamic> muscles;
  @JsonKey(name: 'trainings')
  final int trainings;
  @JsonKey(name: 'trainings_partnered')
  final int trainingsPartnered;

  Progress({
    required this.families,
    required this.muscles,
    required this.trainings,
    required this.trainingsPartnered,
  });

  factory Progress.fromJson(Map<String, dynamic> json) => _$ProgressFromJson(json);

  Map<String, dynamic> toJson() => _$ProgressToJson(this);
}
