// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'pending_feedback_training.dart';

part 'progress.g.dart';

@JsonSerializable(explicitToJson: true)
class Progress {
  @JsonKey(name: 'families', defaultValue: {})
  final Map<String, dynamic> families;
  @JsonKey(name: 'muscles', defaultValue: {})
  final Map<String, dynamic> muscles;
  @JsonKey(name: 'trainings')
  final int trainings;
  @JsonKey(name: 'trainings_partnered')
  final int trainingsPartnered;
  @JsonKey(name: 'pendingFeedback', defaultValue: [])
  final List<PendingFeedbackTraining> pendingFeedback;

  Progress({
    required this.families,
    required this.muscles,
    required this.trainings,
    required this.trainingsPartnered,
    required this.pendingFeedback,
  });

  factory Progress.fromJson(Map<String, dynamic> json) => _$ProgressFromJson(json);

  Map<String, dynamic> toJson() => _$ProgressToJson(this);
}
