// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'readiness_response.g.dart';

@JsonSerializable(explicitToJson: true)
class ReadinessResponse {
  @JsonKey(name: 'score')
  final int score;
  @JsonKey(name: 'level', defaultValue: '')
  final String level;
  @JsonKey(name: 'summary', defaultValue: '')
  final String summary;

  ReadinessResponse({
    required this.score,
    required this.level,
    required this.summary,
  });

  factory ReadinessResponse.fromJson(Map<String, dynamic> json) => _$ReadinessResponseFromJson(json);

  Map<String, dynamic> toJson() => _$ReadinessResponseToJson(this);
}
