// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'readiness_sleep_metric.g.dart';

@JsonSerializable(explicitToJson: true)
class ReadinessSleepMetric {
  @JsonKey(name: 'hours')
  final double hours;
  @JsonKey(name: 'baseline_hours')
  final double? baselineHours;
  @JsonKey(name: 'deviation_pct')
  final double? deviationPct;
  @JsonKey(name: 'status')
  final String? status;

  ReadinessSleepMetric({
    required this.hours,
    this.baselineHours,
    this.deviationPct,
    this.status,
  });

  factory ReadinessSleepMetric.fromJson(Map<String, dynamic> json) => _$ReadinessSleepMetricFromJson(json);

  Map<String, dynamic> toJson() => _$ReadinessSleepMetricToJson(this);
}
