// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'readiness_load_metric.g.dart';

@JsonSerializable(explicitToJson: true)
class ReadinessLoadMetric {
  @JsonKey(name: 'vigor_sessions')
  final int vigorSessions;
  @JsonKey(name: 'external_workouts')
  final int externalWorkouts;
  @JsonKey(name: 'external_minutes')
  final int? externalMinutes;

  ReadinessLoadMetric({
    required this.vigorSessions,
    required this.externalWorkouts,
    this.externalMinutes,
  });

  factory ReadinessLoadMetric.fromJson(Map<String, dynamic> json) => _$ReadinessLoadMetricFromJson(json);

  Map<String, dynamic> toJson() => _$ReadinessLoadMetricToJson(this);
}
