// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'readiness_sleep_metric.dart';
import 'readiness_hrv_metric.dart';
import 'readiness_rhr_metric.dart';
import 'readiness_load_metric.dart';

part 'readiness_metrics.g.dart';

@JsonSerializable(explicitToJson: true)
class ReadinessMetrics {
  @JsonKey(name: 'sleep')
  final ReadinessSleepMetric? sleep;
  @JsonKey(name: 'hrv')
  final ReadinessHRVMetric? hRV;
  @JsonKey(name: 'resting_hr')
  final ReadinessRHRMetric? restingHR;
  @JsonKey(name: 'load')
  final ReadinessLoadMetric? load;

  ReadinessMetrics({
    this.sleep,
    this.hRV,
    this.restingHR,
    this.load,
  });

  factory ReadinessMetrics.fromJson(Map<String, dynamic> json) => _$ReadinessMetricsFromJson(json);

  Map<String, dynamic> toJson() => _$ReadinessMetricsToJson(this);
}
