// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'readiness_rhr_metric.g.dart';

@JsonSerializable(explicitToJson: true)
class ReadinessRHRMetric {
  @JsonKey(name: 'today_bpm')
  final int todayBpm;
  @JsonKey(name: 'baseline_bpm')
  final double? baselineBpm;
  @JsonKey(name: 'deviation_bpm')
  final double? deviationBpm;
  @JsonKey(name: 'status')
  final String? status;

  ReadinessRHRMetric({
    required this.todayBpm,
    this.baselineBpm,
    this.deviationBpm,
    this.status,
  });

  factory ReadinessRHRMetric.fromJson(Map<String, dynamic> json) => _$ReadinessRHRMetricFromJson(json);

  Map<String, dynamic> toJson() => _$ReadinessRHRMetricToJson(this);
}
