// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'refresh_token.g.dart';

@JsonSerializable(explicitToJson: true)
class RefreshToken {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'token', defaultValue: '')
  final String token;
  @JsonKey(name: 'expires_at', toJson: _dateTimeToJson)
  final DateTime expiresAt;
  @JsonKey(name: 'revoked')
  final bool revoked;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;

  RefreshToken({
    required this.id,
    required this.userId,
    required this.token,
    required this.expiresAt,
    required this.revoked,
    required this.createdAt,
  });

  factory RefreshToken.fromJson(Map<String, dynamic> json) => _$RefreshTokenFromJson(json);

  Map<String, dynamic> toJson() => _$RefreshTokenToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
