// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'report.g.dart';

@JsonSerializable(explicitToJson: true)
class Report {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'content', defaultValue: '')
  final String content;
  @JsonKey(name: 'training_id')
  final String? trainingId;
  @JsonKey(name: 'activity_id')
  final String? activityId;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  Report({
    required this.id,
    required this.content,
    this.trainingId,
    this.activityId,
    required this.userId,
    required this.createdAt,
  });

  factory Report.fromJson(Map<String, dynamic> json) => _$ReportFromJson(json);

  Map<String, dynamic> toJson() => _$ReportToJson(this);
}
