// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'block.dart';

part 'routine.g.dart';

@JsonSerializable(explicitToJson: true)
class Routine {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'training_id', defaultValue: '')
  final String trainingId;
  @JsonKey(name: 'name', defaultValue: '')
  final String type;
  @JsonKey(name: 'rest')
  final int rest;
  @JsonKey(name: 'blocks', defaultValue: const [])
  final List<Block> blocks;

  Routine({
    required this.id,
    required this.trainingId,
    required this.type,
    required this.rest,
    required this.blocks,
  });

  factory Routine.fromJson(Map<String, dynamic> json) => _$RoutineFromJson(json);

  Map<String, dynamic> toJson() => _$RoutineToJson(this);
}
