// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'shared_link.g.dart';

@JsonSerializable(explicitToJson: true)
class SharedLink {
  @JsonKey(name: 'token', defaultValue: '')
  final String token;
  @JsonKey(name: 'training_id', defaultValue: '')
  final String trainingId;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;

  SharedLink({
    required this.token,
    required this.trainingId,
    required this.createdAt,
  });

  factory SharedLink.fromJson(Map<String, dynamic> json) => _$SharedLinkFromJson(json);

  Map<String, dynamic> toJson() => _$SharedLinkToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
