// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'synthesized_recommendation.g.dart';

@JsonSerializable(explicitToJson: true)
class SynthesizedRecommendation {
  @JsonKey(name: 'sessions_per_week', defaultValue: [])
  final List<int> sessionsPerWeek;
  @JsonKey(name: 'session_duration_mins', defaultValue: [])
  final List<int> sessionDurationMins;
  @JsonKey(name: 'methodology_mix', defaultValue: {})
  final Map<String, dynamic> methodologyMix;
  @JsonKey(name: 'preferred_hours', defaultValue: [])
  final List<int> preferredHours;

  SynthesizedRecommendation({
    required this.sessionsPerWeek,
    required this.sessionDurationMins,
    required this.methodologyMix,
    required this.preferredHours,
  });

  factory SynthesizedRecommendation.fromJson(Map<String, dynamic> json) => _$SynthesizedRecommendationFromJson(json);

  Map<String, dynamic> toJson() => _$SynthesizedRecommendationToJson(this);
}
