// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'routine.dart';

part 'training.g.dart';

@JsonSerializable(explicitToJson: true)
class Training {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'description', defaultValue: '')
  final String description;
  @JsonKey(name: 'type', defaultValue: '')
  final String type;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'routines', defaultValue: const [])
  final List<Routine> routines;
  @JsonKey(name: 'prompt')
  final Map<String, dynamic> prompt;
  @JsonKey(name: 'completed_at')
  final DateTime? completedAt;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  Training({
    required this.id,
    required this.name,
    required this.description,
    required this.type,
    required this.duration,
    required this.routines,
    required this.prompt,
    this.completedAt,
    required this.createdAt,
  });

  factory Training.fromJson(Map<String, dynamic> json) => _$TrainingFromJson(json);

  Map<String, dynamic> toJson() => _$TrainingToJson(this);
}
