// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'llm_prompt.dart';

part 'training_prompt.g.dart';

@JsonSerializable(explicitToJson: true)
class TrainingPrompt {
  @JsonKey(name: 'query')
  final LLMPrompt query;
  @JsonKey(name: 'model', defaultValue: '')
  final String model;

  TrainingPrompt({
    required this.query,
    required this.model,
  });

  factory TrainingPrompt.fromJson(Map<String, dynamic> json) => _$TrainingPromptFromJson(json);

  Map<String, dynamic> toJson() => _$TrainingPromptToJson(this);
}
