// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'progression_reasoning.dart';

part 'training_reasoning.g.dart';

@JsonSerializable(explicitToJson: true)
class TrainingReasoning {
  @JsonKey(name: 'constraints', defaultValue: const [])
  final List<String> constraints;
  @JsonKey(name: 'type_selection', defaultValue: '')
  final String typeSelection;
  @JsonKey(name: 'strategy', defaultValue: '')
  final String strategy;
  @JsonKey(name: 'progression')
  final ProgressionReasoning progression;
  @JsonKey(name: 'facts_applied', defaultValue: const [])
  final List<String> factsApplied;
  @JsonKey(name: 'target_muscles', defaultValue: const [])
  final List<String> targetMuscles;
  @JsonKey(name: 'exercises', defaultValue: const [])
  final List<String> exercises;

  TrainingReasoning({
    required this.constraints,
    required this.typeSelection,
    required this.strategy,
    required this.progression,
    required this.factsApplied,
    required this.targetMuscles,
    required this.exercises,
  });

  factory TrainingReasoning.fromJson(Map<String, dynamic> json) => _$TrainingReasoningFromJson(json);

  Map<String, dynamic> toJson() => _$TrainingReasoningToJson(this);
}
