// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'training_reference.g.dart';

@JsonSerializable(explicitToJson: true)
class TrainingReference {
  @JsonKey(name: 'excerpt', defaultValue: '')
  final String excerpt;
  @JsonKey(name: 'url', defaultValue: '')
  final String url;

  TrainingReference({
    required this.excerpt,
    required this.url,
  });

  factory TrainingReference.fromJson(Map<String, dynamic> json) => _$TrainingReferenceFromJson(json);

  Map<String, dynamic> toJson() => _$TrainingReferenceToJson(this);
}
