// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'training_reasoning.dart';
import 'routine.dart';
import 'gym.dart';

part 'training.g.dart';

@JsonSerializable(explicitToJson: true)
class Training {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'reasoning')
  final TrainingReasoning reasoning;
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'description', defaultValue: '')
  final String description;
  @JsonKey(name: 'methodology', defaultValue: '')
  final String methodology;
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'equipment', defaultValue: [])
  final List<String> equipment;
  @JsonKey(name: 'goals', defaultValue: [])
  final List<String> goals;
  @JsonKey(name: 'muscles', defaultValue: [])
  final List<String> muscles;
  @JsonKey(name: 'request', defaultValue: '')
  final String request;
  @JsonKey(name: 'references', defaultValue: [])
  final List<String> references;
  @JsonKey(name: 'routines', defaultValue: [])
  final List<Routine> routines;
  @JsonKey(name: 'prompt')
  final Map<String, dynamic> prompt;
  @JsonKey(name: 'feedback', defaultValue: '')
  final String feedback;
  @JsonKey(name: 'completed_at', toJson: _nullableDateTimeToJson)
  final DateTime? completedAt;
  @JsonKey(name: 'created_at', toJson: _dateTimeToJson)
  final DateTime createdAt;
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'parent_id')
  final String? parentId;
  @JsonKey(name: 'gym_id')
  final String? gymId;
  @JsonKey(name: 'gym')
  final Gym? gym;

  Training({
    required this.id,
    required this.reasoning,
    required this.name,
    required this.description,
    required this.methodology,
    required this.duration,
    required this.equipment,
    required this.goals,
    required this.muscles,
    required this.request,
    required this.references,
    required this.routines,
    required this.prompt,
    required this.feedback,
    this.completedAt,
    required this.createdAt,
    required this.userId,
    this.parentId,
    this.gymId,
    this.gym,
  });

  factory Training.fromJson(Map<String, dynamic> json) => _$TrainingFromJson(json);

  Map<String, dynamic> toJson() => _$TrainingToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();

  static String? _nullableDateTimeToJson(DateTime? dt) => dt?.toUtc().toIso8601String();
}
