// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'validation_error.g.dart';

@JsonSerializable(explicitToJson: true)
class ValidationError {
  @JsonKey(name: 'code', defaultValue: '')
  final String code;
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  ValidationError({
    required this.code,
    required this.message,
  });

  factory ValidationError.fromJson(Map<String, dynamic> json) => _$ValidationErrorFromJson(json);

  Map<String, dynamic> toJson() => _$ValidationErrorToJson(this);
}
