// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'week_summary.g.dart';

@JsonSerializable(explicitToJson: true)
class WeekSummary {
  @JsonKey(name: 'week_start', toJson: _dateTimeToJson)
  final DateTime weekStart;
  @JsonKey(name: 'sessions_completed')
  final int sessionsCompleted;
  @JsonKey(name: 'on_target')
  final bool onTarget;

  WeekSummary({
    required this.weekStart,
    required this.sessionsCompleted,
    required this.onTarget,
  });

  factory WeekSummary.fromJson(Map<String, dynamic> json) => _$WeekSummaryFromJson(json);

  Map<String, dynamic> toJson() => _$WeekSummaryToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
