// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'week_progress.g.dart';

@JsonSerializable(explicitToJson: true)
class WeekProgress {
  @JsonKey(name: 'week_start', toJson: _dateTimeToJson)
  final DateTime weekStart;
  @JsonKey(name: 'sessions_completed')
  final int sessionsCompleted;
  @JsonKey(name: 'days_remaining')
  final int daysRemaining;
  @JsonKey(name: 'methodologies_used', defaultValue: [])
  final List<String> methodologiesUsed;
  @JsonKey(name: 'avg_duration_mins')
  final int avgDurationMins;
  @JsonKey(name: 'completed_days', defaultValue: [])
  final List<int> completedDays;

  WeekProgress({
    required this.weekStart,
    required this.sessionsCompleted,
    required this.daysRemaining,
    required this.methodologiesUsed,
    required this.avgDurationMins,
    required this.completedDays,
  });

  factory WeekProgress.fromJson(Map<String, dynamic> json) => _$WeekProgressFromJson(json);

  Map<String, dynamic> toJson() => _$WeekProgressToJson(this);

  static String _dateTimeToJson(DateTime dt) => dt.toUtc().toIso8601String();
}
