// Code generated by qtc from "gen_exercise.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/embedding/template/gen_exercise.qtpl:1
package template

//line llm/embedding/template/gen_exercise.qtpl:3
import "strings"

//line llm/embedding/template/gen_exercise.qtpl:4
import "github.com/streambinder/vigor/knowledge/model"

//line llm/embedding/template/gen_exercise.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/embedding/template/gen_exercise.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/embedding/template/gen_exercise.qtpl:6
func StreamGenExercise(qw422016 *qt422016.Writer, exercise model.Exercise) {
//line llm/embedding/template/gen_exercise.qtpl:7
	qw422016.N().S(` Name: `)
//line llm/embedding/template/gen_exercise.qtpl:9
	qw422016.E().S(exercise.Name)
//line llm/embedding/template/gen_exercise.qtpl:9
	qw422016.N().S(`. Equipment: `)
//line llm/embedding/template/gen_exercise.qtpl:10
	qw422016.E().S(strings.Join(exercise.Equipment, ", "))
//line llm/embedding/template/gen_exercise.qtpl:10
	qw422016.N().S(`. Muscles: `)
//line llm/embedding/template/gen_exercise.qtpl:11
	qw422016.E().S(strings.Join(exercise.Muscles, ", "))
//line llm/embedding/template/gen_exercise.qtpl:11
	qw422016.N().S(` (secondary: `)
//line llm/embedding/template/gen_exercise.qtpl:11
	qw422016.E().S(strings.Join(exercise.SecondaryMuscles, ", "))
//line llm/embedding/template/gen_exercise.qtpl:11
	qw422016.N().S(`). Body parts: `)
//line llm/embedding/template/gen_exercise.qtpl:12
	qw422016.E().S(strings.Join(exercise.BodyParts, ", "))
//line llm/embedding/template/gen_exercise.qtpl:12
	qw422016.N().S(`. Instructions: `)
//line llm/embedding/template/gen_exercise.qtpl:13
	qw422016.E().S(strings.Join(exercise.Instructions, ", "))
//line llm/embedding/template/gen_exercise.qtpl:13
	qw422016.N().S(`. `)
//line llm/embedding/template/gen_exercise.qtpl:16
}

//line llm/embedding/template/gen_exercise.qtpl:16
func WriteGenExercise(qq422016 qtio422016.Writer, exercise model.Exercise) {
//line llm/embedding/template/gen_exercise.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/embedding/template/gen_exercise.qtpl:16
	StreamGenExercise(qw422016, exercise)
//line llm/embedding/template/gen_exercise.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line llm/embedding/template/gen_exercise.qtpl:16
}

//line llm/embedding/template/gen_exercise.qtpl:16
func GenExercise(exercise model.Exercise) string {
//line llm/embedding/template/gen_exercise.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/embedding/template/gen_exercise.qtpl:16
	WriteGenExercise(qb422016, exercise)
//line llm/embedding/template/gen_exercise.qtpl:16
	qs422016 := string(qb422016.B)
//line llm/embedding/template/gen_exercise.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/embedding/template/gen_exercise.qtpl:16
	return qs422016
//line llm/embedding/template/gen_exercise.qtpl:16
}
