// Code generated by qtc from "gen_user_exercises.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/embedding/template/gen_user_exercises.qtpl:1
package template

//line llm/embedding/template/gen_user_exercises.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/embedding/template/gen_user_exercises.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/embedding/template/gen_user_exercises.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/embedding/template/gen_user_exercises.qtpl:5
func StreamGenUserExercises(qw422016 *qt422016.Writer, profile model.Profile, equipment []string) {
//line llm/embedding/template/gen_user_exercises.qtpl:6
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:8
	if len(profile.Goals()) > 0 {
//line llm/embedding/template/gen_user_exercises.qtpl:8
		qw422016.N().S(` Fitness goals: `)
//line llm/embedding/template/gen_user_exercises.qtpl:10
		for i, goal := range profile.Goals() {
//line llm/embedding/template/gen_user_exercises.qtpl:10
			qw422016.E().S(goal.Description)
//line llm/embedding/template/gen_user_exercises.qtpl:10
			if i < len(profile.Goals())-1 {
//line llm/embedding/template/gen_user_exercises.qtpl:10
				qw422016.N().S(`, `)
//line llm/embedding/template/gen_user_exercises.qtpl:10
			}
//line llm/embedding/template/gen_user_exercises.qtpl:10
		}
//line llm/embedding/template/gen_user_exercises.qtpl:10
		qw422016.N().S(`. `)
//line llm/embedding/template/gen_user_exercises.qtpl:11
	}
//line llm/embedding/template/gen_user_exercises.qtpl:11
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:12
	if len(profile.Injuries()) > 0 {
//line llm/embedding/template/gen_user_exercises.qtpl:12
		qw422016.N().S(` Avoid exercises that impact: `)
//line llm/embedding/template/gen_user_exercises.qtpl:14
		for i, injury := range profile.Injuries() {
//line llm/embedding/template/gen_user_exercises.qtpl:14
			qw422016.E().S(injury.Description)
//line llm/embedding/template/gen_user_exercises.qtpl:14
			if i < len(profile.Injuries())-1 {
//line llm/embedding/template/gen_user_exercises.qtpl:14
				qw422016.N().S(`, `)
//line llm/embedding/template/gen_user_exercises.qtpl:14
			}
//line llm/embedding/template/gen_user_exercises.qtpl:14
		}
//line llm/embedding/template/gen_user_exercises.qtpl:14
		qw422016.N().S(`. `)
//line llm/embedding/template/gen_user_exercises.qtpl:15
	}
//line llm/embedding/template/gen_user_exercises.qtpl:15
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:16
	if len(profile.Limitations()) > 0 {
//line llm/embedding/template/gen_user_exercises.qtpl:16
		qw422016.N().S(` Limitations: `)
//line llm/embedding/template/gen_user_exercises.qtpl:18
		for i, limitation := range profile.Limitations() {
//line llm/embedding/template/gen_user_exercises.qtpl:18
			qw422016.E().S(limitation)
//line llm/embedding/template/gen_user_exercises.qtpl:18
			if i < len(profile.Limitations())-1 {
//line llm/embedding/template/gen_user_exercises.qtpl:18
				qw422016.N().S(`, `)
//line llm/embedding/template/gen_user_exercises.qtpl:18
			}
//line llm/embedding/template/gen_user_exercises.qtpl:18
		}
//line llm/embedding/template/gen_user_exercises.qtpl:18
		qw422016.N().S(`. `)
//line llm/embedding/template/gen_user_exercises.qtpl:19
	}
//line llm/embedding/template/gen_user_exercises.qtpl:19
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:20
	if len(equipment) > 0 {
//line llm/embedding/template/gen_user_exercises.qtpl:20
		qw422016.N().S(` Available equipment: `)
//line llm/embedding/template/gen_user_exercises.qtpl:22
		for i, equipment := range equipment {
//line llm/embedding/template/gen_user_exercises.qtpl:22
			qw422016.E().S(equipment)
//line llm/embedding/template/gen_user_exercises.qtpl:22
			if i < len(equipment)-1 {
//line llm/embedding/template/gen_user_exercises.qtpl:22
				qw422016.N().S(`, `)
//line llm/embedding/template/gen_user_exercises.qtpl:22
			}
//line llm/embedding/template/gen_user_exercises.qtpl:22
		}
//line llm/embedding/template/gen_user_exercises.qtpl:22
		qw422016.N().S(`. `)
//line llm/embedding/template/gen_user_exercises.qtpl:23
	}
//line llm/embedding/template/gen_user_exercises.qtpl:23
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:25
	if len(profile.Goals()) == 0 && len(profile.Injuries()) == 0 && len(profile.Limitations()) == 0 {
//line llm/embedding/template/gen_user_exercises.qtpl:25
		qw422016.N().S(` General strength and fitness training exercises. `)
//line llm/embedding/template/gen_user_exercises.qtpl:27
	}
//line llm/embedding/template/gen_user_exercises.qtpl:27
	qw422016.N().S(` `)
//line llm/embedding/template/gen_user_exercises.qtpl:30
}

//line llm/embedding/template/gen_user_exercises.qtpl:30
func WriteGenUserExercises(qq422016 qtio422016.Writer, profile model.Profile, equipment []string) {
//line llm/embedding/template/gen_user_exercises.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/embedding/template/gen_user_exercises.qtpl:30
	StreamGenUserExercises(qw422016, profile, equipment)
//line llm/embedding/template/gen_user_exercises.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line llm/embedding/template/gen_user_exercises.qtpl:30
}

//line llm/embedding/template/gen_user_exercises.qtpl:30
func GenUserExercises(profile model.Profile, equipment []string) string {
//line llm/embedding/template/gen_user_exercises.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/embedding/template/gen_user_exercises.qtpl:30
	WriteGenUserExercises(qb422016, profile, equipment)
//line llm/embedding/template/gen_user_exercises.qtpl:30
	qs422016 := string(qb422016.B)
//line llm/embedding/template/gen_user_exercises.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/embedding/template/gen_user_exercises.qtpl:30
	return qs422016
//line llm/embedding/template/gen_user_exercises.qtpl:30
}
