// Code generated by qtc from "gen_profile.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package rag

import "github.com/streambinder/vigor/model"

import "github.com/streambinder/vigor/util"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamGenProfile(qw422016 *qt422016.Writer, profiles []model.Profile, goals, equipment, muscles []string, prompt string) {
	qw422016.N().S(` `)
	var (
		injuries    []string
		limitations []string
		conditions  []string
	)
	for _, profile := range profiles {
		limitations = append(limitations, profile.Limitations()...)
		conditions = append(conditions, profile.Conditions()...)
		for _, injury := range profile.Injuries() {
			injuries = append(injuries, injury.Description)
		}
	}
	if len(goals) == 0 {
		for _, profile := range profiles {
			for _, goal := range profile.Goals() {
				goals = append(goals, goal)
			}
		}
	}

	injuries = util.Dedupe(injuries)
	limitations = util.Dedupe(limitations)
	conditions = util.Dedupe(conditions)
	goals = util.Dedupe(goals)

	qw422016.N().S(` `)
	if len(prompt) > 0 {
		qw422016.N().S(`Request: `)
		qw422016.E().S(prompt)
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(goals) > 0 {
		qw422016.N().S(`Goals: `)
		for i, goal := range goals {
			qw422016.E().S(goal)
			if i < len(goals)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(injuries) > 0 {
		qw422016.N().S(`Injuries: `)
		for i, injury := range injuries {
			qw422016.E().S(injury)
			if i < len(injuries)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(limitations) > 0 {
		qw422016.N().S(`Limitations: `)
		for i, limitation := range limitations {
			qw422016.E().S(limitation)
			if i < len(limitations)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(conditions) > 0 {
		qw422016.N().S(`Conditions: `)
		for i, condition := range conditions {
			qw422016.E().S(condition)
			if i < len(conditions)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(equipment) > 0 {
		qw422016.N().S(`Equipment: `)
		for i, eq := range equipment {
			qw422016.E().S(eq)
			if i < len(equipment)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
	if len(muscles) > 0 {
		qw422016.N().S(`Muscles: `)
		for i, eq := range muscles {
			qw422016.E().S(eq)
			if i < len(muscles)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
}

func WriteGenProfile(qq422016 qtio422016.Writer, profiles []model.Profile, goals, equipment, muscles []string, prompt string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamGenProfile(qw422016, profiles, goals, equipment, muscles, prompt)
	qt422016.ReleaseWriter(qw422016)
}

func GenProfile(profiles []model.Profile, goals, equipment, muscles []string, prompt string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteGenProfile(qb422016, profiles, goals, equipment, muscles, prompt)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
