// Code generated by qtc from "gen_classic.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_classic.qtpl:1
package rag

//line llm/rag/gen_classic.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_classic.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_classic.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_classic.qtpl:5
func StreamGenClassic(qw422016 *qt422016.Writer, classic model.Classic) {
//line llm/rag/gen_classic.qtpl:6
	qw422016.N().S(` `)
//line llm/rag/gen_classic.qtpl:7
	qw422016.E().S(classic.Excerpt)
//line llm/rag/gen_classic.qtpl:7
	qw422016.N().S(`. `)
//line llm/rag/gen_classic.qtpl:9
}

//line llm/rag/gen_classic.qtpl:9
func WriteGenClassic(qq422016 qtio422016.Writer, classic model.Classic) {
//line llm/rag/gen_classic.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_classic.qtpl:9
	StreamGenClassic(qw422016, classic)
//line llm/rag/gen_classic.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_classic.qtpl:9
}

//line llm/rag/gen_classic.qtpl:9
func GenClassic(classic model.Classic) string {
//line llm/rag/gen_classic.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_classic.qtpl:9
	WriteGenClassic(qb422016, classic)
//line llm/rag/gen_classic.qtpl:9
	qs422016 := string(qb422016.B)
//line llm/rag/gen_classic.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_classic.qtpl:9
	return qs422016
//line llm/rag/gen_classic.qtpl:9
}
