// Code generated by qtc from "gen_fact.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package rag

import "strings"

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamGenFact(qw422016 *qt422016.Writer, fact model.Fact) {
	qw422016.N().S(` `)
	qw422016.E().S(string(fact.Area))
	qw422016.N().S(`: `)
	qw422016.E().S(fact.Content)
	qw422016.N().S(` `)
	if len(fact.Tags) > 0 {
		qw422016.N().S(`Tags: `)
		qw422016.E().S(strings.Join(fact.Tags, ", "))
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` `)
}

func WriteGenFact(qq422016 qtio422016.Writer, fact model.Fact) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamGenFact(qw422016, fact)
	qt422016.ReleaseWriter(qw422016)
}

func GenFact(fact model.Fact) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteGenFact(qb422016, fact)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
