// Code generated by qtc from "gen_user_facts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_user_facts.qtpl:1
package rag

//line llm/rag/gen_user_facts.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_user_facts.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_user_facts.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_user_facts.qtpl:5
func StreamGenUserFacts(qw422016 *qt422016.Writer, profile model.Profile, prompt string) {
//line llm/rag/gen_user_facts.qtpl:6
	qw422016.N().S(` Knowledge for: `)
//line llm/rag/gen_user_facts.qtpl:9
	if len(prompt) > 0 {
//line llm/rag/gen_user_facts.qtpl:9
		qw422016.N().S(`Request: `)
//line llm/rag/gen_user_facts.qtpl:9
		qw422016.E().S(prompt)
//line llm/rag/gen_user_facts.qtpl:9
		qw422016.N().S(`.`)
//line llm/rag/gen_user_facts.qtpl:9
	}
//line llm/rag/gen_user_facts.qtpl:9
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:10
	if len(profile.Goals()) > 0 {
//line llm/rag/gen_user_facts.qtpl:10
		qw422016.N().S(`Goals: `)
//line llm/rag/gen_user_facts.qtpl:10
		for i, goal := range profile.Goals() {
//line llm/rag/gen_user_facts.qtpl:10
			qw422016.E().S(goal.Description)
//line llm/rag/gen_user_facts.qtpl:10
			if i < len(profile.Goals())-1 {
//line llm/rag/gen_user_facts.qtpl:10
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:10
			}
//line llm/rag/gen_user_facts.qtpl:10
		}
//line llm/rag/gen_user_facts.qtpl:10
		qw422016.N().S(`.`)
//line llm/rag/gen_user_facts.qtpl:10
	}
//line llm/rag/gen_user_facts.qtpl:10
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:11
	if len(profile.Injuries()) > 0 {
//line llm/rag/gen_user_facts.qtpl:11
		qw422016.N().S(`Injuries: `)
//line llm/rag/gen_user_facts.qtpl:11
		for i, injury := range profile.Injuries() {
//line llm/rag/gen_user_facts.qtpl:11
			qw422016.E().S(injury.Description)
//line llm/rag/gen_user_facts.qtpl:11
			if i < len(profile.Injuries())-1 {
//line llm/rag/gen_user_facts.qtpl:11
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:11
			}
//line llm/rag/gen_user_facts.qtpl:11
		}
//line llm/rag/gen_user_facts.qtpl:11
		qw422016.N().S(`.`)
//line llm/rag/gen_user_facts.qtpl:11
	}
//line llm/rag/gen_user_facts.qtpl:11
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:12
	if len(profile.Limitations()) > 0 {
//line llm/rag/gen_user_facts.qtpl:12
		qw422016.N().S(`Limitations: `)
//line llm/rag/gen_user_facts.qtpl:12
		for i, limitation := range profile.Limitations() {
//line llm/rag/gen_user_facts.qtpl:12
			qw422016.E().S(limitation)
//line llm/rag/gen_user_facts.qtpl:12
			if i < len(profile.Limitations())-1 {
//line llm/rag/gen_user_facts.qtpl:12
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:12
			}
//line llm/rag/gen_user_facts.qtpl:12
		}
//line llm/rag/gen_user_facts.qtpl:12
		qw422016.N().S(`.`)
//line llm/rag/gen_user_facts.qtpl:12
	}
//line llm/rag/gen_user_facts.qtpl:12
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:13
	if len(prompt) == 0 && len(profile.Goals()) == 0 && len(profile.Injuries()) == 0 && len(profile.Limitations()) == 0 {
//line llm/rag/gen_user_facts.qtpl:13
		qw422016.N().S(`General fitness knowledge.`)
//line llm/rag/gen_user_facts.qtpl:13
	}
//line llm/rag/gen_user_facts.qtpl:13
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:16
}

//line llm/rag/gen_user_facts.qtpl:16
func WriteGenUserFacts(qq422016 qtio422016.Writer, profile model.Profile, prompt string) {
//line llm/rag/gen_user_facts.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_user_facts.qtpl:16
	StreamGenUserFacts(qw422016, profile, prompt)
//line llm/rag/gen_user_facts.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_user_facts.qtpl:16
}

//line llm/rag/gen_user_facts.qtpl:16
func GenUserFacts(profile model.Profile, prompt string) string {
//line llm/rag/gen_user_facts.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_user_facts.qtpl:16
	WriteGenUserFacts(qb422016, profile, prompt)
//line llm/rag/gen_user_facts.qtpl:16
	qs422016 := string(qb422016.B)
//line llm/rag/gen_user_facts.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_user_facts.qtpl:16
	return qs422016
//line llm/rag/gen_user_facts.qtpl:16
}
