// Code generated by qtc from "gen_user_classics.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_user_classics.qtpl:1
package rag

//line llm/rag/gen_user_classics.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_user_classics.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_user_classics.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_user_classics.qtpl:5
func StreamGenUserClassics(qw422016 *qt422016.Writer, profile model.Profile, prompt string) {
//line llm/rag/gen_user_classics.qtpl:6
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:8
	if len(prompt) > 0 {
//line llm/rag/gen_user_classics.qtpl:8
		qw422016.N().S(` Specific request: `)
//line llm/rag/gen_user_classics.qtpl:9
		qw422016.E().S(prompt)
//line llm/rag/gen_user_classics.qtpl:9
		qw422016.N().S(`. `)
//line llm/rag/gen_user_classics.qtpl:10
	}
//line llm/rag/gen_user_classics.qtpl:10
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:12
	if len(profile.Goals()) > 0 {
//line llm/rag/gen_user_classics.qtpl:12
		qw422016.N().S(` Fitness goals: `)
//line llm/rag/gen_user_classics.qtpl:14
		for i, goal := range profile.Goals() {
//line llm/rag/gen_user_classics.qtpl:14
			qw422016.E().S(goal.Description)
//line llm/rag/gen_user_classics.qtpl:14
			if i < len(profile.Goals())-1 {
//line llm/rag/gen_user_classics.qtpl:14
				qw422016.N().S(`, `)
//line llm/rag/gen_user_classics.qtpl:14
			}
//line llm/rag/gen_user_classics.qtpl:14
		}
//line llm/rag/gen_user_classics.qtpl:14
		qw422016.N().S(`. `)
//line llm/rag/gen_user_classics.qtpl:15
	}
//line llm/rag/gen_user_classics.qtpl:15
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:16
	if len(profile.Injuries()) > 0 {
//line llm/rag/gen_user_classics.qtpl:16
		qw422016.N().S(` Avoid exercises that impact: `)
//line llm/rag/gen_user_classics.qtpl:18
		for i, injury := range profile.Injuries() {
//line llm/rag/gen_user_classics.qtpl:18
			qw422016.E().S(injury.Description)
//line llm/rag/gen_user_classics.qtpl:18
			if i < len(profile.Injuries())-1 {
//line llm/rag/gen_user_classics.qtpl:18
				qw422016.N().S(`, `)
//line llm/rag/gen_user_classics.qtpl:18
			}
//line llm/rag/gen_user_classics.qtpl:18
		}
//line llm/rag/gen_user_classics.qtpl:18
		qw422016.N().S(`. `)
//line llm/rag/gen_user_classics.qtpl:19
	}
//line llm/rag/gen_user_classics.qtpl:19
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:20
	if len(profile.Limitations()) > 0 {
//line llm/rag/gen_user_classics.qtpl:20
		qw422016.N().S(` Limitations: `)
//line llm/rag/gen_user_classics.qtpl:22
		for i, limitation := range profile.Limitations() {
//line llm/rag/gen_user_classics.qtpl:22
			qw422016.E().S(limitation)
//line llm/rag/gen_user_classics.qtpl:22
			if i < len(profile.Limitations())-1 {
//line llm/rag/gen_user_classics.qtpl:22
				qw422016.N().S(`, `)
//line llm/rag/gen_user_classics.qtpl:22
			}
//line llm/rag/gen_user_classics.qtpl:22
		}
//line llm/rag/gen_user_classics.qtpl:22
		qw422016.N().S(`. `)
//line llm/rag/gen_user_classics.qtpl:23
	}
//line llm/rag/gen_user_classics.qtpl:23
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:25
	if len(profile.Goals()) == 0 && len(profile.Injuries()) == 0 && len(profile.Limitations()) == 0 {
//line llm/rag/gen_user_classics.qtpl:25
		qw422016.N().S(` General strength and fitness training exercises. `)
//line llm/rag/gen_user_classics.qtpl:27
	}
//line llm/rag/gen_user_classics.qtpl:27
	qw422016.N().S(` `)
//line llm/rag/gen_user_classics.qtpl:30
}

//line llm/rag/gen_user_classics.qtpl:30
func WriteGenUserClassics(qq422016 qtio422016.Writer, profile model.Profile, prompt string) {
//line llm/rag/gen_user_classics.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_user_classics.qtpl:30
	StreamGenUserClassics(qw422016, profile, prompt)
//line llm/rag/gen_user_classics.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_user_classics.qtpl:30
}

//line llm/rag/gen_user_classics.qtpl:30
func GenUserClassics(profile model.Profile, prompt string) string {
//line llm/rag/gen_user_classics.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_user_classics.qtpl:30
	WriteGenUserClassics(qb422016, profile, prompt)
//line llm/rag/gen_user_classics.qtpl:30
	qs422016 := string(qb422016.B)
//line llm/rag/gen_user_classics.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_user_classics.qtpl:30
	return qs422016
//line llm/rag/gen_user_classics.qtpl:30
}
