// Code generated by qtc from "gen_user_facts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_user_facts.qtpl:1
package rag

//line llm/rag/gen_user_facts.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_user_facts.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_user_facts.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_user_facts.qtpl:5
func StreamGenUserFacts(qw422016 *qt422016.Writer, profile model.Profile) {
//line llm/rag/gen_user_facts.qtpl:6
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:8
	if len(profile.Goals()) > 0 {
//line llm/rag/gen_user_facts.qtpl:8
		qw422016.N().S(` Fitness goals: `)
//line llm/rag/gen_user_facts.qtpl:10
		for i, goal := range profile.Goals() {
//line llm/rag/gen_user_facts.qtpl:10
			qw422016.E().S(goal.Description)
//line llm/rag/gen_user_facts.qtpl:10
			if i < len(profile.Goals())-1 {
//line llm/rag/gen_user_facts.qtpl:10
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:10
			}
//line llm/rag/gen_user_facts.qtpl:10
		}
//line llm/rag/gen_user_facts.qtpl:10
		qw422016.N().S(`. `)
//line llm/rag/gen_user_facts.qtpl:11
	}
//line llm/rag/gen_user_facts.qtpl:11
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:12
	if len(profile.Injuries()) > 0 {
//line llm/rag/gen_user_facts.qtpl:12
		qw422016.N().S(` Avoid exercises that impact: `)
//line llm/rag/gen_user_facts.qtpl:14
		for i, injury := range profile.Injuries() {
//line llm/rag/gen_user_facts.qtpl:14
			qw422016.E().S(injury.Description)
//line llm/rag/gen_user_facts.qtpl:14
			if i < len(profile.Injuries())-1 {
//line llm/rag/gen_user_facts.qtpl:14
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:14
			}
//line llm/rag/gen_user_facts.qtpl:14
		}
//line llm/rag/gen_user_facts.qtpl:14
		qw422016.N().S(`. `)
//line llm/rag/gen_user_facts.qtpl:15
	}
//line llm/rag/gen_user_facts.qtpl:15
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:16
	if len(profile.Limitations()) > 0 {
//line llm/rag/gen_user_facts.qtpl:16
		qw422016.N().S(` Limitations: `)
//line llm/rag/gen_user_facts.qtpl:18
		for i, limitation := range profile.Limitations() {
//line llm/rag/gen_user_facts.qtpl:18
			qw422016.E().S(limitation)
//line llm/rag/gen_user_facts.qtpl:18
			if i < len(profile.Limitations())-1 {
//line llm/rag/gen_user_facts.qtpl:18
				qw422016.N().S(`, `)
//line llm/rag/gen_user_facts.qtpl:18
			}
//line llm/rag/gen_user_facts.qtpl:18
		}
//line llm/rag/gen_user_facts.qtpl:18
		qw422016.N().S(`. `)
//line llm/rag/gen_user_facts.qtpl:19
	}
//line llm/rag/gen_user_facts.qtpl:19
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:21
	if len(profile.Goals()) == 0 && len(profile.Injuries()) == 0 && len(profile.Limitations()) == 0 {
//line llm/rag/gen_user_facts.qtpl:21
		qw422016.N().S(` General strength and fitness training exercises. `)
//line llm/rag/gen_user_facts.qtpl:23
	}
//line llm/rag/gen_user_facts.qtpl:23
	qw422016.N().S(` `)
//line llm/rag/gen_user_facts.qtpl:26
}

//line llm/rag/gen_user_facts.qtpl:26
func WriteGenUserFacts(qq422016 qtio422016.Writer, profile model.Profile) {
//line llm/rag/gen_user_facts.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_user_facts.qtpl:26
	StreamGenUserFacts(qw422016, profile)
//line llm/rag/gen_user_facts.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_user_facts.qtpl:26
}

//line llm/rag/gen_user_facts.qtpl:26
func GenUserFacts(profile model.Profile) string {
//line llm/rag/gen_user_facts.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_user_facts.qtpl:26
	WriteGenUserFacts(qb422016, profile)
//line llm/rag/gen_user_facts.qtpl:26
	qs422016 := string(qb422016.B)
//line llm/rag/gen_user_facts.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_user_facts.qtpl:26
	return qs422016
//line llm/rag/gen_user_facts.qtpl:26
}
