// Code generated by qtc from "gen_exercise.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package rag

import "strings"

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamGenExercise(qw422016 *qt422016.Writer, exercise model.Exercise) {
	qw422016.N().S(` `)
	qw422016.E().S(exercise.Name)
	qw422016.N().S(`. `)
	if len(exercise.Equipment) > 0 {
		qw422016.N().S(`Equipment: `)
		qw422016.E().S(strings.Join(exercise.Equipment, ", "))
		qw422016.N().S(`.`)
	}
	qw422016.N().S(` Muscles: `)
	qw422016.E().S(strings.Join(exercise.Muscles, ", "))
	qw422016.N().S(`. `)
	if len(exercise.Instructions) > 0 {
		for i, instruction := range exercise.Instructions {
			qw422016.N().D(i + 1)
			qw422016.N().S(`. `)
			qw422016.E().S(instruction)
			qw422016.N().S(` `)
		}
	}
	qw422016.N().S(` `)
}

func WriteGenExercise(qq422016 qtio422016.Writer, exercise model.Exercise) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamGenExercise(qw422016, exercise)
	qt422016.ReleaseWriter(qw422016)
}

func GenExercise(exercise model.Exercise) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteGenExercise(qb422016, exercise)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
