// Code generated by qtc from "gen_profile.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_profile.qtpl:1
package rag

//line llm/rag/gen_profile.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_profile.qtpl:4
import "github.com/streambinder/vigor/util"

//line llm/rag/gen_profile.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_profile.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_profile.qtpl:6
func StreamGenProfile(qw422016 *qt422016.Writer, profiles []model.Profile, goals, equipment, muscles []string, prompt string) {
//line llm/rag/gen_profile.qtpl:7
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:11
	var (
		injuries    []string
		limitations []string
		conditions  []string
	)
	for _, profile := range profiles {
		limitations = append(limitations, profile.Limitations()...)
		conditions = append(conditions, profile.Conditions()...)
		for _, injury := range profile.Injuries() {
			injuries = append(injuries, injury.Description)
		}
	}
	if len(goals) == 0 {
		for _, profile := range profiles {
			for _, goal := range profile.Goals() {
				goals = append(goals, goal)
			}
		}
	}

	injuries = util.Dedupe(injuries)
	limitations = util.Dedupe(limitations)
	conditions = util.Dedupe(conditions)
	goals = util.Dedupe(goals)

//line llm/rag/gen_profile.qtpl:36
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:38
	if len(prompt) > 0 {
//line llm/rag/gen_profile.qtpl:38
		qw422016.N().S(`Request: `)
//line llm/rag/gen_profile.qtpl:38
		qw422016.E().S(prompt)
//line llm/rag/gen_profile.qtpl:38
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:38
	}
//line llm/rag/gen_profile.qtpl:38
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:39
	if len(goals) > 0 {
//line llm/rag/gen_profile.qtpl:39
		qw422016.N().S(`Goals: `)
//line llm/rag/gen_profile.qtpl:39
		for i, goal := range goals {
//line llm/rag/gen_profile.qtpl:39
			qw422016.E().S(goal)
//line llm/rag/gen_profile.qtpl:39
			if i < len(goals)-1 {
//line llm/rag/gen_profile.qtpl:39
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:39
			}
//line llm/rag/gen_profile.qtpl:39
		}
//line llm/rag/gen_profile.qtpl:39
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:39
	}
//line llm/rag/gen_profile.qtpl:39
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:40
	if len(injuries) > 0 {
//line llm/rag/gen_profile.qtpl:40
		qw422016.N().S(`Injuries: `)
//line llm/rag/gen_profile.qtpl:40
		for i, injury := range injuries {
//line llm/rag/gen_profile.qtpl:40
			qw422016.E().S(injury)
//line llm/rag/gen_profile.qtpl:40
			if i < len(injuries)-1 {
//line llm/rag/gen_profile.qtpl:40
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:40
			}
//line llm/rag/gen_profile.qtpl:40
		}
//line llm/rag/gen_profile.qtpl:40
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:40
	}
//line llm/rag/gen_profile.qtpl:40
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:41
	if len(limitations) > 0 {
//line llm/rag/gen_profile.qtpl:41
		qw422016.N().S(`Limitations: `)
//line llm/rag/gen_profile.qtpl:41
		for i, limitation := range limitations {
//line llm/rag/gen_profile.qtpl:41
			qw422016.E().S(limitation)
//line llm/rag/gen_profile.qtpl:41
			if i < len(limitations)-1 {
//line llm/rag/gen_profile.qtpl:41
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:41
			}
//line llm/rag/gen_profile.qtpl:41
		}
//line llm/rag/gen_profile.qtpl:41
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:41
	}
//line llm/rag/gen_profile.qtpl:41
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:42
	if len(conditions) > 0 {
//line llm/rag/gen_profile.qtpl:42
		qw422016.N().S(`Conditions: `)
//line llm/rag/gen_profile.qtpl:42
		for i, condition := range conditions {
//line llm/rag/gen_profile.qtpl:42
			qw422016.E().S(condition)
//line llm/rag/gen_profile.qtpl:42
			if i < len(conditions)-1 {
//line llm/rag/gen_profile.qtpl:42
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:42
			}
//line llm/rag/gen_profile.qtpl:42
		}
//line llm/rag/gen_profile.qtpl:42
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:42
	}
//line llm/rag/gen_profile.qtpl:42
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:43
	if len(equipment) > 0 {
//line llm/rag/gen_profile.qtpl:43
		qw422016.N().S(`Equipment: `)
//line llm/rag/gen_profile.qtpl:43
		for i, eq := range equipment {
//line llm/rag/gen_profile.qtpl:43
			qw422016.E().S(eq)
//line llm/rag/gen_profile.qtpl:43
			if i < len(equipment)-1 {
//line llm/rag/gen_profile.qtpl:43
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:43
			}
//line llm/rag/gen_profile.qtpl:43
		}
//line llm/rag/gen_profile.qtpl:43
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:43
	}
//line llm/rag/gen_profile.qtpl:43
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:44
	if len(muscles) > 0 {
//line llm/rag/gen_profile.qtpl:44
		qw422016.N().S(`Muscles: `)
//line llm/rag/gen_profile.qtpl:44
		for i, eq := range muscles {
//line llm/rag/gen_profile.qtpl:44
			qw422016.E().S(eq)
//line llm/rag/gen_profile.qtpl:44
			if i < len(muscles)-1 {
//line llm/rag/gen_profile.qtpl:44
				qw422016.N().S(`, `)
//line llm/rag/gen_profile.qtpl:44
			}
//line llm/rag/gen_profile.qtpl:44
		}
//line llm/rag/gen_profile.qtpl:44
		qw422016.N().S(`.`)
//line llm/rag/gen_profile.qtpl:44
	}
//line llm/rag/gen_profile.qtpl:44
	qw422016.N().S(` `)
//line llm/rag/gen_profile.qtpl:47
}

//line llm/rag/gen_profile.qtpl:47
func WriteGenProfile(qq422016 qtio422016.Writer, profiles []model.Profile, goals, equipment, muscles []string, prompt string) {
//line llm/rag/gen_profile.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_profile.qtpl:47
	StreamGenProfile(qw422016, profiles, goals, equipment, muscles, prompt)
//line llm/rag/gen_profile.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_profile.qtpl:47
}

//line llm/rag/gen_profile.qtpl:47
func GenProfile(profiles []model.Profile, goals, equipment, muscles []string, prompt string) string {
//line llm/rag/gen_profile.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_profile.qtpl:47
	WriteGenProfile(qb422016, profiles, goals, equipment, muscles, prompt)
//line llm/rag/gen_profile.qtpl:47
	qs422016 := string(qb422016.B)
//line llm/rag/gen_profile.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_profile.qtpl:47
	return qs422016
//line llm/rag/gen_profile.qtpl:47
}
