// Code generated by qtc from "gen_user_exercises.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/rag/gen_user_exercises.qtpl:1
package rag

//line llm/rag/gen_user_exercises.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/rag/gen_user_exercises.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/rag/gen_user_exercises.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/rag/gen_user_exercises.qtpl:5
func StreamGenUserExercises(qw422016 *qt422016.Writer, profiles []model.Profile, equipment []string) {
//line llm/rag/gen_user_exercises.qtpl:6
	qw422016.N().S(` Exercises for: `)
//line llm/rag/gen_user_exercises.qtpl:10
	var allGoals, allInjuries, allLimitations []string
	goalSet := make(map[string]bool)
	injurySet := make(map[string]bool)
	limitationSet := make(map[string]bool)
	for _, profile := range profiles {
		for _, goal := range profile.Goals() {
			if !goalSet[goal] {
				goalSet[goal] = true
				allGoals = append(allGoals, goal)
			}
		}
		for _, injury := range profile.Injuries() {
			if !injurySet[injury.Description] {
				injurySet[injury.Description] = true
				allInjuries = append(allInjuries, injury.Description)
			}
		}
		for _, limitation := range profile.Limitations() {
			if !limitationSet[limitation] {
				limitationSet[limitation] = true
				allLimitations = append(allLimitations, limitation)
			}
		}
	}

//line llm/rag/gen_user_exercises.qtpl:34
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:35
	if len(allGoals) > 0 {
//line llm/rag/gen_user_exercises.qtpl:35
		qw422016.N().S(`Goals: `)
//line llm/rag/gen_user_exercises.qtpl:35
		for i, goal := range allGoals {
//line llm/rag/gen_user_exercises.qtpl:35
			qw422016.E().S(goal)
//line llm/rag/gen_user_exercises.qtpl:35
			if i < len(allGoals)-1 {
//line llm/rag/gen_user_exercises.qtpl:35
				qw422016.N().S(`, `)
//line llm/rag/gen_user_exercises.qtpl:35
			}
//line llm/rag/gen_user_exercises.qtpl:35
		}
//line llm/rag/gen_user_exercises.qtpl:35
		qw422016.N().S(`.`)
//line llm/rag/gen_user_exercises.qtpl:35
	}
//line llm/rag/gen_user_exercises.qtpl:35
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:36
	if len(allInjuries) > 0 {
//line llm/rag/gen_user_exercises.qtpl:36
		qw422016.N().S(`Avoid: `)
//line llm/rag/gen_user_exercises.qtpl:36
		for i, injury := range allInjuries {
//line llm/rag/gen_user_exercises.qtpl:36
			qw422016.E().S(injury)
//line llm/rag/gen_user_exercises.qtpl:36
			if i < len(allInjuries)-1 {
//line llm/rag/gen_user_exercises.qtpl:36
				qw422016.N().S(`, `)
//line llm/rag/gen_user_exercises.qtpl:36
			}
//line llm/rag/gen_user_exercises.qtpl:36
		}
//line llm/rag/gen_user_exercises.qtpl:36
		qw422016.N().S(`.`)
//line llm/rag/gen_user_exercises.qtpl:36
	}
//line llm/rag/gen_user_exercises.qtpl:36
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:37
	if len(allLimitations) > 0 {
//line llm/rag/gen_user_exercises.qtpl:37
		qw422016.N().S(`Limitations: `)
//line llm/rag/gen_user_exercises.qtpl:37
		for i, limitation := range allLimitations {
//line llm/rag/gen_user_exercises.qtpl:37
			qw422016.E().S(limitation)
//line llm/rag/gen_user_exercises.qtpl:37
			if i < len(allLimitations)-1 {
//line llm/rag/gen_user_exercises.qtpl:37
				qw422016.N().S(`, `)
//line llm/rag/gen_user_exercises.qtpl:37
			}
//line llm/rag/gen_user_exercises.qtpl:37
		}
//line llm/rag/gen_user_exercises.qtpl:37
		qw422016.N().S(`.`)
//line llm/rag/gen_user_exercises.qtpl:37
	}
//line llm/rag/gen_user_exercises.qtpl:37
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:38
	if len(equipment) > 0 {
//line llm/rag/gen_user_exercises.qtpl:38
		qw422016.N().S(`Equipment: `)
//line llm/rag/gen_user_exercises.qtpl:38
		for i, eq := range equipment {
//line llm/rag/gen_user_exercises.qtpl:38
			qw422016.E().S(eq)
//line llm/rag/gen_user_exercises.qtpl:38
			if i < len(equipment)-1 {
//line llm/rag/gen_user_exercises.qtpl:38
				qw422016.N().S(`, `)
//line llm/rag/gen_user_exercises.qtpl:38
			}
//line llm/rag/gen_user_exercises.qtpl:38
		}
//line llm/rag/gen_user_exercises.qtpl:38
		qw422016.N().S(`.`)
//line llm/rag/gen_user_exercises.qtpl:38
	}
//line llm/rag/gen_user_exercises.qtpl:38
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:39
	if len(allGoals) == 0 && len(allInjuries) == 0 && len(allLimitations) == 0 && len(equipment) == 0 {
//line llm/rag/gen_user_exercises.qtpl:39
		qw422016.N().S(`General fitness exercises.`)
//line llm/rag/gen_user_exercises.qtpl:39
	}
//line llm/rag/gen_user_exercises.qtpl:39
	qw422016.N().S(` `)
//line llm/rag/gen_user_exercises.qtpl:42
}

//line llm/rag/gen_user_exercises.qtpl:42
func WriteGenUserExercises(qq422016 qtio422016.Writer, profiles []model.Profile, equipment []string) {
//line llm/rag/gen_user_exercises.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/rag/gen_user_exercises.qtpl:42
	StreamGenUserExercises(qw422016, profiles, equipment)
//line llm/rag/gen_user_exercises.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line llm/rag/gen_user_exercises.qtpl:42
}

//line llm/rag/gen_user_exercises.qtpl:42
func GenUserExercises(profiles []model.Profile, equipment []string) string {
//line llm/rag/gen_user_exercises.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/rag/gen_user_exercises.qtpl:42
	WriteGenUserExercises(qb422016, profiles, equipment)
//line llm/rag/gen_user_exercises.qtpl:42
	qs422016 := string(qb422016.B)
//line llm/rag/gen_user_exercises.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/rag/gen_user_exercises.qtpl:42
	return qs422016
//line llm/rag/gen_user_exercises.qtpl:42
}
