// Code generated by qtc from "gen_profile.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line gen_profile.qtpl:1
package rag

//line gen_profile.qtpl:3
import "github.com/streambinder/vigor/model"

//line gen_profile.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line gen_profile.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line gen_profile.qtpl:6
type ProfilePurpose int

const (
	ProfilePurposeFacts ProfilePurpose = iota
	ProfilePurposeExercises
)

//line gen_profile.qtpl:14
func StreamGenProfile(qw422016 *qt422016.Writer, profiles []model.Profile, goals []string, equipment []string, prompt string, purpose ProfilePurpose) {
//line gen_profile.qtpl:15
	qw422016.N().S(` `)
//line gen_profile.qtpl:17
	if purpose == ProfilePurposeFacts {
//line gen_profile.qtpl:17
		qw422016.N().S(`Knowledge for:`)
//line gen_profile.qtpl:17
	} else {
//line gen_profile.qtpl:17
		qw422016.N().S(`Exercises for:`)
//line gen_profile.qtpl:17
	}
//line gen_profile.qtpl:17
	qw422016.N().S(` `)
//line gen_profile.qtpl:19
	var allGoals, allInjuries, allLimitations, allConditions []string
	goalSet := make(map[string]bool)
	injurySet := make(map[string]bool)
	limitationSet := make(map[string]bool)
	conditionSet := make(map[string]bool)
	for _, goal := range goals {
		if !goalSet[goal] {
			goalSet[goal] = true
			allGoals = append(allGoals, goal)
		}
	}
	for _, profile := range profiles {
		for _, injury := range profile.Injuries() {
			if !injurySet[injury.Description] {
				injurySet[injury.Description] = true
				allInjuries = append(allInjuries, injury.Description)
			}
		}
		for _, limitation := range profile.Limitations() {
			if !limitationSet[limitation] {
				limitationSet[limitation] = true
				allLimitations = append(allLimitations, limitation)
			}
		}
		for _, condition := range profile.Conditions() {
			if !conditionSet[condition] {
				conditionSet[condition] = true
				allConditions = append(allConditions, condition)
			}
		}
	}

//line gen_profile.qtpl:50
	qw422016.N().S(` `)
//line gen_profile.qtpl:51
	if len(prompt) > 0 {
//line gen_profile.qtpl:51
		qw422016.N().S(`Request: `)
//line gen_profile.qtpl:51
		qw422016.E().S(prompt)
//line gen_profile.qtpl:51
		qw422016.N().S(`.`)
//line gen_profile.qtpl:51
	}
//line gen_profile.qtpl:51
	qw422016.N().S(` `)
//line gen_profile.qtpl:52
	if len(allGoals) > 0 {
//line gen_profile.qtpl:52
		qw422016.N().S(`Goals: `)
//line gen_profile.qtpl:52
		for i, goal := range allGoals {
//line gen_profile.qtpl:52
			qw422016.E().S(goal)
//line gen_profile.qtpl:52
			if i < len(allGoals)-1 {
//line gen_profile.qtpl:52
				qw422016.N().S(`, `)
//line gen_profile.qtpl:52
			}
//line gen_profile.qtpl:52
		}
//line gen_profile.qtpl:52
		qw422016.N().S(`.`)
//line gen_profile.qtpl:52
	}
//line gen_profile.qtpl:52
	qw422016.N().S(` `)
//line gen_profile.qtpl:53
	if len(allInjuries) > 0 {
//line gen_profile.qtpl:53
		if purpose == ProfilePurposeFacts {
//line gen_profile.qtpl:53
			qw422016.N().S(`Injuries`)
//line gen_profile.qtpl:53
		} else {
//line gen_profile.qtpl:53
			qw422016.N().S(`Avoid`)
//line gen_profile.qtpl:53
		}
//line gen_profile.qtpl:53
		qw422016.N().S(`: `)
//line gen_profile.qtpl:53
		for i, injury := range allInjuries {
//line gen_profile.qtpl:53
			qw422016.E().S(injury)
//line gen_profile.qtpl:53
			if i < len(allInjuries)-1 {
//line gen_profile.qtpl:53
				qw422016.N().S(`, `)
//line gen_profile.qtpl:53
			}
//line gen_profile.qtpl:53
		}
//line gen_profile.qtpl:53
		qw422016.N().S(`.`)
//line gen_profile.qtpl:53
	}
//line gen_profile.qtpl:53
	qw422016.N().S(` `)
//line gen_profile.qtpl:54
	if len(allLimitations) > 0 {
//line gen_profile.qtpl:54
		qw422016.N().S(`Limitations: `)
//line gen_profile.qtpl:54
		for i, limitation := range allLimitations {
//line gen_profile.qtpl:54
			qw422016.E().S(limitation)
//line gen_profile.qtpl:54
			if i < len(allLimitations)-1 {
//line gen_profile.qtpl:54
				qw422016.N().S(`, `)
//line gen_profile.qtpl:54
			}
//line gen_profile.qtpl:54
		}
//line gen_profile.qtpl:54
		qw422016.N().S(`.`)
//line gen_profile.qtpl:54
	}
//line gen_profile.qtpl:54
	qw422016.N().S(` `)
//line gen_profile.qtpl:55
	if len(allConditions) > 0 {
//line gen_profile.qtpl:55
		qw422016.N().S(`Conditions: `)
//line gen_profile.qtpl:55
		for i, condition := range allConditions {
//line gen_profile.qtpl:55
			qw422016.E().S(condition)
//line gen_profile.qtpl:55
			if i < len(allConditions)-1 {
//line gen_profile.qtpl:55
				qw422016.N().S(`, `)
//line gen_profile.qtpl:55
			}
//line gen_profile.qtpl:55
		}
//line gen_profile.qtpl:55
		qw422016.N().S(`.`)
//line gen_profile.qtpl:55
	}
//line gen_profile.qtpl:55
	qw422016.N().S(` `)
//line gen_profile.qtpl:56
	if purpose == ProfilePurposeExercises && len(equipment) > 0 {
//line gen_profile.qtpl:56
		qw422016.N().S(`Equipment: `)
//line gen_profile.qtpl:56
		for i, eq := range equipment {
//line gen_profile.qtpl:56
			qw422016.E().S(eq)
//line gen_profile.qtpl:56
			if i < len(equipment)-1 {
//line gen_profile.qtpl:56
				qw422016.N().S(`, `)
//line gen_profile.qtpl:56
			}
//line gen_profile.qtpl:56
		}
//line gen_profile.qtpl:56
		qw422016.N().S(`.`)
//line gen_profile.qtpl:56
	}
//line gen_profile.qtpl:56
	qw422016.N().S(` `)
//line gen_profile.qtpl:58
	hasContent := len(prompt) > 0 || len(allGoals) > 0 || len(allInjuries) > 0 || len(allLimitations) > 0 || len(allConditions) > 0
	if purpose == ProfilePurposeExercises {
		hasContent = hasContent || len(equipment) > 0
	}

//line gen_profile.qtpl:62
	qw422016.N().S(` `)
//line gen_profile.qtpl:63
	if !hasContent {
//line gen_profile.qtpl:63
		if purpose == ProfilePurposeFacts {
//line gen_profile.qtpl:63
			qw422016.N().S(`General fitness knowledge.`)
//line gen_profile.qtpl:63
		} else {
//line gen_profile.qtpl:63
			qw422016.N().S(`General fitness exercises.`)
//line gen_profile.qtpl:63
		}
//line gen_profile.qtpl:63
	}
//line gen_profile.qtpl:63
	qw422016.N().S(` `)
//line gen_profile.qtpl:66
}

//line gen_profile.qtpl:66
func WriteGenProfile(qq422016 qtio422016.Writer, profiles []model.Profile, goals []string, equipment []string, prompt string, purpose ProfilePurpose) {
//line gen_profile.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line gen_profile.qtpl:66
	StreamGenProfile(qw422016, profiles, goals, equipment, prompt, purpose)
//line gen_profile.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line gen_profile.qtpl:66
}

//line gen_profile.qtpl:66
func GenProfile(profiles []model.Profile, goals []string, equipment []string, prompt string, purpose ProfilePurpose) string {
//line gen_profile.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line gen_profile.qtpl:66
	WriteGenProfile(qb422016, profiles, goals, equipment, prompt, purpose)
//line gen_profile.qtpl:66
	qs422016 := string(qb422016.B)
//line gen_profile.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line gen_profile.qtpl:66
	return qs422016
//line gen_profile.qtpl:66
}
