name: vigor
description: Vigor mobile application for fitness training management
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.1
  http: ^1.6.0
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.11.3

flutter:
  generate: true
  uses-material-design: true
