---
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U user -d db"]
  knowledge:
    image: ghcr.io/streambinder/vigor/knowledge:latest
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d db"]
  # llama-server -hf ggml-org/gpt-oss-20b-GGUF  --ctx-size 0 --jinja -ub 2048 -b 2048 --port 8000
  # llama-server -hf bartowski/Llama-3.2-1B-Instruct-GGUF --ctx-size 0 --jinja -ub 2048 -b 2048 --port 8000
  # llm:
  #   image: ghcr.io/ggml-org/llama.cpp:server
  #   platform: linux/amd64
  #   command:
  #     - --model
  #     - /models/Mistral-Nemo-Instruct-2407-Q5_K_M.gguf
  #     - --port
  #     - "8000"
  #     - --ctx-size
  #     - "0"
  #     - --jinja
  #     - -ub
  #     - "2048"
  #     - -b
  #     - "2048"
  #     # - --n-gpu-layers
  #     # - "99"
  #     # - --threads
  #     # - "8"
  #     # - --batch-size
  #     # - "512"
  #     # - --ubatch-size
  #     # - "128"
  #   volumes:
  #     - ../models:/models:ro
  #   ports:
  #     - 8000:8000
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [gpu]
  # vigor:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     llm:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgres://user:pass@db:5432/db?sslmode=disable
  #   ports:
  #     - 8080:8080

volumes:
  db_data:
