---
exit-code: 1
exit-on-eol: 2
scan:
  disable-telemetry: true
  scanners:
    - vuln
    - misconfig
    - secret
misconfiguration:
  scanners:
    - dockerfile
    - kubernetes
    - terraform
    - cloudformation
    - terraformplan-snapshot
    - terraformplan-json
    - helm
    - azure-arm
  exclude-checks:
    - DS-0002 # nginx app image runs master as root by design
