// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'delete_training_response.g.dart';

@JsonSerializable(explicitToJson: true)
class DeleteTrainingResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  DeleteTrainingResponse({
    required this.message,
  });

  factory DeleteTrainingResponse.fromJson(Map<String, dynamic> json) => _$DeleteTrainingResponseFromJson(json);

  Map<String, dynamic> toJson() => _$DeleteTrainingResponseToJson(this);
}
