// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'delete_gym_response.g.dart';

@JsonSerializable(explicitToJson: true)
class DeleteGymResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  DeleteGymResponse({
    required this.message,
  });

  factory DeleteGymResponse.fromJson(Map<String, dynamic> json) => _$DeleteGymResponseFromJson(json);

  Map<String, dynamic> toJson() => _$DeleteGymResponseToJson(this);
}
