// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'equipment_item.g.dart';

@JsonSerializable(explicitToJson: true)
class EquipmentItem {
  @JsonKey(name: 'id', defaultValue: '')
  final String id;
  @JsonKey(name: 'is_weighted')
  final bool isWeighted;
  @JsonKey(name: 'aliases')
  final List<String>? aliases;

  EquipmentItem({
    required this.id,
    required this.isWeighted,
    this.aliases,
  });

  factory EquipmentItem.fromJson(Map<String, dynamic> json) => _$EquipmentItemFromJson(json);

  Map<String, dynamic> toJson() => _$EquipmentItemToJson(this);
}
