// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/training.dart';

part 'get_training_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetTrainingResponse {
  @JsonKey(name: 'trainings', defaultValue: [])
  final List<Training> trainings;

  GetTrainingResponse({
    required this.trainings,
  });

  factory GetTrainingResponse.fromJson(Map<String, dynamic> json) => _$GetTrainingResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetTrainingResponseToJson(this);
}
