// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'get_muscles_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetMusclesResponse {
  @JsonKey(name: 'muscles', defaultValue: [])
  final List<String> muscles;

  GetMusclesResponse({
    required this.muscles,
  });

  factory GetMusclesResponse.fromJson(Map<String, dynamic> json) => _$GetMusclesResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetMusclesResponseToJson(this);
}
