// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/gym.dart';

part 'get_gyms_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetGymsResponse {
  @JsonKey(name: 'gyms', defaultValue: const [])
  final List<Gym> gyms;

  GetGymsResponse({
    required this.gyms,
  });

  factory GetGymsResponse.fromJson(Map<String, dynamic> json) => _$GetGymsResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetGymsResponseToJson(this);
}
