// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'get_methodologies_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetMethodologiesResponse {
  @JsonKey(name: 'methodologies', defaultValue: [])
  final List<String> methodologies;

  GetMethodologiesResponse({
    required this.methodologies,
  });

  factory GetMethodologiesResponse.fromJson(Map<String, dynamic> json) => _$GetMethodologiesResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetMethodologiesResponseToJson(this);
}
