// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import 'partner_info.dart';

part 'get_training_partners_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetTrainingPartnersResponse {
  @JsonKey(name: 'partners', defaultValue: [])
  final List<PartnerInfo> partners;

  GetTrainingPartnersResponse({
    required this.partners,
  });

  factory GetTrainingPartnersResponse.fromJson(Map<String, dynamic> json) => _$GetTrainingPartnersResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetTrainingPartnersResponseToJson(this);
}
