// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/training.dart';
import 'shared_training_owner.dart';

part 'get_shared_training_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetSharedTrainingResponse {
  @JsonKey(name: 'training')
  final Training? training;
  @JsonKey(name: 'owner')
  final SharedTrainingOwner owner;

  GetSharedTrainingResponse({
    this.training,
    required this.owner,
  });

  factory GetSharedTrainingResponse.fromJson(Map<String, dynamic> json) => _$GetSharedTrainingResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetSharedTrainingResponseToJson(this);
}
