// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'get_movement_families_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetMovementFamiliesResponse {
  @JsonKey(name: 'movement_families', defaultValue: [])
  final List<String> movementFamilies;

  GetMovementFamiliesResponse({
    required this.movementFamilies,
  });

  factory GetMovementFamiliesResponse.fromJson(Map<String, dynamic> json) => _$GetMovementFamiliesResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetMovementFamiliesResponseToJson(this);
}
