// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/flow_session.dart';

part 'get_flow_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetFlowResponse {
  @JsonKey(name: 'sessions', defaultValue: [])
  final List<FlowSession> sessions;

  GetFlowResponse({
    required this.sessions,
  });

  factory GetFlowResponse.fromJson(Map<String, dynamic> json) => _$GetFlowResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetFlowResponseToJson(this);
}
