// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'get_goals_response.g.dart';

@JsonSerializable(explicitToJson: true)
class GetGoalsResponse {
  @JsonKey(name: 'goals', defaultValue: const [])
  final List<String> goals;

  GetGoalsResponse({
    required this.goals,
  });

  factory GetGoalsResponse.fromJson(Map<String, dynamic> json) => _$GetGoalsResponseFromJson(json);

  Map<String, dynamic> toJson() => _$GetGoalsResponseToJson(this);
}
