// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_complete_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingCompleteRequest {
  @JsonKey(name: 'feedback', defaultValue: '')
  final String feedback;
  @JsonKey(name: 'activityFeedback')
  final Map<String, dynamic> activityFeedback;
  @JsonKey(name: 'activityReports', defaultValue: const [])
  final List<String> activityReports;

  PostTrainingCompleteRequest({
    required this.feedback,
    required this.activityFeedback,
    required this.activityReports,
  });

  factory PostTrainingCompleteRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingCompleteRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingCompleteRequestToJson(this);
}
