// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_share_training_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostShareTrainingResponse {
  @JsonKey(name: 'token', defaultValue: '')
  final String token;
  @JsonKey(name: 'url', defaultValue: '')
  final String url;

  PostShareTrainingResponse({
    required this.token,
    required this.url,
  });

  factory PostShareTrainingResponse.fromJson(Map<String, dynamic> json) => _$PostShareTrainingResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostShareTrainingResponseToJson(this);
}
