// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_user_update_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostUserUpdateRequest {
  @JsonKey(name: 'first_name', defaultValue: '')
  final String firstName;
  @JsonKey(name: 'last_name', defaultValue: '')
  final String lastName;
  @JsonKey(name: 'birthdate', defaultValue: '')
  final String birthdate;
  @JsonKey(name: 'gender', defaultValue: '')
  final String gender;
  @JsonKey(name: 'language', defaultValue: '')
  final String language;
  @JsonKey(name: 'height')
  final double height;
  @JsonKey(name: 'weight')
  final double weight;
  @JsonKey(name: 'data')
  final Map<String, dynamic> data;

  PostUserUpdateRequest({
    required this.firstName,
    required this.lastName,
    required this.birthdate,
    required this.gender,
    required this.language,
    required this.height,
    required this.weight,
    required this.data,
  });

  factory PostUserUpdateRequest.fromJson(Map<String, dynamic> json) => _$PostUserUpdateRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostUserUpdateRequestToJson(this);
}
