// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/profile.dart';

part 'post_user_update_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostUserUpdateResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;
  @JsonKey(name: 'profile')
  final Profile profile;

  PostUserUpdateResponse({
    required this.message,
    required this.profile,
  });

  factory PostUserUpdateResponse.fromJson(Map<String, dynamic> json) => _$PostUserUpdateResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostUserUpdateResponseToJson(this);
}
