// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_refine_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingRefineRequest {
  @JsonKey(name: 'critique', defaultValue: '')
  final String critique;

  PostTrainingRefineRequest({
    required this.critique,
  });

  factory PostTrainingRefineRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingRefineRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingRefineRequestToJson(this);
}
