// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_logout_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostLogoutRequest {
  @JsonKey(name: 'refresh_token', defaultValue: '')
  final String refreshToken;

  PostLogoutRequest({
    required this.refreshToken,
  });

  factory PostLogoutRequest.fromJson(Map<String, dynamic> json) => _$PostLogoutRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostLogoutRequestToJson(this);
}
