// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/gym.dart';

part 'post_gym_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostGymResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;
  @JsonKey(name: 'gym')
  final Gym gym;

  PostGymResponse({
    required this.message,
    required this.gym,
  });

  factory PostGymResponse.fromJson(Map<String, dynamic> json) => _$PostGymResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostGymResponseToJson(this);
}
