// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_copy_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingCopyRequest {
  @JsonKey(name: 'target', defaultValue: '')
  final String target;

  PostTrainingCopyRequest({
    required this.target,
  });

  factory PostTrainingCopyRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingCopyRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingCopyRequestToJson(this);
}
