// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_partner_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingPartnerRequest {
  @JsonKey(name: 'partner', defaultValue: '')
  final String partner;

  PostTrainingPartnerRequest({
    required this.partner,
  });

  factory PostTrainingPartnerRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingPartnerRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingPartnerRequestToJson(this);
}
