// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_refresh_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostRefreshRequest {
  @JsonKey(name: 'refresh_token', defaultValue: '')
  final String refreshToken;

  PostRefreshRequest({
    required this.refreshToken,
  });

  factory PostRefreshRequest.fromJson(Map<String, dynamic> json) => _$PostRefreshRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostRefreshRequestToJson(this);
}
