// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_login_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostLoginRequest {
  @JsonKey(name: 'email', defaultValue: '')
  final String email;
  @JsonKey(name: 'password', defaultValue: '')
  final String password;

  PostLoginRequest({
    required this.email,
    required this.password,
  });

  factory PostLoginRequest.fromJson(Map<String, dynamic> json) => _$PostLoginRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostLoginRequestToJson(this);
}
