// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_flow_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostFlowRequest {
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'muscles')
  final List<String>? muscles;
  @JsonKey(name: 'prompt')
  final String? prompt;

  PostFlowRequest({
    required this.duration,
    this.muscles,
    this.prompt,
  });

  factory PostFlowRequest.fromJson(Map<String, dynamic> json) => _$PostFlowRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostFlowRequestToJson(this);
}
