// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_gym_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostGymRequest {
  @JsonKey(name: 'name', defaultValue: '')
  final String name;
  @JsonKey(name: 'equipment', defaultValue: [])
  final List<String> equipment;
  @JsonKey(name: 'modifier_variants')
  final Map<String, dynamic>? modifierVariants;

  PostGymRequest({
    required this.name,
    required this.equipment,
    this.modifierVariants,
  });

  factory PostGymRequest.fromJson(Map<String, dynamic> json) => _$PostGymRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostGymRequestToJson(this);
}
