// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_partner_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingPartnerResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  PostTrainingPartnerResponse({
    required this.message,
  });

  factory PostTrainingPartnerResponse.fromJson(Map<String, dynamic> json) => _$PostTrainingPartnerResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingPartnerResponseToJson(this);
}
