// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_avatar_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostAvatarResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  PostAvatarResponse({
    required this.message,
  });

  factory PostAvatarResponse.fromJson(Map<String, dynamic> json) => _$PostAvatarResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostAvatarResponseToJson(this);
}
