// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_training_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingRequest {
  @JsonKey(name: 'duration')
  final int duration;
  @JsonKey(name: 'equipment', defaultValue: [])
  final List<String> equipment;
  @JsonKey(name: 'gym', defaultValue: '')
  final String gym;
  @JsonKey(name: 'prompt', defaultValue: '')
  final String prompt;
  @JsonKey(name: 'partners', defaultValue: [])
  final List<String> partners;
  @JsonKey(name: 'skipWarmupCooldown')
  final bool skipWarmupCooldown;
  @JsonKey(name: 'methodology', defaultValue: '')
  final String methodology;
  @JsonKey(name: 'goals', defaultValue: [])
  final List<String> goals;
  @JsonKey(name: 'muscles', defaultValue: [])
  final List<String> muscles;
  @JsonKey(name: 'freeText', defaultValue: '')
  final String freeText;

  PostTrainingRequest({
    required this.duration,
    required this.equipment,
    required this.gym,
    required this.prompt,
    required this.partners,
    required this.skipWarmupCooldown,
    required this.methodology,
    required this.goals,
    required this.muscles,
    required this.freeText,
  });

  factory PostTrainingRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingRequestToJson(this);
}
