// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/training.dart';

part 'post_training_complete_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingCompleteResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;
  @JsonKey(name: 'training')
  final Training training;

  PostTrainingCompleteResponse({
    required this.message,
    required this.training,
  });

  factory PostTrainingCompleteResponse.fromJson(Map<String, dynamic> json) => _$PostTrainingCompleteResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingCompleteResponseToJson(this);
}
