// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/training_feedback.dart';

part 'post_training_complete_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostTrainingCompleteRequest {
  @JsonKey(name: 'feedback')
  final TrainingFeedback feedback;
  @JsonKey(name: 'activityFeedback', defaultValue: {})
  final Map<String, String> activityFeedback;
  @JsonKey(name: 'activityReports', defaultValue: [])
  final List<String> activityReports;
  @JsonKey(name: 'completedIn')
  final int? completedIn;

  PostTrainingCompleteRequest({
    required this.feedback,
    required this.activityFeedback,
    required this.activityReports,
    this.completedIn,
  });

  factory PostTrainingCompleteRequest.fromJson(Map<String, dynamic> json) => _$PostTrainingCompleteRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostTrainingCompleteRequestToJson(this);
}
