// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_unregister_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostUnregisterResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  PostUnregisterResponse({
    required this.message,
  });

  factory PostUnregisterResponse.fromJson(Map<String, dynamic> json) => _$PostUnregisterResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostUnregisterResponseToJson(this);
}
