// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_flow_complete_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostFlowCompleteRequest {
  @JsonKey(name: 'completed_in')
  final int? completedIn;

  PostFlowCompleteRequest({
    this.completedIn,
  });

  factory PostFlowCompleteRequest.fromJson(Map<String, dynamic> json) => _$PostFlowCompleteRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostFlowCompleteRequestToJson(this);
}
