// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_refresh_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostRefreshResponse {
  @JsonKey(name: 'access_token', defaultValue: '')
  final String accessToken;
  @JsonKey(name: 'refresh_token', defaultValue: '')
  final String refreshToken;

  PostRefreshResponse({
    required this.accessToken,
    required this.refreshToken,
  });

  factory PostRefreshResponse.fromJson(Map<String, dynamic> json) => _$PostRefreshResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostRefreshResponseToJson(this);
}
