// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/flow_session.dart';

part 'post_flow_complete_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostFlowCompleteResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;
  @JsonKey(name: 'session')
  final FlowSession session;

  PostFlowCompleteResponse({
    required this.message,
    required this.session,
  });

  factory PostFlowCompleteResponse.fromJson(Map<String, dynamic> json) => _$PostFlowCompleteResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostFlowCompleteResponseToJson(this);
}
