// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_register_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PostRegisterResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;

  PostRegisterResponse({
    required this.message,
  });

  factory PostRegisterResponse.fromJson(Map<String, dynamic> json) => _$PostRegisterResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PostRegisterResponseToJson(this);
}
