// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'post_register_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PostRegisterRequest {
  @JsonKey(name: 'email', defaultValue: '')
  final String email;
  @JsonKey(name: 'password', defaultValue: '')
  final String password;

  PostRegisterRequest({
    required this.email,
    required this.password,
  });

  factory PostRegisterRequest.fromJson(Map<String, dynamic> json) => _$PostRegisterRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PostRegisterRequestToJson(this);
}
