// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'put_gym_request.g.dart';

@JsonSerializable(explicitToJson: true)
class PutGymRequest {
  @JsonKey(name: 'name')
  final String? name;
  @JsonKey(name: 'equipment')
  final List<String>? equipment;

  PutGymRequest({
    this.name,
    this.equipment,
  });

  factory PutGymRequest.fromJson(Map<String, dynamic> json) => _$PutGymRequestFromJson(json);

  Map<String, dynamic> toJson() => _$PutGymRequestToJson(this);
}
