// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';
import '../models/gym.dart';

part 'put_gym_response.g.dart';

@JsonSerializable(explicitToJson: true)
class PutGymResponse {
  @JsonKey(name: 'message', defaultValue: '')
  final String message;
  @JsonKey(name: 'gym')
  final Gym gym;

  PutGymResponse({
    required this.message,
    required this.gym,
  });

  factory PutGymResponse.fromJson(Map<String, dynamic> json) => _$PutGymResponseFromJson(json);

  Map<String, dynamic> toJson() => _$PutGymResponseToJson(this);
}
