// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by vigor/codegen

import 'package:json_annotation/json_annotation.dart';

part 'shared_training_owner.g.dart';

@JsonSerializable(explicitToJson: true)
class SharedTrainingOwner {
  @JsonKey(name: 'user_id', defaultValue: '')
  final String userId;
  @JsonKey(name: 'first_name', defaultValue: '')
  final String firstName;
  @JsonKey(name: 'last_name', defaultValue: '')
  final String lastName;

  SharedTrainingOwner({
    required this.userId,
    required this.firstName,
    required this.lastName,
  });

  factory SharedTrainingOwner.fromJson(Map<String, dynamic> json) => _$SharedTrainingOwnerFromJson(json);

  Map<String, dynamic> toJson() => _$SharedTrainingOwnerToJson(this);
}
