// Code generated by qtc from "gen_training_exercises.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "strings"

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeExercisesSystem(qw422016 *qt422016.Writer, skipWarmupCooldown bool, minWork int, maxWork int) {
	qw422016.N().S(`You are an exercise selection specialist. Pick exercises from the provided pools for a training session.

Output a JSON object with:
- exercises: array of {exercise_id, rationale, phase} where phase is "warmup", "work", or "cooldown"

Rules:
- Use only exercise IDs from the provided lists — never invent IDs
- Annotations in parentheses (weighted, timer-only, reps-only, recent) are metadata — not part of the ID
- For work exercises: cover the primary muscles with higher count, secondary muscles with 1-2 exercises
- Avoid exercises matching any contraindicated pattern
- Prefer favorite exercises when they fit
- Prefer non-recent exercises over recent ones for variety
- Avoid exercises listed in avoid_exercises
`)
	if !skipWarmupCooldown {
		qw422016.N().S(`- Include 3-4 warmup exercises and 4-6 cooldown exercises covering worked muscles`)
	}
	qw422016.N().S(`
- Select `)
	qw422016.N().D(minWork)
	qw422016.N().S(`-`)
	qw422016.N().D(maxWork)
	qw422016.N().S(` distinct work exercises (band scaled to methodology density and session duration)
- Keep rationale to 3-8 words per exercise
`)
}

func WriteNodeExercisesSystem(qq422016 qtio422016.Writer, skipWarmupCooldown bool, minWork int, maxWork int) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeExercisesSystem(qw422016, skipWarmupCooldown, minWork, maxWork)
	qt422016.ReleaseWriter(qw422016)
}

func NodeExercisesSystem(skipWarmupCooldown bool, minWork int, maxWork int) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeExercisesSystem(qb422016, skipWarmupCooldown, minWork, maxWork)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeExercisesUser(qw422016 *qt422016.Writer,
	methodology string,
	primaryMuscles []string,
	secondaryMuscles []string,
	contraindicatedPatterns []string,
	avoidExercises []string,
	workExercises []model.Exercise,
	warmupExercises []model.Exercise,
	cooldownExercises []model.Exercise,
	favoriteExercises []model.Exercise,
	recentExerciseIDs []string,
	calibrationFamilies []string,
	skipWarmupCooldown bool,
) {
	qw422016.N().S(`Methodology: `)
	qw422016.E().S(methodology)
	qw422016.N().S(`
Primary muscles: `)
	qw422016.E().S(strings.Join(primaryMuscles, ", "))
	qw422016.N().S(`
`)
	if len(secondaryMuscles) > 0 {
		qw422016.N().S(`Secondary muscles: `)
		qw422016.E().S(strings.Join(secondaryMuscles, ", "))
	}
	qw422016.N().S(`
`)
	if len(contraindicatedPatterns) > 0 {
		qw422016.N().S(`
Avoid these patterns: `)
		qw422016.E().S(strings.Join(contraindicatedPatterns, "; "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(avoidExercises) > 0 {
		qw422016.N().S(`
Avoid these exercises: `)
		qw422016.E().S(strings.Join(avoidExercises, ", "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(calibrationFamilies) > 0 {
		qw422016.N().S(`
Calibration priority — include exercises from: `)
		qw422016.E().S(strings.Join(calibrationFamilies, ", "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(favoriteExercises) > 0 {
		qw422016.N().S(`
Favorites: `)
		for i, ex := range favoriteExercises {
			qw422016.E().S(ex.ID)
			if i < len(favoriteExercises)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`

`)
	recentSet := make(map[string]bool, len(recentExerciseIDs))
	for _, id := range recentExerciseIDs {
		recentSet[id] = true
	}

	qw422016.N().S(`
`)
	if !skipWarmupCooldown {
		qw422016.N().S(`
[WARMUP] `)
		qw422016.N().D(len(warmupExercises))
		qw422016.N().S(` options
`)
		for _, exercise := range warmupExercises {
			qw422016.E().S(exercise.ID)
			qw422016.N().S(`, `)
		}
		qw422016.N().S(`

`)
	}
	qw422016.N().S(`
[WORK] `)
	qw422016.N().D(len(workExercises))
	qw422016.N().S(` options
`)
	workByMuscle := groupExercisesByMuscle(workExercises)

	for _, muscle := range workExerciseMuscleOrder(workExercises) {
		qw422016.E().S(muscle)
		qw422016.N().S(`: `)
		for i, ex := range workByMuscle[muscle] {
			qw422016.E().S(ex.ID)
			annotations := exerciseAnnotations(ex, recentSet)

			if annotations != "" {
				qw422016.N().S(` (`)
				qw422016.E().S(annotations)
				qw422016.N().S(`)`)
			}
			if i < len(workByMuscle[muscle])-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if !skipWarmupCooldown {
		qw422016.N().S(`
[COOLDOWN] `)
		qw422016.N().D(len(cooldownExercises))
		qw422016.N().S(` options
`)
		for i, exercise := range cooldownExercises {
			qw422016.E().S(exercise.ID)
			if len(exercise.Muscles) > 0 {
				qw422016.N().S(` (`)
				qw422016.E().S(exercise.Muscles[0])
				qw422016.N().S(`)`)
			}
			if i < len(cooldownExercises)-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeExercisesUser(qq422016 qtio422016.Writer,
	methodology string,
	primaryMuscles []string,
	secondaryMuscles []string,
	contraindicatedPatterns []string,
	avoidExercises []string,
	workExercises []model.Exercise,
	warmupExercises []model.Exercise,
	cooldownExercises []model.Exercise,
	favoriteExercises []model.Exercise,
	recentExerciseIDs []string,
	calibrationFamilies []string,
	skipWarmupCooldown bool,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeExercisesUser(qw422016, methodology, primaryMuscles, secondaryMuscles, contraindicatedPatterns, avoidExercises, workExercises, warmupExercises, cooldownExercises, favoriteExercises, recentExerciseIDs, calibrationFamilies, skipWarmupCooldown)
	qt422016.ReleaseWriter(qw422016)
}

func NodeExercisesUser(
	methodology string,
	primaryMuscles []string,
	secondaryMuscles []string,
	contraindicatedPatterns []string,
	avoidExercises []string,
	workExercises []model.Exercise,
	warmupExercises []model.Exercise,
	cooldownExercises []model.Exercise,
	favoriteExercises []model.Exercise,
	recentExerciseIDs []string,
	calibrationFamilies []string,
	skipWarmupCooldown bool,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeExercisesUser(qb422016, methodology, primaryMuscles, secondaryMuscles, contraindicatedPatterns, avoidExercises, workExercises, warmupExercises, cooldownExercises, favoriteExercises, recentExerciseIDs, calibrationFamilies, skipWarmupCooldown)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
