// Code generated by qtc from "gen_flow_reasoning.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamGenFlowReasoning(qw422016 *qt422016.Writer,
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) {
	qw422016.N().S(`Design a `)
	qw422016.N().D(duration)
	qw422016.N().S(`-minute flow session for mobility, recovery, and mindful movement.

Let's think step by step:

1. CONSTRAINTS: What injuries or limitations must I work around?
2. MUSCLE TARGETING: Which muscles need the most attention given the context?
3. POSE SELECTION: Which exercises from the pool best serve recovery for these muscles?
4. FLOW STRUCTURE: How should I sequence poses for a smooth, progressive flow?
5. CREATIVE TITLE: What evocative name captures the session's character?

`)
	if len(userPrompt) > 0 {
		qw422016.N().S(`
[USER REQUEST]
`)
		qw422016.E().S(userPrompt)
		qw422016.N().S(`

`)
	}
	qw422016.N().S(`
[TARGET MUSCLES]
`)
	if musclesFromRecent {
		qw422016.N().S(`Recently trained — prioritize these for recovery:
`)
	} else {
		qw422016.N().S(`Full body flow:
`)
	}
	qw422016.N().S(`
`)
	for i, m := range muscles {
		qw422016.E().S(m)
		if i < len(muscles)-1 {
			qw422016.N().S(`, `)
		}
	}
	qw422016.N().S(`

[PROFILE]
Age:`)
	qw422016.N().D(profile.Age())
	qw422016.N().S(` Height:`)
	qw422016.N().FPrec(profile.Height, 0)
	qw422016.N().S(`cm Weight:`)
	qw422016.N().FPrec(profile.Weight, 0)
	qw422016.N().S(`kg Gender:`)
	qw422016.E().S(profile.Gender)
	qw422016.N().S(`
`)
	if len(profile.Injuries()) > 0 {
		qw422016.N().S(`Injuries: `)
		for j, injury := range profile.Injuries() {
			qw422016.E().S(injury.Description)
			qw422016.N().S(`(`)
			qw422016.N().D(injury.Year)
			qw422016.N().S(`)`)
			if j < len(profile.Injuries())-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	if len(profile.Limitations()) > 0 {
		qw422016.N().S(`Limitations: `)
		for j, limitation := range profile.Limitations() {
			qw422016.E().S(limitation)
			if j < len(profile.Limitations())-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	if len(profile.Conditions()) > 0 {
		qw422016.N().S(`Conditions: `)
		for j, condition := range profile.Conditions() {
			qw422016.E().S(condition)
			if j < len(profile.Conditions())-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`

[EXERCISES] `)
	qw422016.N().D(len(exercises))
	qw422016.N().S(` options (id: name[primary_muscle])
`)
	for _, exercise := range exercises {
		qw422016.E().S(exercise.ID)
		qw422016.N().S(`: `)
		qw422016.E().S(exercise.Name)
		if len(exercise.Muscles) > 0 {
			qw422016.N().S(`[`)
			qw422016.E().S(exercise.Muscles[0])
			qw422016.N().S(`]`)
		}
		qw422016.N().S(`, `)
	}
	qw422016.N().S(`

`)
	if len(facts) > 0 {
		qw422016.N().S(`
[FACTS]
Apply when relevant to selected poses:
`)
		for i, fact := range facts {
			qw422016.N().S(`- [F`)
			qw422016.N().D(i)
			qw422016.N().S(`] `)
			qw422016.E().S(fact.Content)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
Output language: `)
	if len(profile.Language) > 0 {
		qw422016.E().S(profile.Language)
	} else {
		qw422016.N().S(`English`)
	}
	qw422016.N().S(`

[REMINDERS]
`)
	if len(profile.Injuries()) > 0 {
		qw422016.N().S(`- CRITICAL: avoid all poses contraindicated by injuries: `)
		for j, injury := range profile.Injuries() {
			qw422016.E().S(injury.Description)
			if j < len(profile.Injuries())-1 {
				qw422016.N().S(`, `)
			}
		}
		qw422016.N().S(`

`)
	}
	qw422016.N().S(`- TARGET: total session must be approximately `)
	qw422016.N().D(duration * 60)
	qw422016.N().S(` seconds (holds + transition rests combined)
- Hold durations: 10–60 seconds per pose (ACSM: 10–30s per hold, up to 60s for 2-rep equivalent in a single pass)
- Transition rest between poses: 5–15 seconds (not counted in hold time)
- Minimum 4 poses, maximum 40. Use enough poses to reach the target duration.
- This is a single continuous flow — no warmup/cooldown split
- Sequence from gentle mobilization to deeper stretches, ending with calming poses
- ONLY use exercise IDs from the [EXERCISES] list above — never invent IDs, variants, or suffixes
`)
}

func WriteGenFlowReasoning(qq422016 qtio422016.Writer,
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamGenFlowReasoning(qw422016, profile, muscles, musclesFromRecent, exercises, facts, userPrompt, duration)
	qt422016.ReleaseWriter(qw422016)
}

func GenFlowReasoning(
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteGenFlowReasoning(qb422016, profile, muscles, musclesFromRecent, exercises, facts, userPrompt, duration)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
