// Code generated by qtc from "gen_flow_reasoning.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/gen_flow_reasoning.qtpl:1
package prompt

//line llm/prompt/gen_flow_reasoning.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/prompt/gen_flow_reasoning.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/gen_flow_reasoning.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/gen_flow_reasoning.qtpl:5
func StreamGenFlowReasoning(qw422016 *qt422016.Writer,
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) {
//line llm/prompt/gen_flow_reasoning.qtpl:13
	qw422016.N().S(`Design a `)
//line llm/prompt/gen_flow_reasoning.qtpl:14
	qw422016.N().D(duration)
//line llm/prompt/gen_flow_reasoning.qtpl:14
	qw422016.N().S(`-minute flow session for mobility, recovery, and mindful movement.

Let's think step by step:

1. CONSTRAINTS: What injuries or limitations must I work around?
2. MUSCLE TARGETING: Which muscles need the most attention given the context?
3. POSE SELECTION: Which exercises from the pool best serve recovery for these muscles?
4. FLOW STRUCTURE: How should I sequence poses for a smooth, progressive flow?
5. CREATIVE TITLE: What evocative name captures the session's character?

`)
//line llm/prompt/gen_flow_reasoning.qtpl:24
	if len(userPrompt) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:24
		qw422016.N().S(`
[USER REQUEST]
`)
//line llm/prompt/gen_flow_reasoning.qtpl:26
		qw422016.E().S(userPrompt)
//line llm/prompt/gen_flow_reasoning.qtpl:26
		qw422016.N().S(`

`)
//line llm/prompt/gen_flow_reasoning.qtpl:28
	}
//line llm/prompt/gen_flow_reasoning.qtpl:28
	qw422016.N().S(`
[TARGET MUSCLES]
`)
//line llm/prompt/gen_flow_reasoning.qtpl:30
	if musclesFromRecent {
//line llm/prompt/gen_flow_reasoning.qtpl:30
		qw422016.N().S(`Recently trained — prioritize these for recovery:
`)
//line llm/prompt/gen_flow_reasoning.qtpl:31
	} else {
//line llm/prompt/gen_flow_reasoning.qtpl:31
		qw422016.N().S(`Full body flow:
`)
//line llm/prompt/gen_flow_reasoning.qtpl:32
	}
//line llm/prompt/gen_flow_reasoning.qtpl:32
	qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:33
	for i, m := range muscles {
//line llm/prompt/gen_flow_reasoning.qtpl:33
		qw422016.E().S(m)
//line llm/prompt/gen_flow_reasoning.qtpl:33
		if i < len(muscles)-1 {
//line llm/prompt/gen_flow_reasoning.qtpl:33
			qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:33
		}
//line llm/prompt/gen_flow_reasoning.qtpl:33
	}
//line llm/prompt/gen_flow_reasoning.qtpl:33
	qw422016.N().S(`

[PROFILE]
Age:`)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().D(profile.Age())
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().S(` Height:`)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().FPrec(profile.Height, 0)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().S(`cm Weight:`)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().FPrec(profile.Weight, 0)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().S(`kg Gender:`)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.E().S(profile.Gender)
//line llm/prompt/gen_flow_reasoning.qtpl:36
	qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:37
	if len(profile.Injuries()) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:37
		qw422016.N().S(`Injuries: `)
//line llm/prompt/gen_flow_reasoning.qtpl:37
		for j, injury := range profile.Injuries() {
//line llm/prompt/gen_flow_reasoning.qtpl:37
			qw422016.E().S(injury.Description)
//line llm/prompt/gen_flow_reasoning.qtpl:37
			qw422016.N().S(`(`)
//line llm/prompt/gen_flow_reasoning.qtpl:37
			qw422016.N().D(injury.Year)
//line llm/prompt/gen_flow_reasoning.qtpl:37
			qw422016.N().S(`)`)
//line llm/prompt/gen_flow_reasoning.qtpl:37
			if j < len(profile.Injuries())-1 {
//line llm/prompt/gen_flow_reasoning.qtpl:37
				qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:37
			}
//line llm/prompt/gen_flow_reasoning.qtpl:37
		}
//line llm/prompt/gen_flow_reasoning.qtpl:37
		qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:38
	}
//line llm/prompt/gen_flow_reasoning.qtpl:38
	if len(profile.Limitations()) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:38
		qw422016.N().S(`Limitations: `)
//line llm/prompt/gen_flow_reasoning.qtpl:38
		for j, limitation := range profile.Limitations() {
//line llm/prompt/gen_flow_reasoning.qtpl:38
			qw422016.E().S(limitation)
//line llm/prompt/gen_flow_reasoning.qtpl:38
			if j < len(profile.Limitations())-1 {
//line llm/prompt/gen_flow_reasoning.qtpl:38
				qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:38
			}
//line llm/prompt/gen_flow_reasoning.qtpl:38
		}
//line llm/prompt/gen_flow_reasoning.qtpl:38
		qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:39
	}
//line llm/prompt/gen_flow_reasoning.qtpl:39
	if len(profile.Conditions()) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:39
		qw422016.N().S(`Conditions: `)
//line llm/prompt/gen_flow_reasoning.qtpl:39
		for j, condition := range profile.Conditions() {
//line llm/prompt/gen_flow_reasoning.qtpl:39
			qw422016.E().S(condition)
//line llm/prompt/gen_flow_reasoning.qtpl:39
			if j < len(profile.Conditions())-1 {
//line llm/prompt/gen_flow_reasoning.qtpl:39
				qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:39
			}
//line llm/prompt/gen_flow_reasoning.qtpl:39
		}
//line llm/prompt/gen_flow_reasoning.qtpl:39
		qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:40
	}
//line llm/prompt/gen_flow_reasoning.qtpl:40
	qw422016.N().S(`

[EXERCISES] `)
//line llm/prompt/gen_flow_reasoning.qtpl:42
	qw422016.N().D(len(exercises))
//line llm/prompt/gen_flow_reasoning.qtpl:42
	qw422016.N().S(` options (id: name[primary_muscle])
`)
//line llm/prompt/gen_flow_reasoning.qtpl:43
	for _, exercise := range exercises {
//line llm/prompt/gen_flow_reasoning.qtpl:43
		qw422016.E().S(exercise.ID)
//line llm/prompt/gen_flow_reasoning.qtpl:43
		qw422016.N().S(`: `)
//line llm/prompt/gen_flow_reasoning.qtpl:43
		qw422016.E().S(exercise.Name)
//line llm/prompt/gen_flow_reasoning.qtpl:43
		if len(exercise.Muscles) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:43
			qw422016.N().S(`[`)
//line llm/prompt/gen_flow_reasoning.qtpl:43
			qw422016.E().S(exercise.Muscles[0])
//line llm/prompt/gen_flow_reasoning.qtpl:43
			qw422016.N().S(`]`)
//line llm/prompt/gen_flow_reasoning.qtpl:43
		}
//line llm/prompt/gen_flow_reasoning.qtpl:43
		qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:43
	}
//line llm/prompt/gen_flow_reasoning.qtpl:43
	qw422016.N().S(`

`)
//line llm/prompt/gen_flow_reasoning.qtpl:45
	if len(facts) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:45
		qw422016.N().S(`
[FACTS]
Apply when relevant to selected poses:
`)
//line llm/prompt/gen_flow_reasoning.qtpl:48
		for i, fact := range facts {
//line llm/prompt/gen_flow_reasoning.qtpl:48
			qw422016.N().S(`- [F`)
//line llm/prompt/gen_flow_reasoning.qtpl:48
			qw422016.N().D(i)
//line llm/prompt/gen_flow_reasoning.qtpl:48
			qw422016.N().S(`] `)
//line llm/prompt/gen_flow_reasoning.qtpl:48
			qw422016.E().S(fact.Content)
//line llm/prompt/gen_flow_reasoning.qtpl:48
			qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:49
		}
//line llm/prompt/gen_flow_reasoning.qtpl:49
		qw422016.N().S(`
`)
//line llm/prompt/gen_flow_reasoning.qtpl:50
	}
//line llm/prompt/gen_flow_reasoning.qtpl:50
	qw422016.N().S(`
Output language: `)
//line llm/prompt/gen_flow_reasoning.qtpl:51
	if len(profile.Language) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:51
		qw422016.E().S(profile.Language)
//line llm/prompt/gen_flow_reasoning.qtpl:51
	} else {
//line llm/prompt/gen_flow_reasoning.qtpl:51
		qw422016.N().S(`English`)
//line llm/prompt/gen_flow_reasoning.qtpl:51
	}
//line llm/prompt/gen_flow_reasoning.qtpl:51
	qw422016.N().S(`

[REMINDERS]
`)
//line llm/prompt/gen_flow_reasoning.qtpl:54
	if len(profile.Injuries()) > 0 {
//line llm/prompt/gen_flow_reasoning.qtpl:54
		qw422016.N().S(`- CRITICAL: avoid all poses contraindicated by injuries: `)
//line llm/prompt/gen_flow_reasoning.qtpl:54
		for j, injury := range profile.Injuries() {
//line llm/prompt/gen_flow_reasoning.qtpl:54
			qw422016.E().S(injury.Description)
//line llm/prompt/gen_flow_reasoning.qtpl:54
			if j < len(profile.Injuries())-1 {
//line llm/prompt/gen_flow_reasoning.qtpl:54
				qw422016.N().S(`, `)
//line llm/prompt/gen_flow_reasoning.qtpl:54
			}
//line llm/prompt/gen_flow_reasoning.qtpl:54
		}
//line llm/prompt/gen_flow_reasoning.qtpl:54
		qw422016.N().S(`

`)
//line llm/prompt/gen_flow_reasoning.qtpl:56
	}
//line llm/prompt/gen_flow_reasoning.qtpl:56
	qw422016.N().S(`- TARGET: total session must be approximately `)
//line llm/prompt/gen_flow_reasoning.qtpl:56
	qw422016.N().D(duration * 60)
//line llm/prompt/gen_flow_reasoning.qtpl:56
	qw422016.N().S(` seconds (holds + transition rests combined)
- Hold durations: 10–60 seconds per pose (ACSM: 10–30s per hold, up to 60s for 2-rep equivalent in a single pass)
- Transition rest between poses: 5–15 seconds (not counted in hold time)
- Minimum 4 poses, maximum 40. Use enough poses to reach the target duration.
- This is a single continuous flow — no warmup/cooldown split
- Sequence from gentle mobilization to deeper stretches, ending with calming poses
- ONLY use exercise IDs from the [EXERCISES] list above — never invent IDs, variants, or suffixes
`)
//line llm/prompt/gen_flow_reasoning.qtpl:63
}

//line llm/prompt/gen_flow_reasoning.qtpl:63
func WriteGenFlowReasoning(qq422016 qtio422016.Writer,
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) {
//line llm/prompt/gen_flow_reasoning.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/gen_flow_reasoning.qtpl:63
	StreamGenFlowReasoning(qw422016, profile, muscles, musclesFromRecent, exercises, facts, userPrompt, duration)
//line llm/prompt/gen_flow_reasoning.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/gen_flow_reasoning.qtpl:63
}

//line llm/prompt/gen_flow_reasoning.qtpl:63
func GenFlowReasoning(
	profile model.Profile,
	muscles []string,
	musclesFromRecent bool,
	exercises []model.Exercise,
	facts []model.Fact,
	userPrompt string,
	duration int,
) string {
//line llm/prompt/gen_flow_reasoning.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/gen_flow_reasoning.qtpl:63
	WriteGenFlowReasoning(qb422016, profile, muscles, musclesFromRecent, exercises, facts, userPrompt, duration)
//line llm/prompt/gen_flow_reasoning.qtpl:63
	qs422016 := string(qb422016.B)
//line llm/prompt/gen_flow_reasoning.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/gen_flow_reasoning.qtpl:63
	return qs422016
//line llm/prompt/gen_flow_reasoning.qtpl:63
}
