// Code generated by qtc from "gen_training_muscles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "fmt"
import "sort"
import "strings"
import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeMusclesSystem(qw422016 *qt422016.Writer, availableMuscles []string, hasExplicit bool) {
	qw422016.N().S(`You are a muscle targeting strategist. Decide primary, secondary muscle groups and their distribution for a training session.

Output a JSON object with:
- primary: array of muscle groups for high-volume emphasis (1-4)
- secondary: array of muscle groups for maintenance volume (0-4)
- distribution: map from muscle name to float 0.0-1.0 (sum should be ~1.0, represents training volume share)
- reasoning: one sentence explaining why these muscles were chosen
- summary: one-sentence plain-language summary of the muscle targeting (e.g. "focuses on pushing muscles with some back and shoulder support"), written conversationally

`)
	if len(availableMuscles) > 0 {
		qw422016.N().S(`
Available muscles with the current equipment (muscle: exercise count):
`)
		muscles := make([]string, 0, len(availableMuscles))
		for _, m := range availableMuscles {
			muscles = append(muscles, m)
		}
		sort.Strings(muscles)

		for _, m := range muscles {
			qw422016.N().S(`- `)
			qw422016.E().S(m)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
primary and secondary MUST use only muscle names from the list above — never invent finer-grained names (e.g. "lats", "rhomboids", "hamstrings"); use the coarse names shown. primary MUST have a non-zero exercise count — never nominate a muscle the equipment can't train.
`)
	} else {
		qw422016.N().S(`
Available muscle groups: chest, back, legs, arms, shoulders, core, glutes, full_body. Use coarse names only.
`)
	}
	qw422016.N().S(`
`)
	if hasExplicit {
		qw422016.N().S(`
User has explicitly requested specific muscles — you MUST respect them: primary MUST be a subset of the explicit list, and secondary should complement or be empty. Do not add unrelated muscles as primary.
`)
	}
	qw422016.N().S(`
Rules:
- Prefer primary muscles aligned with goals and user request
- Distribution keys must be from primary ∪ secondary, values 0.05-0.8, sum 1.0 (±0.05)
- If no explicit muscles and no clear goal, default to a balanced full-body distribution
- Keep reasoning concise (one sentence)
`)
}

func WriteNodeMusclesSystem(qq422016 qtio422016.Writer, availableMuscles []string, hasExplicit bool) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeMusclesSystem(qw422016, availableMuscles, hasExplicit)
	qt422016.ReleaseWriter(qw422016)
}

func NodeMusclesSystem(availableMuscles []string, hasExplicit bool) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeMusclesSystem(qb422016, availableMuscles, hasExplicit)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeMusclesUser(qw422016 *qt422016.Writer,
	goals []model.Goal,
	explicitMuscles []string,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	recentMuscleFrequency map[string]int,
) {
	qw422016.N().S(`Duration: `)
	qw422016.N().D(duration)
	qw422016.N().S(` minutes

`)
	if len(explicitMuscles) > 0 {
		qw422016.N().S(`
Explicit muscle request: `)
		qw422016.E().S(strings.Join(explicitMuscles, ", "))
		qw422016.N().S(`
If explicit muscles were provided, use them as primary. You may add 0-2 complementary secondary muscles only if they naturally support the movement.
`)
	} else {
		qw422016.N().S(`
No explicit muscle request — infer from goals, history, and user prompt.
`)
	}
	qw422016.N().S(`
`)
	if len(goals) > 0 {
		qw422016.N().S(`
Goals:
`)
		for _, goal := range goals {
			qw422016.N().S(`- `)
			qw422016.E().S(goal.ID)
			qw422016.N().S(`: `)
			qw422016.E().S(goal.Description)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if healthVolumeModifier < 1.0 || healthIntensityModifier < 1.0 {
		qw422016.N().S(`
Recovery: volume at `)
		qw422016.E().S(fmt.Sprintf("%.0f%%", healthVolumeModifier*100))
		qw422016.N().S(`, intensity at `)
		qw422016.E().S(fmt.Sprintf("%.0f%%", healthIntensityModifier*100))
		qw422016.N().S(`. `)
		qw422016.E().S(healthRationale)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if historyPatternNotes != "" {
		qw422016.N().S(`History pattern: `)
		qw422016.E().S(historyPatternNotes)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if historyBadSessionNotes != "" {
		qw422016.N().S(`Recent issue: `)
		qw422016.E().S(historyBadSessionNotes)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if userPrompt != "" {
		qw422016.N().S(`User request: `)
		qw422016.E().S(userPrompt)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(recentMuscleFrequency) > 0 {
		qw422016.N().S(`
Recent muscle frequency (last 14 days, to balance):
`)
		for muscle, count := range recentMuscleFrequency {
			qw422016.N().S(`- `)
			qw422016.E().S(muscle)
			qw422016.N().S(`: `)
			qw422016.N().D(count)
			qw422016.N().S(` times
`)
		}
	}
	qw422016.N().S(`
`)
}

func WriteNodeMusclesUser(qq422016 qtio422016.Writer,
	goals []model.Goal,
	explicitMuscles []string,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	recentMuscleFrequency map[string]int,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeMusclesUser(qw422016, goals, explicitMuscles, healthVolumeModifier, healthIntensityModifier, healthRationale, historyPatternNotes, historyBadSessionNotes, userPrompt, duration, recentMuscleFrequency)
	qt422016.ReleaseWriter(qw422016)
}

func NodeMusclesUser(
	goals []model.Goal,
	explicitMuscles []string,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	recentMuscleFrequency map[string]int,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeMusclesUser(qb422016, goals, explicitMuscles, healthVolumeModifier, healthIntensityModifier, healthRationale, historyPatternNotes, historyBadSessionNotes, userPrompt, duration, recentMuscleFrequency)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
