// Code generated by qtc from "gen_training_structuring.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/gen_training_structuring.qtpl:1
package prompt

//line llm/prompt/gen_training_structuring.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/gen_training_structuring.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/gen_training_structuring.qtpl:3
func StreamGenTrainingStructuring(qw422016 *qt422016.Writer, reasoningOutput string) {
//line llm/prompt/gen_training_structuring.qtpl:3
	qw422016.N().S(`Extract the training program from the reasoning below into the provided JSON schema.
Use exercise IDs (not names) for exercise_id fields. Map [FN] markers to the fact_indices array.

`)
//line llm/prompt/gen_training_structuring.qtpl:7
	qw422016.E().S(reasoningOutput)
//line llm/prompt/gen_training_structuring.qtpl:7
	qw422016.N().S(`
`)
//line llm/prompt/gen_training_structuring.qtpl:8
}

//line llm/prompt/gen_training_structuring.qtpl:8
func WriteGenTrainingStructuring(qq422016 qtio422016.Writer, reasoningOutput string) {
//line llm/prompt/gen_training_structuring.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/gen_training_structuring.qtpl:8
	StreamGenTrainingStructuring(qw422016, reasoningOutput)
//line llm/prompt/gen_training_structuring.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/gen_training_structuring.qtpl:8
}

//line llm/prompt/gen_training_structuring.qtpl:8
func GenTrainingStructuring(reasoningOutput string) string {
//line llm/prompt/gen_training_structuring.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/gen_training_structuring.qtpl:8
	WriteGenTrainingStructuring(qb422016, reasoningOutput)
//line llm/prompt/gen_training_structuring.qtpl:8
	qs422016 := string(qb422016.B)
//line llm/prompt/gen_training_structuring.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/gen_training_structuring.qtpl:8
	return qs422016
//line llm/prompt/gen_training_structuring.qtpl:8
}
