// Code generated by qtc from "gen_training_derive.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeDeriveParamsUser(qw422016 *qt422016.Writer, freeText string, articles []string) {
	qw422016.N().S(`REQUEST: `)
	qw422016.E().S(freeText)
	qw422016.N().S(`
`)
	for i, article := range articles {
		qw422016.N().S(`
[ARTICLE `)
		qw422016.N().D(i + 1)
		qw422016.N().S(`]
`)
		qw422016.E().S(article)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeDeriveParamsUser(qq422016 qtio422016.Writer, freeText string, articles []string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeDeriveParamsUser(qw422016, freeText, articles)
	qt422016.ReleaseWriter(qw422016)
}

func NodeDeriveParamsUser(freeText string, articles []string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeDeriveParamsUser(qb422016, freeText, articles)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
