// Code generated by qtc from "gen_training_health.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeHealthSystem(qw422016 *qt422016.Writer) {
	qw422016.N().S(`You are a recovery analyst. Given a user's health snapshot, determine how training volume and intensity should be adjusted.

Output a JSON object with:
- volume_modifier: float 0.0-1.0 (1.0 = full volume, 0.7 = 30% reduction)
- intensity_modifier: float 0.0-1.0 (1.0 = full intensity)
- extend_warmup: boolean
- rationale: one sentence explaining your reasoning (internal, not shown to user)

Rules:
- Sleep deviation <= -15%: reduce volume proportionally
- HRV deviation <= -15%: reduce both volume and intensity
- RHR deviation >= +15%: reduce intensity
- Low step count vs baseline: extend warmup
- External workouts in last 48h: reduce volume for overlapping muscle groups
- Multiple negative deviations compound: reduce more aggressively
- Extreme values (sleep < 5h, HRV < 15ms RMSSD): significant reduction regardless of baseline
- If baselines not established (< 7 days): only apply extreme-value rules
- Negligible deviations: return 1.0 for both modifiers
- Only reason about metrics explicitly listed below. A metric that is absent was NOT measured — never treat a missing metric as a low or extreme value, and never reduce because of it.
`)
}

func WriteNodeHealthSystem(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeHealthSystem(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func NodeHealthSystem() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeHealthSystem(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeHealthUser(qw422016 *qt422016.Writer, healthSnapshot *model.HealthSnapshot) {
	if healthSnapshot == nil || !healthSnapshot.HasRecoverySignal() {
		qw422016.N().S(`No recovery metrics available. Return volume_modifier=1.0, intensity_modifier=1.0, extend_warmup=false, rationale="no data".
`)
	} else {
		qw422016.N().S(`
`)
		if healthSnapshot.SleepPresent {
			qw422016.N().S(`Sleep: `)
			qw422016.N().FPrec(healthSnapshot.SleepHours, 1)
			qw422016.N().S(`h (baseline: `)
			qw422016.N().FPrec(healthSnapshot.SleepBaseline, 1)
			qw422016.N().S(`h, deviation: `)
			qw422016.E().S(formatDeviation(healthSnapshot.SleepDeviation))
			qw422016.N().S(`)
  Deep: `)
			qw422016.N().FPrec(healthSnapshot.SleepDeepHours, 1)
			qw422016.N().S(`h, Light: `)
			qw422016.N().FPrec(healthSnapshot.SleepLightHours, 1)
			qw422016.N().S(`h, REM: `)
			qw422016.N().FPrec(healthSnapshot.SleepREMHours, 1)
			qw422016.N().S(`h
`)
		}
		qw422016.N().S(`
`)
		if healthSnapshot.HRVPresent {
			qw422016.N().S(`HRV: `)
			qw422016.N().FPrec(healthSnapshot.HRVRMSSD, 0)
			qw422016.N().S(`ms RMSSD (baseline: `)
			qw422016.N().FPrec(healthSnapshot.HRVBaseline, 0)
			qw422016.N().S(`ms, deviation: `)
			qw422016.E().S(formatDeviation(healthSnapshot.HRVDeviation))
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
		if healthSnapshot.RHRPresent {
			qw422016.N().S(`RHR: `)
			qw422016.N().D(healthSnapshot.RestingHR)
			qw422016.N().S(`bpm (baseline: `)
			qw422016.N().FPrec(healthSnapshot.RHRBaseline, 0)
			qw422016.N().S(`bpm, deviation: `)
			qw422016.E().S(formatDeviation(healthSnapshot.RHRDeviation))
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
		if healthSnapshot.StepsPresent {
			qw422016.N().S(`Steps yesterday: `)
			qw422016.E().S(formatNumber(healthSnapshot.Steps))
			qw422016.N().S(` (baseline: `)
			qw422016.E().S(formatNumber(int(healthSnapshot.StepsBaseline)))
			qw422016.N().S(`, deviation: `)
			qw422016.E().S(formatDeviation(healthSnapshot.StepsDeviation))
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
		if len(healthSnapshot.ExternalWorkouts) > 0 {
			qw422016.N().S(`External workouts (last 3 days):
`)
			for _, w := range healthSnapshot.ExternalWorkouts {
				qw422016.N().S(`  - `)
				qw422016.N().D(w.DaysAgo)
				qw422016.N().S(` day`)
				if w.DaysAgo != 1 {
					qw422016.N().S(`s`)
				}
				qw422016.N().S(` ago: `)
				qw422016.E().S(w.ExerciseType)
				qw422016.N().S(`, `)
				qw422016.N().D(w.DurationMins)
				qw422016.N().S(`min
`)
			}
		}
		qw422016.N().S(`
`)
		if healthSnapshot.BaselineDays >= 7 {
			qw422016.N().S(`Baselines from `)
			qw422016.N().D(healthSnapshot.BaselineDays)
			qw422016.N().S(`-day rolling averages.
`)
		} else {
			qw422016.N().S(`Baselines not established (`)
			qw422016.N().D(healthSnapshot.BaselineDays)
			qw422016.N().S(`/7 days) — extreme-value rules only.
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeHealthUser(qq422016 qtio422016.Writer, healthSnapshot *model.HealthSnapshot) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeHealthUser(qw422016, healthSnapshot)
	qt422016.ReleaseWriter(qw422016)
}

func NodeHealthUser(healthSnapshot *model.HealthSnapshot) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeHealthUser(qb422016, healthSnapshot)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
