// Code generated by qtc from "gen_training_creative.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "strings"

import "github.com/streambinder/vigor/llm/pipeline"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeCreativeSystem(qw422016 *qt422016.Writer, language string) {
	qw422016.N().S(`You are a copywriter for a fitness app. Write a training session title and description.
All output must be in `)
	qw422016.E().S(language)
	qw422016.N().S(`.

Output a JSON object with:
- name: string (3-4 memorable words)
- description: string (3-5 sentences)

Title rules:
- Reflect workout character (intensity, focus, energy)
- Action words, alliteration, or evocative phrases
- Match methodology tone: strength=powerful, circuit/HIIT=fast, mobility=flowing
- Never use: all caps, methodology names, goal lists, generic terms ("training", "workout")
- Never reuse names from the recent names list

Description rules:
- Read the `)
	qw422016.N().S("`")
	qw422016.N().S(`summary`)
	qw422016.N().S("`")
	qw422016.N().S(` field from each pipeline step below and weave them into a cohesive 3-5 sentence narrative
- Every sentence should map to a pipeline step — cover all 7 steps: recovery/health assessment, history-based progression, movement constraints, methodology choice, muscle targeting, exercise selection, and programming approach
- Always name the session's muscle targets explicitly, as a deliberate choice grounded in the user's data (requested muscles, constraints, recovery, history) — never leave them implied by the exercise list alone
- If muscles to rest are listed, mention what was deliberately left to recover and why
- If a step's summary is empty or states "no adjustment"/"no change", skip it naturally — do NOT invent coverage
- Write conversationally, as if explaining the workout to the user
- Do NOT use raw data labels like "too_easy", "too_hard", or technical metric names
- If constraints apply, mention what was worked around in a positive, practical way
- If exercises set aside during selection are listed, weave at most one or two notable ones into the selection sentence (what was left out and why) — never list them mechanically, and mention none when the list is empty
- If recovery was adjusted, mention the rationale without naming metrics
- If no warmup/cooldown, skip structural mentions of them
- The user should feel that every decision made during generation was based on their data

`)
}

func WriteNodeCreativeSystem(qq422016 qtio422016.Writer, language string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeCreativeSystem(qw422016, language)
	qt422016.ReleaseWriter(qw422016)
}

func NodeCreativeSystem(language string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeCreativeSystem(qb422016, language)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeCreativeUser(qw422016 *qt422016.Writer,
	strategy pipeline.Strategy,
	targeting pipeline.MuscleTargeting,
	exercises pipeline.ExerciseSelection,
	history pipeline.HistoryAnalysis,
	constraints pipeline.ConstraintExtraction,
	loadResult pipeline.LoadProgramming,
	health pipeline.HealthAssessment,
	recentNames []string,
) {
	qw422016.N().S(`Methodology: `)
	qw422016.E().S(strategy.Methodology)
	qw422016.N().S(`
Focus: `)
	qw422016.E().S(strings.Join(targeting.PrimaryMuscles, ", "))
	qw422016.N().S(`
`)
	if len(targeting.SecondaryMuscles) > 0 {
		qw422016.N().S(`
Secondary muscles: `)
		qw422016.E().S(strings.Join(targeting.SecondaryMuscles, ", "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(targeting.AvoidMuscles) > 0 {
		qw422016.N().S(`
Muscles to rest: `)
		qw422016.E().S(strings.Join(targeting.AvoidMuscles, ", "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`

Exercises:
`)
	for _, ex := range exercises.Exercises {
		if ex.Phase == "work" {
			qw422016.N().S(`- `)
			qw422016.E().S(ex.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(ex.Rationale)
			qw422016.N().S(`
`)
		}
	}
	qw422016.N().S(`
`)
	if len(exercises.Excluded) > 0 {
		qw422016.N().S(`
Set aside during selection:
`)
		for _, ex := range exercises.Excluded {
			qw422016.N().S(`- `)
			qw422016.E().S(ex.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(ex.Reason)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`

`)
	if len(history.Progressions) > 0 {
		qw422016.N().S(`
Progression decisions:
`)
		for _, p := range history.Progressions {
			qw422016.N().S(`- `)
			qw422016.E().S(p.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(p.Action)
			qw422016.N().S(` (`)
			qw422016.E().S(p.Signal)
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(constraints.ContraindicatedPatterns) > 0 || len(constraints.Accommodations) > 0 {
		qw422016.N().S(`
Contraindications:
`)
		if len(constraints.ContraindicatedPatterns) > 0 {
			qw422016.N().S(`Patterns to avoid: `)
			qw422016.E().S(strings.Join(constraints.ContraindicatedPatterns, ", "))
			qw422016.N().S(`
`)
		}
		if len(constraints.Accommodations) > 0 {
			qw422016.N().S(`Accommodations applied: `)
			qw422016.E().S(strings.Join(constraints.Accommodations, ", "))
			qw422016.N().S(`
`)
		}
	}
	qw422016.N().S(`
`)
	recoveryApplied := health.VolumeModifier < 1.0 || health.IntensityModifier < 1.0 || health.ExtendWarmup

	qw422016.N().S(`
`)
	if recoveryApplied {
		qw422016.N().S(`Recovery adjustment applied — volume at `)
		qw422016.N().D(int(health.VolumeModifier * 100))
		qw422016.N().S(`%, intensity at `)
		qw422016.N().D(int(health.IntensityModifier * 100))
		qw422016.N().S(`%`)
		if health.ExtendWarmup {
			qw422016.N().S(`, extended warmup`)
		}
		qw422016.N().S(`.
`)
	} else {
		qw422016.N().S(`No recovery adjustment was applied.
`)
	}
	qw422016.N().S(`
`)
	if len(loadResult.Routines) > 0 {
		qw422016.N().S(`
Routine structure:
`)
		for _, r := range loadResult.Routines {
			qw422016.N().S(`- `)
			qw422016.E().S(r.Type)
			qw422016.N().S(`: `)
			qw422016.N().D(len(r.Blocks))
			qw422016.N().S(` block(s), `)
			qw422016.N().D(r.Rest)
			qw422016.N().S(`s rest between blocks`)
			if r.Rest > 0 {
				qw422016.N().S(`, `)
				qw422016.N().D(r.Rest)
				qw422016.N().S(`s rest after routine`)
			}
			qw422016.N().S(`}
`)
		}
	}
	qw422016.N().S(`
`)
	if history.BadSessionNotes != "" {
		qw422016.N().S(`
Recent issue: `)
		qw422016.E().S(history.BadSessionNotes)
	}
	qw422016.N().S(`
`)
	if len(recentNames) > 0 {
		qw422016.N().S(`
Do not reuse these names: `)
		qw422016.E().S(strings.Join(recentNames, ", "))
	}
	qw422016.N().S(`
`)
}

func WriteNodeCreativeUser(qq422016 qtio422016.Writer,
	strategy pipeline.Strategy,
	targeting pipeline.MuscleTargeting,
	exercises pipeline.ExerciseSelection,
	history pipeline.HistoryAnalysis,
	constraints pipeline.ConstraintExtraction,
	loadResult pipeline.LoadProgramming,
	health pipeline.HealthAssessment,
	recentNames []string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeCreativeUser(qw422016, strategy, targeting, exercises, history, constraints, loadResult, health, recentNames)
	qt422016.ReleaseWriter(qw422016)
}

func NodeCreativeUser(
	strategy pipeline.Strategy,
	targeting pipeline.MuscleTargeting,
	exercises pipeline.ExerciseSelection,
	history pipeline.HistoryAnalysis,
	constraints pipeline.ConstraintExtraction,
	loadResult pipeline.LoadProgramming,
	health pipeline.HealthAssessment,
	recentNames []string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeCreativeUser(qb422016, strategy, targeting, exercises, history, constraints, loadResult, health, recentNames)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
