// Code generated by qtc from "gen_training_load.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "fmt"

import "strings"

import "github.com/streambinder/vigor/model"

import "github.com/streambinder/vigor/llm/pipeline"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeLoadSystem(qw422016 *qt422016.Writer, methodology *model.Methodology, hasModifiers bool, hasModifierVariants bool) {
	qw422016.N().S(`You are a strength & conditioning programmer. Given selected exercises and context, assign exact reps/duration, weight, rest, modifiers, and block structure.

Output a JSON object with:
- routines: array of {type, blocks: [{activities: [{exercise_id, reps, duration, weight_kg, rest, modifiers}], repeats, rest}], rest}
- fact_indices: array of integer indices referencing [FACTS] used (empty array if none)

Produce one routine per phase present in the exercise list (warmup, work, cooldown). Routine type must be one of "warmup", "work", "cooldown" — never the methodology name.

Rules:
- Each activity: exactly one of reps or duration > 0, never both
- "timer-only" exercises use duration in seconds, never reps
- "reps-only" exercises use reps count, never duration
- Exercises without a mode annotation: pick reps or duration based on methodology
- "weighted" exercises require weight_kg > 0
- weight_kg: 0 for bodyweight, > 0 for weighted equipment`)
	if hasModifiers {
		qw422016.N().S(` or weighted modifiers`)
	}
	qw422016.N().S(`
`)
	if hasModifierVariants {
		qw422016.N().S(`- For modifiers with listed weight variants, use only those values`)
	}
	qw422016.N().S(`
- modifiers: only IDs from the [MODIFIERS] list — never invent modifiers or use instructions like "per side", "each side", "slow tempo" as modifier IDs
- Duration is adjusted server-side by scaling block repeats — focus on structure quality

Methodology: `)
	qw422016.E().S(methodology.ID)
	qw422016.N().S(`
`)
	qw422016.E().S(methodology.Description)
	qw422016.N().S(`

`)
	if hasModifiers {
		qw422016.N().S(`
Modifiers: add modifier IDs to activities to push intensity. Triggers: "too_easy" feedback, progressive overload. Never add if feedback shows "too_hard". Never invent modifier IDs.
`)
	}
	qw422016.N().S(`

Progression adjustments:
- "increase_weight": bump weight_kg from the from_weight value
- "decrease_weight" / "decrease_reps": reduce load
- "add_modifier": attach the appropriate modifier ID
`)
}

func WriteNodeLoadSystem(qq422016 qtio422016.Writer, methodology *model.Methodology, hasModifiers bool, hasModifierVariants bool) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeLoadSystem(qw422016, methodology, hasModifiers, hasModifierVariants)
	qt422016.ReleaseWriter(qw422016)
}

func NodeLoadSystem(methodology *model.Methodology, hasModifiers bool, hasModifierVariants bool) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeLoadSystem(qb422016, methodology, hasModifiers, hasModifierVariants)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeLoadUser(qw422016 *qt422016.Writer,
	exercises []pipeline.SelectedExercise,
	exerciseModes map[string]string,
	weightedExercises map[string]bool,
	progressions []pipeline.ProgressionSignal,
	volumeTarget string,
	intensityTarget string,
	modifiers []model.Modifier,
	modifierVariants map[string][]float64,
	facts []model.Fact,
	equipmentIDs []string,
	favoriteEquipmentIDs []string,
	skipWarmupCooldown bool,
	duration int,
) {
	qw422016.N().S(`Duration: `)
	qw422016.N().D(duration)
	qw422016.N().S(` minutes. Volume: `)
	qw422016.E().S(volumeTarget)
	qw422016.N().S(`. Intensity: `)
	qw422016.E().S(intensityTarget)
	qw422016.N().S(`.

Exercises to program:
`)
	for _, ex := range exercises {
		mode := exerciseModes[ex.ExerciseID]

		qw422016.N().S(`- `)
		qw422016.E().S(ex.ExerciseID)
		qw422016.N().S(` (`)
		qw422016.E().S(ex.Phase)
		if mode == "duration" {
			qw422016.N().S(`, timer-only`)
		}
		if mode == "reps" {
			qw422016.N().S(`, reps-only`)
		}
		if weightedExercises[ex.ExerciseID] {
			qw422016.N().S(`, weighted`)
		}
		qw422016.N().S(`)
`)
	}
	qw422016.N().S(`

`)
	if len(progressions) > 0 {
		qw422016.N().S(`
Progression signals:
`)
		for _, p := range progressions {
			qw422016.N().S(`- `)
			qw422016.E().S(p.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(p.Action)
			if p.FromWeight > 0 {
				qw422016.N().S(` from `)
				qw422016.E().S(fmt.Sprintf("%.1f", p.FromWeight))
				qw422016.N().S(`kg`)
			}
			if p.ToWeight > 0 {
				qw422016.N().S(` to `)
				qw422016.E().S(fmt.Sprintf("%.1f", p.ToWeight))
				qw422016.N().S(`kg`)
			}
			qw422016.N().S(` (`)
			qw422016.E().S(p.Signal)
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(modifiers) > 0 {
		qw422016.N().S(`
[MODIFIERS]
`)
		for _, mod := range modifiers {
			qw422016.E().S(mod.ID)
			qw422016.N().S(`: [`)
			qw422016.E().S(strings.Join(mod.Patterns, ","))
			qw422016.N().S(`]`)
			if len(mod.Antipatterns) > 0 {
				qw422016.N().S(` (exclude: [`)
				qw422016.E().S(strings.Join(mod.Antipatterns, ","))
				qw422016.N().S(`])`)
			}
			variants := modifierVariants[mod.ID]

			if len(variants) > 0 {
				qw422016.N().S(` (available: `)
				for i, w := range variants {
					qw422016.E().S(fmt.Sprintf("%.1f", w))
					qw422016.N().S(`kg`)
					if i < len(variants)-1 {
						qw422016.N().S(`, `)
					}
				}
				qw422016.N().S(`)`)
			}
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(equipmentIDs) > 0 {
		qw422016.N().S(`
Equipment: `)
		qw422016.E().S(strings.Join(equipmentIDs, ", "))
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(facts) > 0 {
		qw422016.N().S(`
[FACTS]
`)
		for i, fact := range facts {
			qw422016.N().S(`- [F`)
			qw422016.N().D(i)
			qw422016.N().S(`] `)
			qw422016.E().S(fact.Content)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if skipWarmupCooldown {
		qw422016.N().S(`Work routine only, no warmup/cooldown.`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeLoadUser(qq422016 qtio422016.Writer,
	exercises []pipeline.SelectedExercise,
	exerciseModes map[string]string,
	weightedExercises map[string]bool,
	progressions []pipeline.ProgressionSignal,
	volumeTarget string,
	intensityTarget string,
	modifiers []model.Modifier,
	modifierVariants map[string][]float64,
	facts []model.Fact,
	equipmentIDs []string,
	favoriteEquipmentIDs []string,
	skipWarmupCooldown bool,
	duration int,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeLoadUser(qw422016, exercises, exerciseModes, weightedExercises, progressions, volumeTarget, intensityTarget, modifiers, modifierVariants, facts, equipmentIDs, favoriteEquipmentIDs, skipWarmupCooldown, duration)
	qt422016.ReleaseWriter(qw422016)
}

func NodeLoadUser(
	exercises []pipeline.SelectedExercise,
	exerciseModes map[string]string,
	weightedExercises map[string]bool,
	progressions []pipeline.ProgressionSignal,
	volumeTarget string,
	intensityTarget string,
	modifiers []model.Modifier,
	modifierVariants map[string][]float64,
	facts []model.Fact,
	equipmentIDs []string,
	favoriteEquipmentIDs []string,
	skipWarmupCooldown bool,
	duration int,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeLoadUser(qb422016, exercises, exerciseModes, weightedExercises, progressions, volumeTarget, intensityTarget, modifiers, modifierVariants, facts, equipmentIDs, favoriteEquipmentIDs, skipWarmupCooldown, duration)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
