// Code generated by qtc from "gen_flow.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamGenFlowStructuring(qw422016 *qt422016.Writer, reasoningOutput string) {
	qw422016.N().S(`Extract the flow session from the reasoning below into the provided JSON schema.
Use exercise IDs (not names) for exercise_id fields — copy them verbatim from the reasoning's [EXERCISES] list. Never invent IDs or add suffixes. Map [FN] markers to the fact_indices array.

`)
	qw422016.E().S(reasoningOutput)
	qw422016.N().S(`
`)
}

func WriteGenFlowStructuring(qq422016 qtio422016.Writer, reasoningOutput string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamGenFlowStructuring(qw422016, reasoningOutput)
	qt422016.ReleaseWriter(qw422016)
}

func GenFlowStructuring(reasoningOutput string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteGenFlowStructuring(qb422016, reasoningOutput)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
