// Code generated by qtc from "gen_training_constraints.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeConstraintsUser(qw422016 *qt422016.Writer, profiles []model.Profile) {
	for i, profile := range profiles {
		qw422016.N().S(`
`)
		if len(profiles) > 1 {
			qw422016.N().S(`Participant `)
			qw422016.N().D(i + 1)
			qw422016.N().S(`:
`)
		}
		qw422016.N().S(`Age:`)
		qw422016.N().D(profile.Age())
		qw422016.N().S(` Gender:`)
		qw422016.E().S(profile.Gender)
		qw422016.N().S(`
`)
		if len(profile.Injuries()) > 0 {
			qw422016.N().S(`Injuries: `)
			for j, injury := range profile.Injuries() {
				qw422016.E().S(injury.Description)
				qw422016.N().S(` (`)
				qw422016.N().D(injury.Year)
				qw422016.N().S(`)`)
				if j < len(profile.Injuries())-1 {
					qw422016.N().S(`, `)
				}
			}
			qw422016.N().S(`
`)
		}
		if len(profile.Limitations()) > 0 {
			qw422016.N().S(`Limitations: `)
			for j, limitation := range profile.Limitations() {
				qw422016.E().S(limitation)
				if j < len(profile.Limitations())-1 {
					qw422016.N().S(`, `)
				}
			}
			qw422016.N().S(`
`)
		}
		if len(profile.Conditions()) > 0 {
			qw422016.N().S(`Conditions: `)
			for j, condition := range profile.Conditions() {
				qw422016.E().S(condition)
				if j < len(profile.Conditions())-1 {
					qw422016.N().S(`, `)
				}
			}
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(profiles) > 1 {
		qw422016.N().S(`Use the most restrictive constraints across all participants.`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeConstraintsUser(qq422016 qtio422016.Writer, profiles []model.Profile) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeConstraintsUser(qw422016, profiles)
	qt422016.ReleaseWriter(qw422016)
}

func NodeConstraintsUser(profiles []model.Profile) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeConstraintsUser(qb422016, profiles)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
