// Code generated by qtc from "gen_training_history.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "encoding/json"

import "github.com/google/uuid"

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeHistorySystem(qw422016 *qt422016.Writer) {
	qw422016.N().S(`You are a training history analyst. Review recent training sessions and user feedback to identify progression signals.

Output a JSON object with:
- progressions: array of {exercise_id, action, from_weight, to_weight, signal} where action is one of: increase_weight, decrease_weight, increase_reps, decrease_reps, replace, add_modifier
- avoid_exercises: array of exercise IDs rated "impossible" or consistently "too_hard"
- recent_names: array of training names from history (to avoid reusing)
- pattern_notes: one sentence about overall patterns (e.g. "user finds leg sessions too hard")
- bad_session_notes: one sentence if any recent session was rated bad, empty string otherwise
- summary: one-sentence plain-language summary of what the history reveals (e.g. "user is progressing well on pressing movements but struggles with legs"), written conversationally without technical labels

Rules:
- "too_easy" → increase_weight or increase_reps or add_modifier
- "too_hard" → decrease_weight or decrease_reps
- "impossible" → replace (add to avoid_exercises)
- If quality was rated bad, note the reason
- Be concise — only report actionable signals
`)
}

func WriteNodeHistorySystem(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeHistorySystem(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func NodeHistorySystem() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeHistorySystem(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeHistoryUser(qw422016 *qt422016.Writer,
	recentTrainings []model.Training,
	recentFeedback map[uuid.UUID]model.TrainingFeedback,
	recentHR map[uuid.UUID]*model.HealthExerciseSession,
) {
	if len(recentTrainings) == 0 {
		qw422016.N().S(`No training history. Return empty progressions, avoid_exercises, recent_names, and empty notes.
`)
	} else {
		qw422016.N().S(`
`)
		for _, training := range recentTrainings {
			qw422016.N().S(`
`)
			fb, hasFb := recentFeedback[training.ID]

			qw422016.N().S(`
`)
			var afb map[string]string
			if hasFb {
				json.Unmarshal(fb.ActivityFeedback, &afb)
			}

			qw422016.N().S(`
`)
			actWeights := activityWeights(training)

			qw422016.N().S(`
- "`)
			qw422016.E().S(training.Name)
			qw422016.N().S(`" | `)
			qw422016.N().D(training.DaysSince())
			qw422016.N().S(`d ago | `)
			qw422016.E().S(training.Methodology)
			if training.CompletedIn != nil {
				qw422016.N().S(` | `)
				qw422016.N().D(*training.CompletedIn / 60)
				qw422016.N().S(`min`)
			}
			if hasFb && fb.Quality != nil {
				if *fb.Quality {
					qw422016.N().S(` | good`)
				} else {
					qw422016.N().S(` | bad`)
					if fb.QualityReason != "" {
						qw422016.N().S(` (`)
						qw422016.E().S(fb.QualityReason)
						qw422016.N().S(`)`)
					}
				}
			}
			if hasFb && fb.Message != "" {
				qw422016.N().S(` | "`)
				qw422016.E().S(fb.Message)
				qw422016.N().S(`"`)
			}
			hr := recentHR[training.ID]

			if hr != nil && hr.AvgHR != nil {
				qw422016.N().S(` | HR avg `)
				qw422016.N().D(*hr.AvgHR)
				if hr.MaxHR != nil {
					qw422016.N().S(` max `)
					qw422016.N().D(*hr.MaxHR)
				}
				qw422016.N().S(`bpm`)
			}
			qw422016.N().S(`
`)
			seen := make(map[string]bool)

			for exID, act := range actWeights {
				seen[exID] = true

				qw422016.N().S(`  `)
				qw422016.E().S(exID)
				qw422016.N().S(`: `)
				qw422016.E().S(formatWeight(act.WeightKg))
				qw422016.N().S(`×`)
				qw422016.N().D(act.Reps)
				if fb := afb[exID]; len(fb) > 0 {
					qw422016.N().S(` (`)
					qw422016.E().S(fb)
					qw422016.N().S(`)`)
				}
				qw422016.N().S(`
`)
			}
			for exID, exFb := range afb {
				if !seen[exID] && len(exFb) > 0 {
					qw422016.N().S(`  `)
					qw422016.E().S(exID)
					qw422016.N().S(`: `)
					qw422016.E().S(exFb)
					qw422016.N().S(`
`)
				}
			}
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeHistoryUser(qq422016 qtio422016.Writer,
	recentTrainings []model.Training,
	recentFeedback map[uuid.UUID]model.TrainingFeedback,
	recentHR map[uuid.UUID]*model.HealthExerciseSession,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeHistoryUser(qw422016, recentTrainings, recentFeedback, recentHR)
	qt422016.ReleaseWriter(qw422016)
}

func NodeHistoryUser(
	recentTrainings []model.Training,
	recentFeedback map[uuid.UUID]model.TrainingFeedback,
	recentHR map[uuid.UUID]*model.HealthExerciseSession,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeHistoryUser(qb422016, recentTrainings, recentFeedback, recentHR)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
