// Code generated by qtc from "gen_training_creative.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "strings"

import "github.com/streambinder/vigor/llm/pipeline"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeCreativeSystem(qw422016 *qt422016.Writer, language string) {
	qw422016.N().S(`You are a copywriter for a fitness app. Write a training session title and description.
All output must be in `)
	qw422016.E().S(language)
	qw422016.N().S(`.

Output a JSON object with:
- name: string (3-4 memorable words)
- description: string (3-5 sentences)

Title rules:
- Reflect workout character (intensity, focus, energy)
- Action words, alliteration, or evocative phrases
- Match methodology tone: strength=powerful, circuit/HIIT=fast, mobility=flowing
- Never use: all caps, methodology names, goal lists, generic terms ("training", "workout")
- Never reuse names from the recent names list

Description rules:
- Open with the methodology and primary focus
- Only surface progression decisions listed under "Progression decisions" below, and only for the exercises in this session — without using labels like "too_easy" or "too_hard" (say "you've been handling this weight well" or "pulling back here"). If none are listed, do NOT invent or mention any rep/weight changes.
- Only mention recovery/readiness if a recovery adjustment was actually applied (shown below) — state the rationale without naming metrics (say "keeping volume moderate to support recovery"). If no adjustment was applied, do NOT claim the session was scaled for recovery.
- Close with key exercises or structural highlights
- The user should feel their feedback was read and acted on
`)
}

func WriteNodeCreativeSystem(qq422016 qtio422016.Writer, language string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeCreativeSystem(qw422016, language)
	qt422016.ReleaseWriter(qw422016)
}

func NodeCreativeSystem(language string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeCreativeSystem(qb422016, language)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeCreativeUser(qw422016 *qt422016.Writer,
	methodology string,
	primaryMuscles []string,
	exercises []pipeline.SelectedExercise,
	progressions []pipeline.ProgressionSignal,
	healthRationale string,
	volumeModifier float64,
	intensityModifier float64,
	extendWarmup bool,
	recentNames []string,
	badSessionNotes string,
) {
	qw422016.N().S(`Methodology: `)
	qw422016.E().S(methodology)
	qw422016.N().S(`
Focus: `)
	qw422016.E().S(strings.Join(primaryMuscles, ", "))
	qw422016.N().S(`

Exercises:
`)
	for _, ex := range exercises {
		if ex.Phase == "work" {
			qw422016.N().S(`- `)
			qw422016.E().S(ex.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(ex.Rationale)
			qw422016.N().S(`
`)
		}
	}
	qw422016.N().S(`

`)
	if len(progressions) > 0 {
		qw422016.N().S(`
Progression decisions:
`)
		for _, p := range progressions {
			qw422016.N().S(`- `)
			qw422016.E().S(p.ExerciseID)
			qw422016.N().S(`: `)
			qw422016.E().S(p.Action)
			qw422016.N().S(` (`)
			qw422016.E().S(p.Signal)
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	recoveryApplied := volumeModifier < 1.0 || intensityModifier < 1.0 || extendWarmup

	qw422016.N().S(`
`)
	if recoveryApplied {
		qw422016.N().S(`Recovery adjustment applied — volume at `)
		qw422016.N().D(int(volumeModifier * 100))
		qw422016.N().S(`%, intensity at `)
		qw422016.N().D(int(intensityModifier * 100))
		qw422016.N().S(`%`)
		if extendWarmup {
			qw422016.N().S(`, extended warmup`)
		}
		qw422016.N().S(`. `)
		if healthRationale != "" {
			qw422016.N().S(`Reason: `)
			qw422016.E().S(healthRationale)
		}
		qw422016.N().S(`
Mention this readiness-based scaling in the description (without naming metrics).
`)
	} else {
		qw422016.N().S(`No recovery adjustment was applied — do NOT mention recovery, readiness, or volume/intensity reduction in the description.
`)
	}
	qw422016.N().S(`
`)
	if badSessionNotes != "" {
		qw422016.N().S(`
Recent issue: `)
		qw422016.E().S(badSessionNotes)
	}
	qw422016.N().S(`
`)
	if len(recentNames) > 0 {
		qw422016.N().S(`
Do not reuse these names: `)
		qw422016.E().S(strings.Join(recentNames, ", "))
	}
	qw422016.N().S(`
`)
}

func WriteNodeCreativeUser(qq422016 qtio422016.Writer,
	methodology string,
	primaryMuscles []string,
	exercises []pipeline.SelectedExercise,
	progressions []pipeline.ProgressionSignal,
	healthRationale string,
	volumeModifier float64,
	intensityModifier float64,
	extendWarmup bool,
	recentNames []string,
	badSessionNotes string,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeCreativeUser(qw422016, methodology, primaryMuscles, exercises, progressions, healthRationale, volumeModifier, intensityModifier, extendWarmup, recentNames, badSessionNotes)
	qt422016.ReleaseWriter(qw422016)
}

func NodeCreativeUser(
	methodology string,
	primaryMuscles []string,
	exercises []pipeline.SelectedExercise,
	progressions []pipeline.ProgressionSignal,
	healthRationale string,
	volumeModifier float64,
	intensityModifier float64,
	extendWarmup bool,
	recentNames []string,
	badSessionNotes string,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeCreativeUser(qb422016, methodology, primaryMuscles, exercises, progressions, healthRationale, volumeModifier, intensityModifier, extendWarmup, recentNames, badSessionNotes)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
