// Code generated by qtc from "gen_training_health.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeHealthUser(qw422016 *qt422016.Writer, healthSnapshot *model.HealthSnapshot) {
	if healthSnapshot == nil || !healthSnapshot.HasRecoverySignal() {
		qw422016.N().S(`No recovery metrics available.
`)
	} else {
		qw422016.N().S(`
`)
		if healthSnapshot.SleepPresent {
			qw422016.N().S(`Sleep last night: `)
			qw422016.N().FPrec(healthSnapshot.SleepHours, 1)
			qw422016.N().S(`h (30-day baseline: `)
			qw422016.N().FPrec(healthSnapshot.SleepBaseline, 1)
			qw422016.N().S(`h, deviation: `)
			qw422016.E().S(formatDeviation(healthSnapshot.SleepDeviation))
			qw422016.N().S(`)
`)
		}
		qw422016.N().S(`
`)
		if healthSnapshot.HRVPresent {
			qw422016.N().S(`HRV: `)
			qw422016.N().FPrec(healthSnapshot.HRVRMSSD, 0)
			qw422016.N().S(`ms RMSSD today; 7-day average `)
			qw422016.N().FPrec(healthSnapshot.HRVRecentAvg, 0)
			qw422016.N().S(`ms`)
			if healthSnapshot.HRVHasZScore {
				qw422016.N().S(` vs 28-day reference `)
				qw422016.N().FPrec(healthSnapshot.HRVBaseline, 0)
				qw422016.N().S(`ms (`)
				qw422016.E().S(formatSD(healthSnapshot.HRVZScore))
				qw422016.N().S(` SD)`)
			} else {
				qw422016.N().S(` (reference: `)
				qw422016.N().FPrec(healthSnapshot.HRVBaseline, 0)
				qw422016.N().S(`ms, deviation: `)
				qw422016.E().S(formatDeviation(healthSnapshot.HRVDeviation))
				qw422016.N().S(`)`)
			}
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
		if healthSnapshot.RHRPresent {
			qw422016.N().S(`Resting HR: `)
			qw422016.N().D(healthSnapshot.RestingHR)
			qw422016.N().S(`bpm (baseline: `)
			qw422016.N().FPrec(healthSnapshot.RHRBaseline, 0)
			qw422016.N().S(`bpm, 3-day average deviation: `)
			qw422016.E().S(formatSD(healthSnapshot.RHRDeviationBpm))
			qw422016.N().S(` bpm)
`)
		}
		qw422016.N().S(`
`)
		if len(healthSnapshot.ExternalWorkouts) > 0 {
			qw422016.N().S(`External workouts (last 7 days):
`)
			for _, w := range healthSnapshot.ExternalWorkouts {
				qw422016.N().S(`  - `)
				qw422016.N().D(w.DaysAgo)
				qw422016.N().S(` day`)
				if w.DaysAgo != 1 {
					qw422016.N().S(`s`)
				}
				qw422016.N().S(` ago: `)
				qw422016.E().S(w.ExerciseType)
				qw422016.N().S(`, `)
				qw422016.N().D(w.DurationMins)
				qw422016.N().S(`min
`)
			}
		}
		qw422016.N().S(`
Sleep baseline from `)
		qw422016.N().D(healthSnapshot.BaselineDays)
		qw422016.N().S(` days (30-day window); recovery reference from `)
		qw422016.N().D(healthSnapshot.RecoveryDays)
		qw422016.N().S(` days (60-day window).
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeHealthUser(qq422016 qtio422016.Writer, healthSnapshot *model.HealthSnapshot) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeHealthUser(qw422016, healthSnapshot)
	qt422016.ReleaseWriter(qw422016)
}

func NodeHealthUser(healthSnapshot *model.HealthSnapshot) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeHealthUser(qb422016, healthSnapshot)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
