// Code generated by qtc from "gen_training_strategy.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package prompt

import "fmt"

import "sort"

import "github.com/streambinder/vigor/model"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNodeStrategySystem(qw422016 *qt422016.Writer, methodology *model.Methodology, methodologies []model.Methodology, methodologyCoverage map[string]int, muscleCoverage map[string]int) {
	qw422016.N().S(`You are a training program strategist. Choose a methodology and define the session's muscle emphasis and intensity targets.

Output a JSON object with:
- methodology: string (methodology ID)
- methodology_reason: one sentence
- primary_muscles: array of muscle groups for high-volume emphasis
- secondary_muscles: array of muscle groups for maintenance volume
- volume_target: "low" | "moderate" | "high"
- intensity_target: "low" | "moderate" | "high"
- calibration_families: array of movement families to prioritize (empty if not calibrating)
- summary: one-sentence plain-language description of why this methodology was chosen and what the session targets (e.g. "chosen for its focus on controlled pulling movements, emphasizing mid-back and rear delts"), written conversationally

`)
	if methodology != nil {
		qw422016.N().S(`
Methodology is preselected: `)
		qw422016.E().S(methodology.ID)
		qw422016.N().S(`
`)
		qw422016.E().S(methodology.Description)
		qw422016.N().S(`
Use this methodology. Focus on muscle emphasis and volume/intensity targets.
`)
	} else {
		qw422016.N().S(`
Available methodologies (pick one):
`)
		for _, m := range methodologies {
			count := methodologyCoverage[m.ID]

			qw422016.N().S(`- `)
			qw422016.E().S(m.ID)
			qw422016.N().S(` [`)
			qw422016.N().D(count)
			qw422016.N().S(` compatible exercises]: `)
			qw422016.E().S(m.Description)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
Prefer methodologies with higher compatible exercise counts unless goals require otherwise.
`)
	}
	qw422016.N().S(`
`)
	if len(muscleCoverage) > 0 {
		qw422016.N().S(`
Trainable muscles with the available equipment (muscle: exercise count):
`)
		muscles := make([]string, 0, len(muscleCoverage))
		for m := range muscleCoverage {
			muscles = append(muscles, m)
		}
		sort.Slice(muscles, func(i, j int) bool {
			if muscleCoverage[muscles[i]] != muscleCoverage[muscles[j]] {
				return muscleCoverage[muscles[i]] > muscleCoverage[muscles[j]]
			}
			return muscles[i] < muscles[j]
		})

		for _, m := range muscles {
			qw422016.E().S(m)
			qw422016.N().S(`: `)
			qw422016.N().D(muscleCoverage[m])
			qw422016.N().S(`, `)
		}
		qw422016.N().S(`
primary_muscles and secondary_muscles MUST use only muscle names from the list above — never invent finer-grained names (e.g. "lats", "rhomboids", "hamstrings"); use the coarse names shown. primary_muscles MUST have a non-zero exercise count — never nominate a muscle the equipment can't train, even if the goal suggests it. Prefer higher-count muscles for primary emphasis.
`)
	}
	qw422016.N().S(`
`)
}

func WriteNodeStrategySystem(qq422016 qtio422016.Writer, methodology *model.Methodology, methodologies []model.Methodology, methodologyCoverage map[string]int, muscleCoverage map[string]int) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeStrategySystem(qw422016, methodology, methodologies, methodologyCoverage, muscleCoverage)
	qt422016.ReleaseWriter(qw422016)
}

func NodeStrategySystem(methodology *model.Methodology, methodologies []model.Methodology, methodologyCoverage map[string]int, muscleCoverage map[string]int) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeStrategySystem(qb422016, methodology, methodologies, methodologyCoverage, muscleCoverage)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamNodeStrategyUser(qw422016 *qt422016.Writer,
	goals []model.Goal,
	calibrationGaps map[string]int,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	skipWarmupCooldown bool,
) {
	qw422016.N().S(`Duration: `)
	qw422016.N().D(duration)
	qw422016.N().S(` minutes`)
	if skipWarmupCooldown {
		qw422016.N().S(` (work only, no warmup/cooldown)`)
	}
	qw422016.N().S(`

`)
	if len(goals) > 0 {
		qw422016.N().S(`
Goals:
`)
		for _, goal := range goals {
			qw422016.N().S(`- `)
			qw422016.E().S(goal.ID)
			qw422016.N().S(`: `)
			qw422016.E().S(goal.Description)
			qw422016.N().S(`
`)
		}
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if healthVolumeModifier < 1.0 || healthIntensityModifier < 1.0 {
		qw422016.N().S(`
Recovery status: volume at `)
		qw422016.E().S(fmt.Sprintf("%.0f%%", healthVolumeModifier*100))
		qw422016.N().S(`, intensity at `)
		qw422016.E().S(fmt.Sprintf("%.0f%%", healthIntensityModifier*100))
		qw422016.N().S(`. `)
		qw422016.E().S(healthRationale)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if historyPatternNotes != "" {
		qw422016.N().S(`History: `)
		qw422016.E().S(historyPatternNotes)
	}
	qw422016.N().S(`
`)
	if historyBadSessionNotes != "" {
		qw422016.N().S(`
Recent issue: `)
		qw422016.E().S(historyBadSessionNotes)
	}
	qw422016.N().S(`
`)
	if userPrompt != "" {
		qw422016.N().S(`
User request: `)
		qw422016.E().S(userPrompt)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`
`)
	if len(calibrationGaps) > 0 {
		qw422016.N().S(`
Calibration override: prioritize these under-sampled movement families over goals:
`)
		for family, count := range calibrationGaps {
			qw422016.N().S(`- `)
			qw422016.E().S(family)
			qw422016.N().S(` (`)
			qw422016.N().D(count)
			qw422016.N().S(`/5 sessions)
`)
		}
	}
	qw422016.N().S(`
`)
}

func WriteNodeStrategyUser(qq422016 qtio422016.Writer,
	goals []model.Goal,
	calibrationGaps map[string]int,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	skipWarmupCooldown bool,
) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNodeStrategyUser(qw422016, goals, calibrationGaps, healthVolumeModifier, healthIntensityModifier, healthRationale, historyPatternNotes, historyBadSessionNotes, userPrompt, duration, skipWarmupCooldown)
	qt422016.ReleaseWriter(qw422016)
}

func NodeStrategyUser(
	goals []model.Goal,
	calibrationGaps map[string]int,
	healthVolumeModifier float64,
	healthIntensityModifier float64,
	healthRationale string,
	historyPatternNotes string,
	historyBadSessionNotes string,
	userPrompt string,
	duration int,
	skipWarmupCooldown bool,
) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNodeStrategyUser(qb422016, goals, calibrationGaps, healthVolumeModifier, healthIntensityModifier, healthRationale, historyPatternNotes, historyBadSessionNotes, userPrompt, duration, skipWarmupCooldown)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
