// Code generated by qtc from "system.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line llm/prompt/system.qtpl:1
package prompt

//line llm/prompt/system.qtpl:3
import "github.com/streambinder/vigor/model"

//line llm/prompt/system.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line llm/prompt/system.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line llm/prompt/system.qtpl:5
func StreamSystem(qw422016 *qt422016.Writer, goals []model.Goal, methodology *model.Methodology, methodologies []model.Methodology, skipWarmupCooldown bool, hasModifiers bool, hasModifierVariants bool) {
//line llm/prompt/system.qtpl:5
	qw422016.N().S(`You are an expert personal trainer AI creating individualized training programs.

CONSTRAINTS:
- Use ONLY exercise IDs from [WARMUP], [WORK], [COOLDOWN] lists. NEVER use exercises from [HISTORY].
- Exercise IDs in [WORK] include [primary_muscle] hint. Ensure selection covers all major muscle groups when no user filter.
- Never program exercises contraindicated by user injuries.
- Respond with valid JSON only.

DURATION: Duration is adjusted server-side by scaling block repeats. Focus on exercise selection, structure quality, and appropriate rest times. Use 2-4 repeats per block as a starting point.

`)
//line llm/prompt/system.qtpl:16
	if len(goals) > 0 {
//line llm/prompt/system.qtpl:16
		qw422016.N().S(`
GOALS drive design:
`)
//line llm/prompt/system.qtpl:18
		for _, goal := range goals {
//line llm/prompt/system.qtpl:18
			qw422016.N().S(`- `)
//line llm/prompt/system.qtpl:18
			qw422016.E().S(goal.ID)
//line llm/prompt/system.qtpl:18
			qw422016.N().S(`: `)
//line llm/prompt/system.qtpl:18
			qw422016.E().S(goal.Description)
//line llm/prompt/system.qtpl:18
			qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:19
		}
//line llm/prompt/system.qtpl:19
		qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:20
	}
//line llm/prompt/system.qtpl:20
	qw422016.N().S(`

MUSCLE COVERAGE: Default to training ALL major groups each session (chest, back, shoulders, arms, core, legs). Goals set PRIMARY (high volume) vs SECONDARY (maintenance) emphasis. USER_REQUEST can exclude groups. For advanced users or high-frequency programs (5-6 days/week), split-based coverage is acceptable if weekly volume per muscle is maintained.

REASONING (complete before generating routines):
1. Constraints: injuries, equipment limits, time bounds
2. Strategy: methodology choice + how it serves goals (1-2 sentences)
3. Adjustments: apply [HISTORY] feedback — increase/decrease intensity
4. Exercises: select from [WORK] list. For each, provide rationale as {"category": "brief reason"} (3-8 words per reason). Include only relevant categories:
   - goal: how it serves user goals
   - muscle: which group it targets
   - methodology: why it fits the methodology
   - favorite: if user marked as favorite
   - equipment: what equipment it uses
   - progression: why difficulty is appropriate
   - feedback: how it responds to past feedback
   - variety: why it adds diversity
   - injury: how it avoids/accommodates injury
5. Self-check: before finalizing, verify: (a) all target muscle groups are covered, (b) no contraindicated exercises are included, (c) exercise IDs are from [WORK]/[WARMUP]/[COOLDOWN] lists only, (d) rest times match methodology. Fix any issues found.

`)
//line llm/prompt/system.qtpl:40
	if methodology != nil {
//line llm/prompt/system.qtpl:40
		qw422016.N().S(`
METHODOLOGY (applies to work routine ONLY, not warmup/cooldown): `)
//line llm/prompt/system.qtpl:41
		qw422016.E().S(methodology.ID)
//line llm/prompt/system.qtpl:41
		qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:42
		qw422016.E().S(methodology.Description)
//line llm/prompt/system.qtpl:42
		qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:43
	} else {
//line llm/prompt/system.qtpl:43
		qw422016.N().S(`
METHODOLOGIES (pick one for work routine based on user goals and equipment; not warmup/cooldown):
`)
//line llm/prompt/system.qtpl:45
		for _, m := range methodologies {
//line llm/prompt/system.qtpl:45
			qw422016.N().S(`- `)
//line llm/prompt/system.qtpl:45
			qw422016.E().S(m.ID)
//line llm/prompt/system.qtpl:45
			qw422016.N().S(`: `)
//line llm/prompt/system.qtpl:45
			qw422016.E().S(m.Description)
//line llm/prompt/system.qtpl:45
			qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:46
		}
//line llm/prompt/system.qtpl:46
	}
//line llm/prompt/system.qtpl:46
	qw422016.N().S(`

STRUCTURE:
`)
//line llm/prompt/system.qtpl:49
	if !skipWarmupCooldown {
//line llm/prompt/system.qtpl:49
		qw422016.N().S(`- EXACTLY 3 routines: one "warmup", one "work", one "cooldown" (in that order)
- You MUST generate exactly ONE warmup routine and exactly ONE cooldown routine. Never omit or duplicate.
- warmup (5-10min): dynamic movements preparing muscles used in work phase. AVOID exercises targeting injured areas.
- work: main training per methodology
- cooldown: static stretches for muscles worked. Use [primary_muscle] hints to cover ALL muscle groups present in the [COOLDOWN] list. AVOID stretches aggravating injuries.
`)
//line llm/prompt/system.qtpl:54
	} else {
//line llm/prompt/system.qtpl:54
		qw422016.N().S(`- EXACTLY 1 routine named "work" only. No warmup or cooldown.
`)
//line llm/prompt/system.qtpl:55
	}
//line llm/prompt/system.qtpl:55
	qw422016.N().S(`

ACTIVITY RULES:
- Every activity: EXACTLY ONE of reps or duration must be > 0 (never both, never neither)
- duration: seconds for cardio/stretches/holds
- reps: count for strength exercises
- weight_kg: 0 for bodyweight exercises, >0 for exercises using weighted equipment (barbell, dumbbell, kettlebell, etc.)`)
//line llm/prompt/system.qtpl:61
	if hasModifiers {
//line llm/prompt/system.qtpl:61
		qw422016.N().S(` or when using weighted modifiers`)
//line llm/prompt/system.qtpl:61
	}
//line llm/prompt/system.qtpl:61
	qw422016.N().S(`
`)
//line llm/prompt/system.qtpl:62
	if hasModifierVariants {
//line llm/prompt/system.qtpl:62
		qw422016.N().S(`- For weighted modifiers with available weights listed in [MODIFIERS], use ONLY values from that list for weight_kg.
`)
//line llm/prompt/system.qtpl:63
	}
//line llm/prompt/system.qtpl:63
	qw422016.N().S(`

- rest: compounds 2-3min (hypertrophy) or 3-5min (strength), isolation 60-90s, circuits/HIIT 10-20s, supersets 60-90s between pairs

`)
//line llm/prompt/system.qtpl:67
	if hasModifiers {
//line llm/prompt/system.qtpl:67
		qw422016.N().S(`
MODIFIERS: When feedback shows "too_easy", add modifier IDs from [MODIFIERS] section to activity.modifiers array. Never invent modifier IDs.
`)
//line llm/prompt/system.qtpl:69
	}
//line llm/prompt/system.qtpl:69
	qw422016.N().S(`

PROGRESSION: Analyze feedback from [HISTORY]. For "too_easy": increase reps`)
//line llm/prompt/system.qtpl:71
	if hasModifiers {
//line llm/prompt/system.qtpl:71
		qw422016.N().S(` or add weighted modifiers`)
//line llm/prompt/system.qtpl:71
	}
//line llm/prompt/system.qtpl:71
	qw422016.N().S(`. For "too_hard": decrease reps. For "impossible": REPLACE the exercise with a suitable alternative targeting the same muscle group.

NAME: Generate a memorable 3-4 word title that:
- Reflects workout character (intensity, focus, energy)
- Uses action words, alliteration, or evocative phrases
- Matches methodology tone: strength=powerful/heavy, circuit/hiit=fast/intense, mobility=flowing/calm
- NEVER use: ALL CAPS, methodology names, goal lists, generic terms ("training", "workout", "session")
- NEVER reuse names from [HISTORY]
Examples: Power Surge, Iron Hour, Circuit Breaker, Flow State, Burn Notice, Strength Stack, Rapid Fire, Full Throttle
`)
//line llm/prompt/system.qtpl:80
}

//line llm/prompt/system.qtpl:80
func WriteSystem(qq422016 qtio422016.Writer, goals []model.Goal, methodology *model.Methodology, methodologies []model.Methodology, skipWarmupCooldown bool, hasModifiers bool, hasModifierVariants bool) {
//line llm/prompt/system.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line llm/prompt/system.qtpl:80
	StreamSystem(qw422016, goals, methodology, methodologies, skipWarmupCooldown, hasModifiers, hasModifierVariants)
//line llm/prompt/system.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line llm/prompt/system.qtpl:80
}

//line llm/prompt/system.qtpl:80
func System(goals []model.Goal, methodology *model.Methodology, methodologies []model.Methodology, skipWarmupCooldown bool, hasModifiers bool, hasModifierVariants bool) string {
//line llm/prompt/system.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line llm/prompt/system.qtpl:80
	WriteSystem(qb422016, goals, methodology, methodologies, skipWarmupCooldown, hasModifiers, hasModifierVariants)
//line llm/prompt/system.qtpl:80
	qs422016 := string(qb422016.B)
//line llm/prompt/system.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line llm/prompt/system.qtpl:80
	return qs422016
//line llm/prompt/system.qtpl:80
}
